#!/usr/bin/env python3
"""Generate per-area aggregate test runners.

Why this exists
---------------
Each test file is a standalone Mojo program, and the ``tests`` task ran one
``mojo -I .`` per file -- 215 compiler invocations against an ~90k-line
source graph, where the measured per-file cost is dominated by compilation
rather than by the test bodies. Aggregating the files of an area into one
binary pays the elaboration cost once per area instead of once per file.

What it emits
-------------
``tests/_agg/agg_<area>.mojo`` per area: aliased imports of every
module-level ``def test_*`` in that area, then explicit registration on a
``TestSuite``.

Two things are deliberate:

* **Imports are aliased** (``test_x as http__test_router__test_x``). Areas
  contain duplicated private helper names and at least one real collision
  (``test_literal_root``), and aliasing means none of them need renaming --
  each file keeps its own module namespace.

* **Registration is explicit, never discovery.** ``discover_tests`` inside
  an aggregate finds the *aggregate's* functions, of which there are none,
  so it prints "Running 0 tests ... 0 failed" and exits 0 -- a green run
  that executed nothing. Explicit ``s.test[fn]()`` lines cannot do that,
  and ``--check`` below is the drift gate that keeps the generated files
  honest.

Excluded files
--------------
``EXCLUDE`` lists tests that mutate process-global state (env vars, named
semaphores, io_uring registrations) and so cannot share a process with
their neighbours. They stay standalone binaries.

Usage
-----
    python3 tests/tools/gen_test_aggregates.py           # write the aggregates
    python3 tests/tools/gen_test_aggregates.py --check   # fail if out of date
"""

from __future__ import annotations

import glob
import os
import re
import subprocess
import sys

TESTS = "tests"
OUT_DIR = os.path.join(TESTS, "_agg")

# Tests that mutate process-global state; they must keep their own process.
EXCLUDE = {
    "tests/runtime/test_block_in_pool.mojo",
    "tests/runtime/test_closure_send_contract.mojo",
    "tests/runtime/test_handoff.mojo",
    "tests/runtime/test_uring_bufring_dispatch.mojo",
    # `test_sqe_construction_zeros_buffer` asserts a freshly constructed
    # `IoUringSqe` presents 64 zero bytes. Standalone it passes; sharing a
    # process with `test_io_uring_multishot_accept`'s real io_uring
    # round-trip it fails deterministically -- 6/6 CI attempts across two
    # commits, always `left: 64`. Standalone is what the per-file chain
    # already did, so this loses no coverage.
    #
    # The root cause is OPEN. Ruled out so far: the old `alloc[UInt8](n)`
    # spelling (51d042d migrated it to the Layout form and the failure did
    # not change), a merely dirty heap (a macOS probe that recycles filled
    # 64-byte blocks still sees a correctly zeroed buffer), and `alloc`'s
    # result being freed at scope exit (probed: the address is not handed
    # out again).
    #
    # Leading hypothesis, untested: `__deinit__` frees the 64-byte buffer
    # while the kernel may still hold the pointer from a submitted SQE, and
    # the value 64 lands in the recycled block *after* construction zeroed
    # it. If that is right it is a live-ness bug in `IoUringSqe`, not a test
    # artefact, and it affects the SQ writer. Needs a Linux box to confirm.
    "tests/runtime/test_io_uring_sqe.mojo",
    "tests/runtime/test_reuseport.mojo",
    "tests/http/test_uring_serve_handler.mojo",
    "tests/http/test_uring_serve_handler_load.mojo",
    # Stress/soak: runtime-bound, not compile-bound, so aggregating it buys
    # nothing and it would dominate the aggregate's wall clock.
    "tests/runtime/stress_scheduler.mojo",
    # Flaky and not in the `tests` chain today: fails roughly 2 runs in 5
    # from `fetch_0rtt(max_polls=200)` timing out over loopback h3, and
    # costs ~20s when it does. Aggregating it would newly introduce a
    # nondeterministic failure into the gating job. It keeps its own
    # `test-h3-0rtt-e2e` task; a nightly job is the right home for it.
    "tests/h3/test_h3_0rtt_e2e.mojo",
}

TEST_DEF = re.compile(r"^def (test_[A-Za-z0-9_]*)\s*\(", re.M)

HEADER = '''"""GENERATED by tests/tools/gen_test_aggregates.py -- do not edit.

Aggregates the {n_files} test files of ``tests/{area}/`` into one compiled
binary so the {n_files} separate compiler invocations become one. Run it with
``mojo -I . -I tests/{area}`` (see tests/tools/run_test_aggregates.sh).

Regenerate with ``python3 tests/tools/gen_test_aggregates.py``; CI fails if this
file is out of date with the tree.
"""

from std.testing import TestSuite
'''


def area_of(path: str) -> str:
    rel = path[len(TESTS) + 1 :]
    return rel.split("/")[0] if "/" in rel else "_root"


def module_of(path: str) -> str:
    """Bare module name, resolved via an area-scoped ``-I``.

    Relative to the area directory, so it is resolved against
    ``-I tests/<area>``.

    Deliberately not rooted at ``tests``. Before the conformance fixtures
    moved under ``tests/conformance/``, the repo also had a top-level
    ``conformance/`` directory, and with both ``-I .`` and ``-I tests`` on
    the command line the name ``conformance`` resolved to the root one --
    which had no such submodule, so that aggregate failed to build.
    Scoping the include to the area sidesteps that class of collision for
    every area uniformly, so it stays the default even now that the
    specific top-level/nested clash is gone.

    Keeping the path *within* the area (rather than just the basename)
    matters for ``tests/grpc/proto/test_codegen.mojo``, the one test that
    lives in a subdirectory.
    """
    rel = path[len(TESTS) + 1 :]
    parts = rel[: -len(".mojo")].split("/")
    return ".".join(parts[1:]) if len(parts) > 1 else parts[0]


def alias(path: str, fn: str) -> str:
    return module_of(path).replace(".", "__") + "__" + fn


def discover() -> dict[str, list[tuple[str, list[str]]]]:
    """area -> [(file, [test fn names])], skipping excluded and empty files."""
    areas: dict[str, list[tuple[str, list[str]]]] = {}
    missing: list[str] = []
    for path in sorted(glob.glob(f"{TESTS}/**/*.mojo", recursive=True)):
        if path.startswith(OUT_DIR) or path in EXCLUDE:
            continue
        names = TEST_DEF.findall(open(path).read())
        if not names:
            # A file with no importable test is a generator bug, not
            # something to quietly drop -- dropping it silently deletes
            # coverage and nothing downstream notices.
            missing.append(path)
            continue
        areas.setdefault(area_of(path), []).append((path, names))
    if missing:
        sys.stderr.write(
            "ERROR: these files have no module-level `def test_*` and would\n"
            "be silently excluded. Give each a `def test_<name>() raises:`\n"
            "wrapper (or add it to EXCLUDE):\n"
            + "".join(f"  {p}\n" for p in missing)
        )
        raise SystemExit(2)
    return areas


def render(area: str, files: list[tuple[str, list[str]]]) -> str:
    out = [HEADER.format(area=area, n_files=len(files))]
    for path, names in files:
        mod = module_of(path)
        for fn in names:
            out.append(f"from {mod} import {fn} as {alias(path, fn)}\n")
    out.append("\n\ndef main() raises:\n    var suite = TestSuite()\n")
    for path, names in files:
        out.append(f"    # {path}\n")
        for fn in names:
            out.append(f"    suite.test[{alias(path, fn)}]()\n")
    out.append("    suite^.run()\n")
    return "".join(out)


def formatted(body: str) -> str:
    """Run `mojo format` over `body` and return the result.

    Write mode formats what it emits, so `--check` has to compare against
    formatted text or it reports every file as stale.
    """
    import tempfile

    with tempfile.TemporaryDirectory() as d:
        tmp = os.path.join(d, "cand.mojo")
        open(tmp, "w").write(body)
        try:
            subprocess.run(["mojo", "format", tmp], capture_output=True, text=True)
        except FileNotFoundError:
            raise SystemExit(
                "ERROR: `mojo` not on PATH. Run this via `pixi run tests-gen`;\n"
                "the candidate has to be formatted before it can be compared."
            )
        return open(tmp).read()


def main() -> int:
    check = "--check" in sys.argv
    areas = discover()
    os.makedirs(OUT_DIR, exist_ok=True)

    written, total_tests = [], 0
    for area, files in sorted(areas.items()):
        path = os.path.join(OUT_DIR, f"agg_{area}.mojo")
        body = render(area, files)
        total_tests += sum(len(n) for _, n in files)
        if check:
            prev = open(path).read() if os.path.exists(path) else ""
            if prev != formatted(body):
                sys.stderr.write(
                    f"ERROR: {path} is out of date. Run "
                    f"`python3 tests/tools/gen_test_aggregates.py`.\n"
                )
                return 1
        else:
            open(path, "w").write(body)
        written.append((area, len(files), sum(len(n) for _, n in files)))

    # Drop aggregates for areas that no longer exist.
    keep = {f"agg_{a}.mojo" for a, _, _ in written}
    for stale in sorted(os.listdir(OUT_DIR)) if os.path.isdir(OUT_DIR) else []:
        if stale.endswith(".mojo") and stale not in keep:
            if check:
                sys.stderr.write(f"ERROR: stale aggregate {stale}\n")
                return 1
            os.remove(os.path.join(OUT_DIR, stale))

    verb = "checked" if check else "wrote"
    for area, nf, nt in written:
        print(f"  {verb} agg_{area}.mojo  {nf:>3} files  {nt:>4} tests")
    print(f"  {len(written)} aggregates, {total_tests} tests total")

    if not check:
        fmt = subprocess.run(
            ["mojo", "format", OUT_DIR], capture_output=True, text=True
        )
        if fmt.returncode != 0:
            sys.stderr.write(fmt.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
