"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 12 test files of ``tests/tls/`` into one compiled
binary so the 12 separate compiler invocations become one. Run it with
``mojo -I . -I tests/tls`` (see tools/run_test_aggregates.sh).

Regenerate with ``python3 tools/gen_test_aggregates.py``; CI fails if this
file is out of date with the tree.
"""

from std.testing import TestSuite
from test_https_reactor import (
    test_https_reactor_h1_roundtrip as test_https_reactor__test_https_reactor_h1_roundtrip,
)
from test_https_reactor import (
    test_https_concurrent_connections as test_https_reactor__test_https_concurrent_connections,
)
from test_https_reactor import (
    test_https_reactor_streaming as test_https_reactor__test_https_reactor_streaming,
)
from test_https_reactor import (
    test_https_multi_worker as test_https_reactor__test_https_multi_worker,
)
from test_https_reactor import (
    test_https_alpn_negotiates_h2 as test_https_reactor__test_https_alpn_negotiates_h2,
)
from test_https_reactor import (
    test_https_alpn_h2_is_served as test_https_reactor__test_https_alpn_h2_is_served,
)
from test_https_reactor import (
    test_stalled_handshake_does_not_block_other_clients as test_https_reactor__test_stalled_handshake_does_not_block_other_clients,
)
from test_https_reactor import (
    test_bind_tls_constructs as test_https_reactor__test_bind_tls_constructs,
)
from test_rustls_quic import (
    test_config_defaults as test_rustls_quic__test_config_defaults,
)
from test_rustls_quic import (
    test_config_holds_alpn_list as test_rustls_quic__test_config_holds_alpn_list,
)
from test_rustls_quic import (
    test_encryption_level_codepoints as test_rustls_quic__test_encryption_level_codepoints,
)
from test_rustls_quic import (
    test_error_kind_codepoints as test_rustls_quic__test_error_kind_codepoints,
)
from test_rustls_quic import (
    test_not_built_error_carries_reason as test_rustls_quic__test_not_built_error_carries_reason,
)
from test_rustls_quic import (
    test_acceptor_constructs as test_rustls_quic__test_acceptor_constructs,
)
from test_rustls_quic import (
    test_acceptor_accept_raises as test_rustls_quic__test_acceptor_accept_raises,
)
from test_rustls_quic import (
    test_session_holds_dcid as test_rustls_quic__test_session_holds_dcid,
)
from test_rustls_quic import (
    test_session_starts_at_initial_level as test_rustls_quic__test_session_starts_at_initial_level,
)
from test_rustls_quic import (
    test_session_feed_crypto_raises as test_rustls_quic__test_session_feed_crypto_raises,
)
from test_rustls_quic import (
    test_session_take_crypto_raises as test_rustls_quic__test_session_take_crypto_raises,
)
from test_rustls_quic import (
    test_session_selected_alpn_raises as test_rustls_quic__test_session_selected_alpn_raises,
)
from test_rustls_quic_client import (
    test_connector_construct as test_rustls_quic_client__test_connector_construct,
)
from test_rustls_quic_client import (
    test_connector_bad_ca_is_null as test_rustls_quic_client__test_connector_bad_ca_is_null,
)
from test_rustls_quic_client import (
    test_connector_system_roots as test_rustls_quic_client__test_connector_system_roots,
)
from test_rustls_quic_client import (
    test_connect_fresh_session as test_rustls_quic_client__test_connect_fresh_session,
)
from test_rustls_quic_client import (
    test_client_emits_clienthello as test_rustls_quic_client__test_client_emits_clienthello,
)
from test_rustls_quic_client import (
    test_loopback_handshake_completes as test_rustls_quic_client__test_loopback_handshake_completes,
)
from test_rustls_quic_client import (
    test_peer_transport_params_roundtrip as test_rustls_quic_client__test_peer_transport_params_roundtrip,
)
from test_rustls_quic_crate_smoke import (
    test_abi_version as test_rustls_quic_crate_smoke__test_abi_version,
)
from test_rustls_quic_crate_smoke import (
    test_acceptor_new_rejects_empty_pem as test_rustls_quic_crate_smoke__test_acceptor_new_rejects_empty_pem,
)
from test_rustls_quic_handshake import (
    test_real_pem_acceptor_construct as test_rustls_quic_handshake__test_real_pem_acceptor_construct,
)
from test_rustls_quic_handshake import (
    test_accept_real_session as test_rustls_quic_handshake__test_accept_real_session,
)
from test_rustls_quic_handshake import (
    test_fresh_session_not_complete as test_rustls_quic_handshake__test_fresh_session_not_complete,
)
from test_rustls_quic_handshake import (
    test_fresh_session_no_alpn as test_rustls_quic_handshake__test_fresh_session_no_alpn,
)
from test_rustls_quic_handshake import (
    test_fresh_session_take_crypto_empty as test_rustls_quic_handshake__test_fresh_session_take_crypto_empty,
)
from test_rustls_quic_handshake import (
    test_feed_empty_crypto_is_noop as test_rustls_quic_handshake__test_feed_empty_crypto_is_noop,
)
from test_rustls_quic_handshake import (
    test_two_acceptors_are_independent as test_rustls_quic_handshake__test_two_acceptors_are_independent,
)
from test_rustls_quic_handshake import (
    test_two_sessions_are_independent as test_rustls_quic_handshake__test_two_sessions_are_independent,
)
from test_rustls_quic_keys import (
    test_fresh_session_has_no_keys_at_any_level as test_rustls_quic_keys__test_fresh_session_has_no_keys_at_any_level,
)
from test_rustls_quic_keys import (
    test_packet_encrypt_raises_when_keys_not_installed as test_rustls_quic_keys__test_packet_encrypt_raises_when_keys_not_installed,
)
from test_rustls_quic_keys import (
    test_packet_decrypt_raises_when_keys_not_installed as test_rustls_quic_keys__test_packet_decrypt_raises_when_keys_not_installed,
)
from test_rustls_quic_keys import (
    test_header_encrypt_raises_when_keys_not_installed as test_rustls_quic_keys__test_header_encrypt_raises_when_keys_not_installed,
)
from test_rustls_quic_keys import (
    test_header_decrypt_raises_when_keys_not_installed as test_rustls_quic_keys__test_header_decrypt_raises_when_keys_not_installed,
)
from test_rustls_quic_keys import (
    test_null_session_have_keys_returns_false as test_rustls_quic_keys__test_null_session_have_keys_returns_false,
)
from test_rustls_quic_keys import (
    test_null_session_packet_encrypt_raises as test_rustls_quic_keys__test_null_session_packet_encrypt_raises,
)
from test_rustls_quic_keys import (
    test_null_session_packet_decrypt_raises as test_rustls_quic_keys__test_null_session_packet_decrypt_raises,
)
from test_rustls_quic_keys import (
    test_null_session_header_encrypt_raises as test_rustls_quic_keys__test_null_session_header_encrypt_raises,
)
from test_rustls_quic_keys import (
    test_null_session_header_decrypt_raises as test_rustls_quic_keys__test_null_session_header_decrypt_raises,
)
from test_tls import (
    test_default_config_verify_required as test_tls__test_default_config_verify_required,
)
from test_tls import (
    test_insecure_config_no_verify as test_tls__test_insecure_config_no_verify,
)
from test_tls import test_custom_ca_bundle as test_tls__test_custom_ca_bundle
from test_tls import (
    test_custom_server_name as test_tls__test_custom_server_name,
)
from test_tls import (
    test_tls_handshake_error_str as test_tls__test_tls_handshake_error_str,
)
from test_tls import (
    test_certificate_expired_str as test_tls__test_certificate_expired_str,
)
from test_tls import (
    test_certificate_hostname_mismatch_str as test_tls__test_certificate_hostname_mismatch_str,
)
from test_tls import (
    test_certificate_untrusted_str as test_tls__test_certificate_untrusted_str,
)
from test_tls import (
    test_tls_connect_valid_cert_succeeds as test_tls__test_tls_connect_valid_cert_succeeds,
)
from test_tls import (
    test_tls_connect_insecure_succeeds as test_tls__test_tls_connect_insecure_succeeds,
)
from test_tls import (
    test_tls_connect_wrong_ca_raises as test_tls__test_tls_connect_wrong_ca_raises,
)
from test_tls import (
    test_tls_version_is_12_or_13 as test_tls__test_tls_version_is_12_or_13,
)
from test_tls import (
    test_tls_cipher_suite_is_forward_secret as test_tls__test_tls_cipher_suite_is_forward_secret,
)
from test_tls import (
    test_tls_peer_cert_subject_non_empty as test_tls__test_tls_peer_cert_subject_non_empty,
)
from test_tls import (
    test_tls_write_read_echo as test_tls__test_tls_write_read_echo,
)
from test_tls import (
    test_tls_close_idempotent as test_tls__test_tls_close_idempotent,
)
from test_tls_acceptor import (
    test_config_minimal as test_tls_acceptor__test_config_minimal,
)
from test_tls_acceptor import (
    test_config_with_alpn_and_mtls as test_tls_acceptor__test_config_with_alpn_and_mtls,
)
from test_tls_acceptor import (
    test_protocol_constants_distinct as test_tls_acceptor__test_protocol_constants_distinct,
)
from test_tls_acceptor import (
    test_config_handshake_timeout_default_and_custom as test_tls_acceptor__test_config_handshake_timeout_default_and_custom,
)
from test_tls_acceptor import (
    test_client_tls_config_default_alpn_empty as test_tls_acceptor__test_client_tls_config_default_alpn_empty,
)
from test_tls_acceptor import (
    test_client_tls_config_alpn_round_trip as test_tls_acceptor__test_client_tls_config_alpn_round_trip,
)
from test_tls_acceptor import (
    test_client_tls_config_alpn_oversized_id_rejected_at_handshake as test_tls_acceptor__test_client_tls_config_alpn_oversized_id_rejected_at_handshake,
)
from test_tls_acceptor import (
    test_mtls_requires_ca_bundle as test_tls_acceptor__test_mtls_requires_ca_bundle,
)
from test_tls_acceptor import (
    test_mtls_requires_ca_bundle_explicit_empty as test_tls_acceptor__test_mtls_requires_ca_bundle_explicit_empty,
)
from test_tls_acceptor import (
    test_mtls_with_ca_bundle_succeeds as test_tls_acceptor__test_mtls_with_ca_bundle_succeeds,
)
from test_tls_acceptor import (
    test_mtls_off_ignores_ca_bundle as test_tls_acceptor__test_mtls_off_ignores_ca_bundle,
)
from test_tls_acceptor import (
    test_tls_info_default_empty as test_tls_acceptor__test_tls_info_default_empty,
)
from test_tls_acceptor import (
    test_tls_info_with_values as test_tls_acceptor__test_tls_info_with_values,
)
from test_tls_acceptor import (
    test_acceptor_construct as test_tls_acceptor__test_acceptor_construct,
)
from test_tls_acceptor import (
    test_acceptor_construct_raises_on_missing_cert as test_tls_acceptor__test_acceptor_construct_raises_on_missing_cert,
)
from test_tls_acceptor import (
    test_acceptor_reload_swaps_cert as test_tls_acceptor__test_acceptor_reload_swaps_cert,
)
from test_tls_acceptor import (
    test_acceptor_reload_repeated_safe as test_tls_acceptor__test_acceptor_reload_repeated_safe,
)
from test_tls_acceptor import (
    test_acceptor_info_placeholder_returns_empty as test_tls_acceptor__test_acceptor_info_placeholder_returns_empty,
)
from test_tls_acceptor import (
    test_acceptor_with_alpn_succeeds as test_tls_acceptor__test_acceptor_with_alpn_succeeds,
)
from test_tls_acceptor import (
    test_acceptor_with_mtls_succeeds as test_tls_acceptor__test_acceptor_with_mtls_succeeds,
)
from test_tls_acceptor import (
    test_handshake_deadline_fires_on_silent_client as test_tls_acceptor__test_handshake_deadline_fires_on_silent_client,
)
from test_tls_acceptor import (
    test_tls_server_error_writes_message_and_code as test_tls_acceptor__test_tls_server_error_writes_message_and_code,
)
from test_tls_acceptor import (
    test_tls_server_not_implemented_default_message as test_tls_acceptor__test_tls_server_not_implemented_default_message,
)
from test_tls_acceptor import (
    test_acceptor_construct_slice_derived_paths as test_tls_acceptor__test_acceptor_construct_slice_derived_paths,
)
from test_tls_acceptor import (
    test_acceptor_reload_slice_derived_paths as test_tls_acceptor__test_acceptor_reload_slice_derived_paths,
)
from test_tls_acceptor import (
    test_acceptor_mtls_slice_derived_ca as test_tls_acceptor__test_acceptor_mtls_slice_derived_ca,
)
from test_tls_acceptor import (
    test_slice_derived_missing_cert_still_raises as test_tls_acceptor__test_slice_derived_missing_cert_still_raises,
)
from test_tls_conn_handle import (
    test_tls_conn_handle_handshake_alpn_sni_roundtrip as test_tls_conn_handle__test_tls_conn_handle_handshake_alpn_sni_roundtrip,
)
from test_tls_conn_handle import (
    test_tls_conn_handle_new_accept_is_nonblocking as test_tls_conn_handle__test_tls_conn_handle_new_accept_is_nonblocking,
)
from test_tls_handshake_live import (
    test_acceptor_with_alpn_constructs_clean as test_tls_handshake_live__test_acceptor_with_alpn_constructs_clean,
)
from test_tls_handshake_live import (
    test_acceptor_alpn_empty_skips_set_alpn_call as test_tls_handshake_live__test_acceptor_alpn_empty_skips_set_alpn_call,
)
from test_tls_handshake_live import (
    test_tls_info_default_fields_for_pre_handshake as test_tls_handshake_live__test_tls_info_default_fields_for_pre_handshake,
)
from test_tls_handshake_live import (
    test_reload_round_trip as test_tls_handshake_live__test_reload_round_trip,
)
from test_tls_handshake_live import (
    test_reload_repeated_safe as test_tls_handshake_live__test_reload_repeated_safe,
)
from test_tls_handshake_live import (
    test_acceptor_mtls_constructs_with_self_signed_ca as test_tls_handshake_live__test_acceptor_mtls_constructs_with_self_signed_ca,
)
from test_tls_handshake_live import (
    test_acceptor_mtls_misconfig_rejected as test_tls_handshake_live__test_acceptor_mtls_misconfig_rejected,
)
from test_tls_handshake_live import (
    test_acceptor_mtls_with_bad_ca_path_raises as test_tls_handshake_live__test_acceptor_mtls_with_bad_ca_path_raises,
)
from test_tls_resume import (
    test_session_round_trip_resumes as test_tls_resume__test_session_round_trip_resumes,
)
from test_tls_resume import (
    test_resume_with_empty_session_falls_back_to_full as test_tls_resume__test_resume_with_empty_session_falls_back_to_full,
)
from test_tls_resume import (
    test_session_addr_zero_when_not_yet_arrived as test_tls_resume__test_session_addr_zero_when_not_yet_arrived,
)
from test_tls_server_ffi import (
    test_server_ctx_new_succeeds_with_real_cert as test_tls_server_ffi__test_server_ctx_new_succeeds_with_real_cert,
)
from test_tls_server_ffi import (
    test_server_ctx_new_raises_on_missing_cert as test_tls_server_ffi__test_server_ctx_new_raises_on_missing_cert,
)
from test_tls_server_ffi import (
    test_server_ctx_new_raises_on_missing_key as test_tls_server_ffi__test_server_ctx_new_raises_on_missing_key,
)
from test_tls_server_ffi import (
    test_server_ctx_new_raises_on_mismatched_cert_key as test_tls_server_ffi__test_server_ctx_new_raises_on_mismatched_cert_key,
)
from test_tls_server_ffi import (
    test_set_alpn_h2_and_http11_succeeds as test_tls_server_ffi__test_set_alpn_h2_and_http11_succeeds,
)
from test_tls_server_ffi import (
    test_set_alpn_single_protocol_succeeds as test_tls_server_ffi__test_set_alpn_single_protocol_succeeds,
)
from test_tls_server_ffi import (
    test_set_alpn_empty_raises as test_tls_server_ffi__test_set_alpn_empty_raises,
)
from test_tls_server_ffi import (
    test_set_verify_client_cert_with_self_signed_ca as test_tls_server_ffi__test_set_verify_client_cert_with_self_signed_ca,
)
from test_tls_server_ffi import (
    test_set_verify_client_cert_raises_on_missing_path as test_tls_server_ffi__test_set_verify_client_cert_raises_on_missing_path,
)
from test_tls_server_ffi import (
    test_reload_succeeds_with_valid_pair as test_tls_server_ffi__test_reload_succeeds_with_valid_pair,
)
from test_tls_server_ffi import (
    test_reload_raises_on_bad_pair as test_tls_server_ffi__test_reload_raises_on_bad_pair,
)
from test_tls_server_ffi import (
    test_ssl_new_accept_returns_handle as test_tls_server_ffi__test_ssl_new_accept_returns_handle,
)
from test_tls_server_ffi import (
    test_alpn_selected_empty_before_handshake as test_tls_server_ffi__test_alpn_selected_empty_before_handshake,
)
from test_tls_server_ffi import (
    test_sni_host_empty_before_handshake as test_tls_server_ffi__test_sni_host_empty_before_handshake,
)


def main() raises:
    var suite = TestSuite()
    # tests/tls/test_https_reactor.mojo
    suite.test[test_https_reactor__test_https_reactor_h1_roundtrip]()
    suite.test[test_https_reactor__test_https_concurrent_connections]()
    suite.test[test_https_reactor__test_https_reactor_streaming]()
    suite.test[test_https_reactor__test_https_multi_worker]()
    suite.test[test_https_reactor__test_https_alpn_negotiates_h2]()
    suite.test[test_https_reactor__test_https_alpn_h2_is_served]()
    suite.test[
        test_https_reactor__test_stalled_handshake_does_not_block_other_clients
    ]()
    suite.test[test_https_reactor__test_bind_tls_constructs]()
    # tests/tls/test_rustls_quic.mojo
    suite.test[test_rustls_quic__test_config_defaults]()
    suite.test[test_rustls_quic__test_config_holds_alpn_list]()
    suite.test[test_rustls_quic__test_encryption_level_codepoints]()
    suite.test[test_rustls_quic__test_error_kind_codepoints]()
    suite.test[test_rustls_quic__test_not_built_error_carries_reason]()
    suite.test[test_rustls_quic__test_acceptor_constructs]()
    suite.test[test_rustls_quic__test_acceptor_accept_raises]()
    suite.test[test_rustls_quic__test_session_holds_dcid]()
    suite.test[test_rustls_quic__test_session_starts_at_initial_level]()
    suite.test[test_rustls_quic__test_session_feed_crypto_raises]()
    suite.test[test_rustls_quic__test_session_take_crypto_raises]()
    suite.test[test_rustls_quic__test_session_selected_alpn_raises]()
    # tests/tls/test_rustls_quic_client.mojo
    suite.test[test_rustls_quic_client__test_connector_construct]()
    suite.test[test_rustls_quic_client__test_connector_bad_ca_is_null]()
    suite.test[test_rustls_quic_client__test_connector_system_roots]()
    suite.test[test_rustls_quic_client__test_connect_fresh_session]()
    suite.test[test_rustls_quic_client__test_client_emits_clienthello]()
    suite.test[test_rustls_quic_client__test_loopback_handshake_completes]()
    suite.test[test_rustls_quic_client__test_peer_transport_params_roundtrip]()
    # tests/tls/test_rustls_quic_crate_smoke.mojo
    suite.test[test_rustls_quic_crate_smoke__test_abi_version]()
    suite.test[
        test_rustls_quic_crate_smoke__test_acceptor_new_rejects_empty_pem
    ]()
    # tests/tls/test_rustls_quic_handshake.mojo
    suite.test[test_rustls_quic_handshake__test_real_pem_acceptor_construct]()
    suite.test[test_rustls_quic_handshake__test_accept_real_session]()
    suite.test[test_rustls_quic_handshake__test_fresh_session_not_complete]()
    suite.test[test_rustls_quic_handshake__test_fresh_session_no_alpn]()
    suite.test[
        test_rustls_quic_handshake__test_fresh_session_take_crypto_empty
    ]()
    suite.test[test_rustls_quic_handshake__test_feed_empty_crypto_is_noop]()
    suite.test[test_rustls_quic_handshake__test_two_acceptors_are_independent]()
    suite.test[test_rustls_quic_handshake__test_two_sessions_are_independent]()
    # tests/tls/test_rustls_quic_keys.mojo
    suite.test[
        test_rustls_quic_keys__test_fresh_session_has_no_keys_at_any_level
    ]()
    suite.test[
        test_rustls_quic_keys__test_packet_encrypt_raises_when_keys_not_installed
    ]()
    suite.test[
        test_rustls_quic_keys__test_packet_decrypt_raises_when_keys_not_installed
    ]()
    suite.test[
        test_rustls_quic_keys__test_header_encrypt_raises_when_keys_not_installed
    ]()
    suite.test[
        test_rustls_quic_keys__test_header_decrypt_raises_when_keys_not_installed
    ]()
    suite.test[
        test_rustls_quic_keys__test_null_session_have_keys_returns_false
    ]()
    suite.test[test_rustls_quic_keys__test_null_session_packet_encrypt_raises]()
    suite.test[test_rustls_quic_keys__test_null_session_packet_decrypt_raises]()
    suite.test[test_rustls_quic_keys__test_null_session_header_encrypt_raises]()
    suite.test[test_rustls_quic_keys__test_null_session_header_decrypt_raises]()
    # tests/tls/test_tls.mojo
    suite.test[test_tls__test_default_config_verify_required]()
    suite.test[test_tls__test_insecure_config_no_verify]()
    suite.test[test_tls__test_custom_ca_bundle]()
    suite.test[test_tls__test_custom_server_name]()
    suite.test[test_tls__test_tls_handshake_error_str]()
    suite.test[test_tls__test_certificate_expired_str]()
    suite.test[test_tls__test_certificate_hostname_mismatch_str]()
    suite.test[test_tls__test_certificate_untrusted_str]()
    suite.test[test_tls__test_tls_connect_valid_cert_succeeds]()
    suite.test[test_tls__test_tls_connect_insecure_succeeds]()
    suite.test[test_tls__test_tls_connect_wrong_ca_raises]()
    suite.test[test_tls__test_tls_version_is_12_or_13]()
    suite.test[test_tls__test_tls_cipher_suite_is_forward_secret]()
    suite.test[test_tls__test_tls_peer_cert_subject_non_empty]()
    suite.test[test_tls__test_tls_write_read_echo]()
    suite.test[test_tls__test_tls_close_idempotent]()
    # tests/tls/test_tls_acceptor.mojo
    suite.test[test_tls_acceptor__test_config_minimal]()
    suite.test[test_tls_acceptor__test_config_with_alpn_and_mtls]()
    suite.test[test_tls_acceptor__test_protocol_constants_distinct]()
    suite.test[
        test_tls_acceptor__test_config_handshake_timeout_default_and_custom
    ]()
    suite.test[test_tls_acceptor__test_client_tls_config_default_alpn_empty]()
    suite.test[test_tls_acceptor__test_client_tls_config_alpn_round_trip]()
    suite.test[
        test_tls_acceptor__test_client_tls_config_alpn_oversized_id_rejected_at_handshake
    ]()
    suite.test[test_tls_acceptor__test_mtls_requires_ca_bundle]()
    suite.test[test_tls_acceptor__test_mtls_requires_ca_bundle_explicit_empty]()
    suite.test[test_tls_acceptor__test_mtls_with_ca_bundle_succeeds]()
    suite.test[test_tls_acceptor__test_mtls_off_ignores_ca_bundle]()
    suite.test[test_tls_acceptor__test_tls_info_default_empty]()
    suite.test[test_tls_acceptor__test_tls_info_with_values]()
    suite.test[test_tls_acceptor__test_acceptor_construct]()
    suite.test[
        test_tls_acceptor__test_acceptor_construct_raises_on_missing_cert
    ]()
    suite.test[test_tls_acceptor__test_acceptor_reload_swaps_cert]()
    suite.test[test_tls_acceptor__test_acceptor_reload_repeated_safe]()
    suite.test[
        test_tls_acceptor__test_acceptor_info_placeholder_returns_empty
    ]()
    suite.test[test_tls_acceptor__test_acceptor_with_alpn_succeeds]()
    suite.test[test_tls_acceptor__test_acceptor_with_mtls_succeeds]()
    suite.test[
        test_tls_acceptor__test_handshake_deadline_fires_on_silent_client
    ]()
    suite.test[
        test_tls_acceptor__test_tls_server_error_writes_message_and_code
    ]()
    suite.test[
        test_tls_acceptor__test_tls_server_not_implemented_default_message
    ]()
    suite.test[test_tls_acceptor__test_acceptor_construct_slice_derived_paths]()
    suite.test[test_tls_acceptor__test_acceptor_reload_slice_derived_paths]()
    suite.test[test_tls_acceptor__test_acceptor_mtls_slice_derived_ca]()
    suite.test[
        test_tls_acceptor__test_slice_derived_missing_cert_still_raises
    ]()
    # tests/tls/test_tls_conn_handle.mojo
    suite.test[
        test_tls_conn_handle__test_tls_conn_handle_handshake_alpn_sni_roundtrip
    ]()
    suite.test[
        test_tls_conn_handle__test_tls_conn_handle_new_accept_is_nonblocking
    ]()
    # tests/tls/test_tls_handshake_live.mojo
    suite.test[
        test_tls_handshake_live__test_acceptor_with_alpn_constructs_clean
    ]()
    suite.test[
        test_tls_handshake_live__test_acceptor_alpn_empty_skips_set_alpn_call
    ]()
    suite.test[
        test_tls_handshake_live__test_tls_info_default_fields_for_pre_handshake
    ]()
    suite.test[test_tls_handshake_live__test_reload_round_trip]()
    suite.test[test_tls_handshake_live__test_reload_repeated_safe]()
    suite.test[
        test_tls_handshake_live__test_acceptor_mtls_constructs_with_self_signed_ca
    ]()
    suite.test[test_tls_handshake_live__test_acceptor_mtls_misconfig_rejected]()
    suite.test[
        test_tls_handshake_live__test_acceptor_mtls_with_bad_ca_path_raises
    ]()
    # tests/tls/test_tls_resume.mojo
    suite.test[test_tls_resume__test_session_round_trip_resumes]()
    suite.test[
        test_tls_resume__test_resume_with_empty_session_falls_back_to_full
    ]()
    suite.test[test_tls_resume__test_session_addr_zero_when_not_yet_arrived]()
    # tests/tls/test_tls_server_ffi.mojo
    suite.test[
        test_tls_server_ffi__test_server_ctx_new_succeeds_with_real_cert
    ]()
    suite.test[
        test_tls_server_ffi__test_server_ctx_new_raises_on_missing_cert
    ]()
    suite.test[test_tls_server_ffi__test_server_ctx_new_raises_on_missing_key]()
    suite.test[
        test_tls_server_ffi__test_server_ctx_new_raises_on_mismatched_cert_key
    ]()
    suite.test[test_tls_server_ffi__test_set_alpn_h2_and_http11_succeeds]()
    suite.test[test_tls_server_ffi__test_set_alpn_single_protocol_succeeds]()
    suite.test[test_tls_server_ffi__test_set_alpn_empty_raises]()
    suite.test[
        test_tls_server_ffi__test_set_verify_client_cert_with_self_signed_ca
    ]()
    suite.test[
        test_tls_server_ffi__test_set_verify_client_cert_raises_on_missing_path
    ]()
    suite.test[test_tls_server_ffi__test_reload_succeeds_with_valid_pair]()
    suite.test[test_tls_server_ffi__test_reload_raises_on_bad_pair]()
    suite.test[test_tls_server_ffi__test_ssl_new_accept_returns_handle]()
    suite.test[test_tls_server_ffi__test_alpn_selected_empty_before_handshake]()
    suite.test[test_tls_server_ffi__test_sni_host_empty_before_handshake]()
    suite^.run()
