"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 1 test files of ``tests/tcp/`` into one compiled
binary so the 1 separate compiler invocations become one. Run it with
``mojo -I . -I tests/tcp`` (see tools/run_test_aggregates.sh).

Regenerate with ``python3 tools/gen_test_aggregates.py``; CI fails if this
file is out of date with the tree.
"""

from std.testing import TestSuite
from test_tcp import (
    test_listener_bind_port_zero_assigns_port as test_tcp__test_listener_bind_port_zero_assigns_port,
)
from test_tcp import (
    test_listener_local_addr_is_loopback as test_tcp__test_listener_local_addr_is_loopback,
)
from test_tcp import (
    test_listener_close_idempotent as test_tcp__test_listener_close_idempotent,
)
from test_tcp import (
    test_connect_to_listener_succeeds as test_tcp__test_connect_to_listener_succeeds,
)
from test_tcp import (
    test_connect_refused_raises_error as test_tcp__test_connect_refused_raises_error,
)
from test_tcp import (
    test_stream_peer_addr_matches_server as test_tcp__test_stream_peer_addr_matches_server,
)
from test_tcp import (
    test_stream_local_addr_is_nonzero as test_tcp__test_stream_local_addr_is_nonzero,
)
from test_tcp import (
    test_stream_close_idempotent as test_tcp__test_stream_close_idempotent,
)
from test_tcp import test_round_trip_1_byte as test_tcp__test_round_trip_1_byte
from test_tcp import test_round_trip_1_kb as test_tcp__test_round_trip_1_kb
from test_tcp import test_round_trip_64_kb as test_tcp__test_round_trip_64_kb
from test_tcp import (
    test_read_returns_zero_on_eof as test_tcp__test_read_returns_zero_on_eof,
)
from test_tcp import (
    test_bidirectional_ping_pong as test_tcp__test_bidirectional_ping_pong,
)
from test_tcp import (
    test_sequential_connections as test_tcp__test_sequential_connections,
)
from test_tcp import (
    test_tcp_nodelay_toggle as test_tcp__test_tcp_nodelay_toggle,
)
from test_tcp import test_keepalive_toggle as test_tcp__test_keepalive_toggle
from test_tcp import (
    test_recv_timeout_causes_timeout_error as test_tcp__test_recv_timeout_causes_timeout_error,
)
from test_tcp import (
    test_connect_timeout_blackhole as test_tcp__test_connect_timeout_blackhole,
)
from test_tcp import (
    test_reuseaddr_allows_rebind as test_tcp__test_reuseaddr_allows_rebind,
)
from test_tcp import test_v6_listener_bind as test_tcp__test_v6_listener_bind
from test_tcp import (
    test_v6_connect_loopback as test_tcp__test_v6_connect_loopback,
)
from test_tcp import test_v6_peer_addr as test_tcp__test_v6_peer_addr


def main() raises:
    var suite = TestSuite()
    # tests/tcp/test_tcp.mojo
    suite.test[test_tcp__test_listener_bind_port_zero_assigns_port]()
    suite.test[test_tcp__test_listener_local_addr_is_loopback]()
    suite.test[test_tcp__test_listener_close_idempotent]()
    suite.test[test_tcp__test_connect_to_listener_succeeds]()
    suite.test[test_tcp__test_connect_refused_raises_error]()
    suite.test[test_tcp__test_stream_peer_addr_matches_server]()
    suite.test[test_tcp__test_stream_local_addr_is_nonzero]()
    suite.test[test_tcp__test_stream_close_idempotent]()
    suite.test[test_tcp__test_round_trip_1_byte]()
    suite.test[test_tcp__test_round_trip_1_kb]()
    suite.test[test_tcp__test_round_trip_64_kb]()
    suite.test[test_tcp__test_read_returns_zero_on_eof]()
    suite.test[test_tcp__test_bidirectional_ping_pong]()
    suite.test[test_tcp__test_sequential_connections]()
    suite.test[test_tcp__test_tcp_nodelay_toggle]()
    suite.test[test_tcp__test_keepalive_toggle]()
    suite.test[test_tcp__test_recv_timeout_causes_timeout_error]()
    suite.test[test_tcp__test_connect_timeout_blackhole]()
    suite.test[test_tcp__test_reuseaddr_allows_rebind]()
    suite.test[test_tcp__test_v6_listener_bind]()
    suite.test[test_tcp__test_v6_connect_loopback]()
    suite.test[test_tcp__test_v6_peer_addr]()
    suite^.run()
