"""GENERATED by tests/tools/gen_test_aggregates.py -- do not edit.

Aggregates the 29 test files of ``tests/quic/`` into one compiled
binary so the 29 separate compiler invocations become one. Run it with
``mojo -I . -I tests/quic`` (see tests/tools/run_test_aggregates.sh).

Regenerate with ``python3 tests/tools/gen_test_aggregates.py``; CI fails if this
file is out of date with the tree.
"""

from std.testing import TestSuite
from test_aead_ffi import (
    test_build_nonce_zero_pn as test_aead_ffi__test_build_nonce_zero_pn,
)
from test_aead_ffi import (
    test_build_nonce_xor_low_bytes as test_aead_ffi__test_build_nonce_xor_low_bytes,
)
from test_aead_ffi import (
    test_aes_128_gcm_round_trip as test_aead_ffi__test_aes_128_gcm_round_trip,
)
from test_aead_ffi import (
    test_aes_256_gcm_round_trip as test_aead_ffi__test_aes_256_gcm_round_trip,
)
from test_aead_ffi import (
    test_chacha20_poly1305_round_trip as test_aead_ffi__test_chacha20_poly1305_round_trip,
)
from test_aead_ffi import (
    test_open_rejects_tampered_tag as test_aead_ffi__test_open_rejects_tampered_tag,
)
from test_aead_ffi import (
    test_open_rejects_tampered_aad as test_aead_ffi__test_open_rejects_tampered_aad,
)
from test_aead_ffi import (
    test_open_rejects_wrong_packet_number as test_aead_ffi__test_open_rejects_wrong_packet_number,
)
from test_aead_ffi import (
    test_empty_plaintext_round_trip as test_aead_ffi__test_empty_plaintext_round_trip,
)
from test_aead_ffi import (
    test_empty_aad_round_trip as test_aead_ffi__test_empty_aad_round_trip,
)
from test_crypto import (
    test_initial_salt_matches_rfc9001 as test_crypto__test_initial_salt_matches_rfc9001,
)
from test_crypto import (
    test_hkdf_extract_matches_rfc9001_a1 as test_crypto__test_hkdf_extract_matches_rfc9001_a1,
)
from test_crypto import (
    test_client_initial_secret_matches_rfc9001_a1 as test_crypto__test_client_initial_secret_matches_rfc9001_a1,
)
from test_crypto import (
    test_server_initial_secret_matches_rfc9001_a1 as test_crypto__test_server_initial_secret_matches_rfc9001_a1,
)
from test_crypto import (
    test_derive_initial_secrets_bundles_both_directions as test_crypto__test_derive_initial_secrets_bundles_both_directions,
)
from test_crypto import (
    test_hkdf_expand_length_zero as test_crypto__test_hkdf_expand_length_zero,
)
from test_crypto import (
    test_hkdf_expand_truncates_to_length as test_crypto__test_hkdf_expand_truncates_to_length,
)
from test_crypto import (
    test_stub_backend_reports_aead_choice as test_crypto__test_stub_backend_reports_aead_choice,
)
from test_crypto import (
    test_stub_backend_raises_on_encrypt as test_crypto__test_stub_backend_raises_on_encrypt,
)
from test_crypto import (
    test_stub_backend_raises_on_decrypt as test_crypto__test_stub_backend_raises_on_decrypt,
)
from test_crypto import (
    test_stub_backend_raises_on_header_protection as test_crypto__test_stub_backend_raises_on_header_protection,
)
from test_frame import (
    test_padding_single_byte as test_frame__test_padding_single_byte,
)
from test_frame import test_ping_round_trip as test_frame__test_ping_round_trip
from test_frame import test_ack_round_trip as test_frame__test_ack_round_trip
from test_frame import (
    test_ack_ecn_round_trip as test_frame__test_ack_ecn_round_trip,
)
from test_frame import (
    test_reset_stream_round_trip as test_frame__test_reset_stream_round_trip,
)
from test_frame import (
    test_stop_sending_round_trip as test_frame__test_stop_sending_round_trip,
)
from test_frame import (
    test_crypto_round_trip as test_frame__test_crypto_round_trip,
)
from test_frame import (
    test_new_token_round_trip as test_frame__test_new_token_round_trip,
)
from test_frame import (
    test_new_token_empty_rejected as test_frame__test_new_token_empty_rejected,
)
from test_frame import (
    test_stream_round_trip_with_offset_and_fin as test_frame__test_stream_round_trip_with_offset_and_fin,
)
from test_frame import (
    test_stream_round_trip_no_offset_no_fin as test_frame__test_stream_round_trip_no_offset_no_fin,
)
from test_frame import (
    test_max_data_round_trip as test_frame__test_max_data_round_trip,
)
from test_frame import (
    test_max_stream_data_round_trip as test_frame__test_max_stream_data_round_trip,
)
from test_frame import (
    test_max_streams_bidi_and_uni as test_frame__test_max_streams_bidi_and_uni,
)
from test_frame import (
    test_data_blocked_round_trip as test_frame__test_data_blocked_round_trip,
)
from test_frame import (
    test_stream_data_blocked_round_trip as test_frame__test_stream_data_blocked_round_trip,
)
from test_frame import (
    test_streams_blocked_bidi_and_uni as test_frame__test_streams_blocked_bidi_and_uni,
)
from test_frame import (
    test_new_connection_id_round_trip as test_frame__test_new_connection_id_round_trip,
)
from test_frame import (
    test_retire_connection_id_round_trip as test_frame__test_retire_connection_id_round_trip,
)
from test_frame import (
    test_path_challenge_round_trip as test_frame__test_path_challenge_round_trip,
)
from test_frame import (
    test_path_response_round_trip as test_frame__test_path_response_round_trip,
)
from test_frame import (
    test_connection_close_transport_round_trip as test_frame__test_connection_close_transport_round_trip,
)
from test_frame import (
    test_connection_close_application_round_trip as test_frame__test_connection_close_application_round_trip,
)
from test_frame import (
    test_handshake_done_round_trip as test_frame__test_handshake_done_round_trip,
)
from test_frame import (
    test_unknown_frame_type_rejected as test_frame__test_unknown_frame_type_rejected,
)
from test_frame import (
    test_truncated_crypto_rejected as test_frame__test_truncated_crypto_rejected,
)
from test_frame import (
    test_datagram_with_length_round_trip as test_frame__test_datagram_with_length_round_trip,
)
from test_frame import (
    test_datagram_no_length_runs_to_end as test_frame__test_datagram_no_length_runs_to_end,
)
from test_hp_mask_ffi import (
    test_rfc9001_a2_aes128_client_initial as test_hp_mask_ffi__test_rfc9001_a2_aes128_client_initial,
)
from test_hp_mask_ffi import (
    test_rfc9001_a5_chacha20_short_header as test_hp_mask_ffi__test_rfc9001_a5_chacha20_short_header,
)
from test_hp_mask_ffi import (
    test_aes256_deterministic as test_hp_mask_ffi__test_aes256_deterministic,
)
from test_hp_mask_ffi import (
    test_aes256_sample_change_flips_mask as test_hp_mask_ffi__test_aes256_sample_change_flips_mask,
)
from test_hp_mask_ffi import (
    test_chacha20_sample_change_flips_mask as test_hp_mask_ffi__test_chacha20_sample_change_flips_mask,
)
from test_loss_recovery import (
    test_ack_retires_and_resets_backoff as test_loss_recovery__test_ack_retires_and_resets_backoff,
)
from test_loss_recovery import (
    test_ack_gap_leaves_lost_packet_outstanding as test_loss_recovery__test_ack_gap_leaves_lost_packet_outstanding,
)
from test_loss_recovery import (
    test_pto_deadline_and_backoff as test_loss_recovery__test_pto_deadline_and_backoff,
)
from test_loss_recovery import (
    test_fire_pto_empty_is_noop as test_loss_recovery__test_fire_pto_empty_is_noop,
)
from test_loss_recovery import (
    test_expand_ack_single_range as test_loss_recovery__test_expand_ack_single_range,
)
from test_loss_recovery import (
    test_expand_ack_with_gap as test_loss_recovery__test_expand_ack_with_gap,
)
from test_loss_recovery import (
    test_rtt_sample_drives_pto as test_loss_recovery__test_rtt_sample_drives_pto,
)
from test_loss_recovery import (
    test_ack_based_loss_detection_packet_threshold as test_loss_recovery__test_ack_based_loss_detection_packet_threshold,
)
from test_loss_recovery import (
    test_cc_reduces_window_on_loss as test_loss_recovery__test_cc_reduces_window_on_loss,
)
from test_openssl_quic_crypto import (
    test_derive_packet_keys_rfc9001_a5_chacha20 as test_openssl_quic_crypto__test_derive_packet_keys_rfc9001_a5_chacha20,
)
from test_openssl_quic_crypto import (
    test_round_trip_aes_128_gcm as test_openssl_quic_crypto__test_round_trip_aes_128_gcm,
)
from test_openssl_quic_crypto import (
    test_round_trip_aes_256_gcm as test_openssl_quic_crypto__test_round_trip_aes_256_gcm,
)
from test_openssl_quic_crypto import (
    test_round_trip_chacha20_poly1305 as test_openssl_quic_crypto__test_round_trip_chacha20_poly1305,
)
from test_openssl_quic_crypto import (
    test_decrypt_rejects_tampered_ciphertext as test_openssl_quic_crypto__test_decrypt_rejects_tampered_ciphertext,
)
from test_openssl_quic_crypto import (
    test_decrypt_short_ciphertext_raises as test_openssl_quic_crypto__test_decrypt_short_ciphertext_raises,
)
from test_openssl_quic_crypto import (
    test_hp_mask_returns_5_bytes as test_openssl_quic_crypto__test_hp_mask_returns_5_bytes,
)
from test_openssl_quic_crypto import (
    test_hp_mask_rejects_wrong_sample_length as test_openssl_quic_crypto__test_hp_mask_rejects_wrong_sample_length,
)
from test_openssl_quic_crypto import (
    test_from_secret_factory as test_openssl_quic_crypto__test_from_secret_factory,
)
from test_packet import (
    test_long_header_initial_round_trip as test_packet__test_long_header_initial_round_trip,
)
from test_packet import (
    test_long_header_all_packet_types as test_packet__test_long_header_all_packet_types,
)
from test_packet import (
    test_long_header_rejects_missing_long_bit as test_packet__test_long_header_rejects_missing_long_bit,
)
from test_packet import (
    test_long_header_rejects_missing_fixed_bit as test_packet__test_long_header_rejects_missing_fixed_bit,
)
from test_packet import (
    test_long_header_rejects_oversized_cid as test_packet__test_long_header_rejects_oversized_cid,
)
from test_packet import (
    test_version_negotiation_detection as test_packet__test_version_negotiation_detection,
)
from test_packet import (
    test_initial_extras_round_trip as test_packet__test_initial_extras_round_trip,
)
from test_packet import (
    test_short_header_round_trip as test_packet__test_short_header_round_trip,
)
from test_packet import (
    test_short_header_rejects_long_bit as test_packet__test_short_header_rejects_long_bit,
)
from test_packet import (
    test_short_header_rejects_bad_dcid_length as test_packet__test_short_header_rejects_bad_dcid_length,
)
from test_packet import (
    test_encoder_rejects_oversized_cid as test_packet__test_encoder_rejects_oversized_cid,
)
from test_quic_0rtt_replay import (
    test_disabled_by_default_rejects_all as test_quic_0rtt_replay__test_disabled_by_default_rejects_all,
)
from test_quic_0rtt_replay import (
    test_admits_fresh_in_order as test_quic_0rtt_replay__test_admits_fresh_in_order,
)
from test_quic_0rtt_replay import (
    test_rejects_duplicate_packet_number as test_quic_0rtt_replay__test_rejects_duplicate_packet_number,
)
from test_quic_0rtt_replay import (
    test_admits_reordered_within_window as test_quic_0rtt_replay__test_admits_reordered_within_window,
)
from test_quic_0rtt_replay import (
    test_rejects_stale_outside_window as test_quic_0rtt_replay__test_rejects_stale_outside_window,
)
from test_quic_0rtt_replay import (
    test_byte_budget_enforced as test_quic_0rtt_replay__test_byte_budget_enforced,
)
from test_quic_0rtt_replay import (
    test_early_data_packet_len_matches_total as test_quic_0rtt_replay__test_early_data_packet_len_matches_total,
)
from test_quic_0rtt_replay import (
    test_strike_fresh_then_replay_refused as test_quic_0rtt_replay__test_strike_fresh_then_replay_refused,
)
from test_quic_0rtt_replay import (
    test_strike_distinct_keys_independent as test_quic_0rtt_replay__test_strike_distinct_keys_independent,
)
from test_quic_0rtt_replay import (
    test_strike_expired_window_allows_again as test_quic_0rtt_replay__test_strike_expired_window_allows_again,
)
from test_quic_0rtt_replay import (
    test_strike_capacity_fail_closed as test_quic_0rtt_replay__test_strike_capacity_fail_closed,
)
from test_quic_cc import test_choice_tag as test_quic_cc__test_choice_tag
from test_quic_cc import (
    test_reno_initial_window as test_quic_cc__test_reno_initial_window,
)
from test_quic_cc import (
    test_reno_slow_start_growth as test_quic_cc__test_reno_slow_start_growth,
)
from test_quic_cc import (
    test_reno_loss_halves_window as test_quic_cc__test_reno_loss_halves_window,
)
from test_quic_cc import (
    test_reno_minimum_window_floor as test_quic_cc__test_reno_minimum_window_floor,
)
from test_quic_cc import (
    test_cubic_initial_and_loss as test_quic_cc__test_cubic_initial_and_loss,
)
from test_quic_cc import (
    test_cubic_slow_start_grows as test_quic_cc__test_cubic_slow_start_grows,
)
from test_quic_cc import (
    test_cubic_hystart_exits_on_rtt_rise as test_quic_cc__test_cubic_hystart_exits_on_rtt_rise,
)
from test_quic_cc import (
    test_cubic_minimum_window_floor as test_quic_cc__test_cubic_minimum_window_floor,
)
from test_quic_client import (
    test_client_handshake_completes as test_quic_client__test_client_handshake_completes,
)
from test_quic_client import (
    test_client_send_stream_after_handshake as test_quic_client__test_client_send_stream_after_handshake,
)
from test_quic_client import (
    test_client_handshake_through_retry as test_quic_client__test_client_handshake_through_retry,
)
from test_quic_client import (
    test_stream_control_frames_are_retransmitted_on_pto as test_quic_client__test_stream_control_frames_are_retransmitted_on_pto,
)
from test_quic_client import (
    test_cancel_stream_forbids_further_stream_frames as test_quic_client__test_cancel_stream_forbids_further_stream_frames,
)
from test_quic_handle_packet import (
    test_decode_packet_number_rfc_a3 as test_quic_handle_packet__test_decode_packet_number_rfc_a3,
)
from test_quic_handle_packet import (
    test_decode_packet_number_no_wrap as test_quic_handle_packet__test_decode_packet_number_no_wrap,
)
from test_quic_handle_packet import (
    test_protect_unprotect_round_trip as test_quic_handle_packet__test_protect_unprotect_round_trip,
)
from test_quic_handle_packet import (
    test_handle_packet_drives_state_machine_through_stream_frame as test_quic_handle_packet__test_handle_packet_drives_state_machine_through_stream_frame,
)
from test_quic_handle_packet import (
    test_listener_dispatch_routes_into_handle_packet as test_quic_handle_packet__test_listener_dispatch_routes_into_handle_packet,
)
from test_quic_handle_packet import (
    test_dispatch_garbled_initial_drops_silently as test_quic_handle_packet__test_dispatch_garbled_initial_drops_silently,
)
from test_quic_handle_packet import (
    test_handle_packet_drops_short_header_silently as test_quic_handle_packet__test_handle_packet_drops_short_header_silently,
)
from test_quic_handle_packet import (
    test_handle_packet_drops_handshake_long_silently as test_quic_handle_packet__test_handle_packet_drops_handshake_long_silently,
)
from test_quic_handshake_bridge import (
    test_events_crypto_frames_starts_empty as test_quic_handshake_bridge__test_events_crypto_frames_starts_empty,
)
from test_quic_handshake_bridge import (
    test_handle_frame_buf_surfaces_crypto_frame as test_quic_handshake_bridge__test_handle_frame_buf_surfaces_crypto_frame,
)
from test_quic_handshake_bridge import (
    test_listener_bind_empty_pem_yields_null_acceptor as test_quic_handshake_bridge__test_listener_bind_empty_pem_yields_null_acceptor,
)
from test_quic_handshake_bridge import (
    test_listener_bind_real_pem_yields_live_acceptor as test_quic_handshake_bridge__test_listener_bind_real_pem_yields_live_acceptor,
)
from test_quic_handshake_bridge import (
    test_accept_initial_materializes_real_session as test_quic_handshake_bridge__test_accept_initial_materializes_real_session,
)
from test_quic_handshake_bridge import (
    test_accept_initial_empty_pem_keeps_null_sentinel as test_quic_handshake_bridge__test_accept_initial_empty_pem_keeps_null_sentinel,
)
from test_quic_handshake_bridge import (
    test_bridge_dispatches_crypto_frame_no_crash_real_pem as test_quic_handshake_bridge__test_bridge_dispatches_crypto_frame_no_crash_real_pem,
)
from test_quic_handshake_bridge import (
    test_bridge_dispatches_crypto_frame_no_crash_empty_pem as test_quic_handshake_bridge__test_bridge_dispatches_crypto_frame_no_crash_empty_pem,
)
from test_quic_handshake_bridge import (
    test_retransmit_does_not_grow_session_slab as test_quic_handshake_bridge__test_retransmit_does_not_grow_session_slab,
)
from test_quic_handshake_bridge import (
    test_listener_teardown_no_leak as test_quic_handshake_bridge__test_listener_teardown_no_leak,
)
from test_quic_keys_install import (
    test_per_level_egress_queues_allocated_in_lockstep as test_quic_keys_install__test_per_level_egress_queues_allocated_in_lockstep,
)
from test_quic_keys_install import (
    test_synth_initial_does_not_flip_handshake_or_1rtt_keys as test_quic_keys_install__test_synth_initial_does_not_flip_handshake_or_1rtt_keys,
)
from test_quic_keys_install import (
    test_multiple_synth_initials_keep_egress_queues_in_lockstep as test_quic_keys_install__test_multiple_synth_initials_keep_egress_queues_in_lockstep,
)
from test_quic_loopback_integration import (
    test_loopback_initial_handshake_round_trip as test_quic_loopback_integration__test_loopback_initial_handshake_round_trip,
)
from test_quic_loopback_integration import (
    test_loopback_retransmit_routes_to_existing_slot as test_quic_loopback_integration__test_loopback_retransmit_routes_to_existing_slot,
)
from test_quic_loopback_integration import (
    test_loopback_idle_close_retires_cid as test_quic_loopback_integration__test_loopback_idle_close_retires_cid,
)
from test_quic_loopback_integration import (
    test_loopback_unknown_short_header_stateless_reset as test_quic_loopback_integration__test_loopback_unknown_short_header_stateless_reset,
)
from test_quic_loopback_integration import (
    test_egress_build_initial_response_decrypts_at_client as test_quic_loopback_integration__test_egress_build_initial_response_decrypts_at_client,
)
from test_quic_loopback_integration import (
    test_egress_drain_clears_queue_and_advances_counters as test_quic_loopback_integration__test_egress_drain_clears_queue_and_advances_counters,
)
from test_quic_loopback_integration import (
    test_egress_no_op_when_queue_empty as test_quic_loopback_integration__test_egress_no_op_when_queue_empty,
)
from test_quic_loopback_integration import (
    test_io_loop_tick_drives_recv_dispatch_drain as test_quic_loopback_integration__test_io_loop_tick_drives_recv_dispatch_drain,
)
from test_quic_migration import (
    test_client_migrates_to_new_path as test_quic_migration__test_client_migrates_to_new_path,
)
from test_quic_migration_probe import (
    test_idle_probe_allows_and_should_start as test_quic_migration_probe__test_idle_probe_allows_and_should_start,
)
from test_quic_migration_probe import (
    test_amplification_budget_3x as test_quic_migration_probe__test_amplification_budget_3x,
)
from test_quic_migration_probe import (
    test_note_rx_only_counts_candidate as test_quic_migration_probe__test_note_rx_only_counts_candidate,
)
from test_quic_migration_probe import (
    test_validation_lifts_cap as test_quic_migration_probe__test_validation_lifts_cap,
)
from test_quic_migration_probe import (
    test_should_start_on_candidate_change as test_quic_migration_probe__test_should_start_on_candidate_change,
)
from test_quic_migration_probe import (
    test_new_path_challenge_encoding as test_quic_migration_probe__test_new_path_challenge_encoding,
)
from test_quic_post_initial_decrypt import (
    test_decrypt_post_initial_raises_slot_out_of_range as test_quic_post_initial_decrypt__test_decrypt_post_initial_raises_slot_out_of_range,
)
from test_quic_post_initial_decrypt import (
    test_decrypt_post_initial_raises_on_truncated_handshake as test_quic_post_initial_decrypt__test_decrypt_post_initial_raises_on_truncated_handshake,
)
from test_quic_post_initial_decrypt import (
    test_handle_inbound_drops_handshake_without_sentinel as test_quic_post_initial_decrypt__test_handle_inbound_drops_handshake_without_sentinel,
)
from test_quic_post_initial_decrypt import (
    test_handle_inbound_drops_1rtt_without_sentinel as test_quic_post_initial_decrypt__test_handle_inbound_drops_1rtt_without_sentinel,
)
from test_quic_post_initial_decrypt import (
    test_ack_ranges_exclude_skipped_pn as test_quic_post_initial_decrypt__test_ack_ranges_exclude_skipped_pn,
)
from test_quic_post_initial_decrypt import (
    test_ack_ranges_contiguous_single_range as test_quic_post_initial_decrypt__test_ack_ranges_contiguous_single_range,
)
from test_quic_post_initial_decrypt import (
    test_ack_ranges_duplicate_pn_is_idempotent as test_quic_post_initial_decrypt__test_ack_ranges_duplicate_pn_is_idempotent,
)
from test_quic_post_initial_egress import (
    test_handshake_response_empty_when_slot_out_of_range as test_quic_post_initial_egress__test_handshake_response_empty_when_slot_out_of_range,
)
from test_quic_post_initial_egress import (
    test_1rtt_response_empty_when_slot_out_of_range as test_quic_post_initial_egress__test_1rtt_response_empty_when_slot_out_of_range,
)
from test_quic_post_initial_egress import (
    test_handshake_response_empty_without_readiness_sentinel as test_quic_post_initial_egress__test_handshake_response_empty_without_readiness_sentinel,
)
from test_quic_post_initial_egress import (
    test_1rtt_response_empty_without_readiness_sentinel as test_quic_post_initial_egress__test_1rtt_response_empty_without_readiness_sentinel,
)
from test_quic_post_initial_egress import (
    test_handshake_response_empty_when_queue_empty as test_quic_post_initial_egress__test_handshake_response_empty_when_queue_empty,
)
from test_quic_post_initial_egress import (
    test_drain_and_send_noop_on_closed_slot as test_quic_post_initial_egress__test_drain_and_send_noop_on_closed_slot,
)
from test_quic_reactor import (
    test_bind_opens_real_udp_socket as test_quic_reactor__test_bind_opens_real_udp_socket,
)
from test_quic_reactor import (
    test_bind_honors_explicit_port_zero as test_quic_reactor__test_bind_honors_explicit_port_zero,
)
from test_quic_reactor import (
    test_tick_returns_false_on_timeout as test_quic_reactor__test_tick_returns_false_on_timeout,
)
from test_quic_reactor import (
    test_shutdown_makes_run_exit as test_quic_reactor__test_shutdown_makes_run_exit,
)
from test_quic_reactor import (
    test_dispatch_initial_creates_new_slot as test_quic_reactor__test_dispatch_initial_creates_new_slot,
)
from test_quic_reactor import (
    test_dispatch_initial_retransmit_routes_to_same_slot as test_quic_reactor__test_dispatch_initial_retransmit_routes_to_same_slot,
)
from test_quic_reactor import (
    test_dispatch_handshake_with_unknown_dcid_drops as test_quic_reactor__test_dispatch_handshake_with_unknown_dcid_drops,
)
from test_quic_reactor import (
    test_dispatch_short_unknown_dcid_drops as test_quic_reactor__test_dispatch_short_unknown_dcid_drops,
)
from test_quic_reactor import (
    test_dispatch_short_known_dcid_routes as test_quic_reactor__test_dispatch_short_known_dcid_routes,
)
from test_quic_reactor import (
    test_dispatch_empty_datagram_drops as test_quic_reactor__test_dispatch_empty_datagram_drops,
)
from test_quic_reactor import (
    test_live_loopback_tick_routes_initial as test_quic_reactor__test_live_loopback_tick_routes_initial,
)
from test_quic_reactor import (
    test_cid_to_hex_round_trip as test_quic_reactor__test_cid_to_hex_round_trip,
)
from test_quic_resumption import (
    test_resumption_installs_early_keys as test_quic_resumption__test_resumption_installs_early_keys,
)
from test_quic_retry_server import (
    test_quic_retry_server as test_quic_retry_server__test_quic_retry_server,
)
from test_quic_server_loss_recovery import (
    test_loss_slab_starts_empty_and_parallels_connections as test_quic_server_loss_recovery__test_loss_slab_starts_empty_and_parallels_connections,
)
from test_quic_server_loss_recovery import (
    test_max_pto_count_has_a_bounded_default as test_quic_server_loss_recovery__test_max_pto_count_has_a_bounded_default,
)
from test_quic_server_loss_recovery import (
    test_slab_tracks_sent_packets_and_retires_them_on_ack as test_quic_server_loss_recovery__test_slab_tracks_sent_packets_and_retires_them_on_ack,
)
from test_quic_server_loss_recovery import (
    test_pto_fires_frames_for_retransmission as test_quic_server_loss_recovery__test_pto_fires_frames_for_retransmission,
)
from test_quic_server_loss_recovery import (
    test_ack_of_everything_disarms_the_timer as test_quic_server_loss_recovery__test_ack_of_everything_disarms_the_timer,
)
from test_quic_timers import (
    test_token_round_trip as test_quic_timers__test_token_round_trip,
)
from test_quic_timers import (
    test_encode_rejects_invalid_kind as test_quic_timers__test_encode_rejects_invalid_kind,
)
from test_quic_timers import (
    test_encode_rejects_invalid_slot as test_quic_timers__test_encode_rejects_invalid_slot,
)
from test_quic_timers import (
    test_decode_rejects_unknown_kind as test_quic_timers__test_decode_rejects_unknown_kind,
)
from test_quic_timers import (
    test_timer_kind_name as test_quic_timers__test_timer_kind_name,
)
from test_quic_timers import (
    test_schedule_idle_cancels_previous as test_quic_timers__test_schedule_idle_cancels_previous,
)
from test_quic_timers import (
    test_advance_idle_closes_connection as test_quic_timers__test_advance_idle_closes_connection,
)
from test_quic_timers import (
    test_dispatch_arms_idle_timer_on_accept as test_quic_timers__test_dispatch_arms_idle_timer_on_accept,
)
from test_quic_timers import (
    test_on_idle_callback_is_idempotent_to_double_fire as test_quic_timers__test_on_idle_callback_is_idempotent_to_double_fire,
)
from test_retry import (
    test_retry_integrity_tag_rfc9001_a4 as test_retry__test_retry_integrity_tag_rfc9001_a4,
)
from test_retry import (
    test_verify_retry_integrity_round_trip as test_retry__test_verify_retry_integrity_round_trip,
)
from test_retry import (
    test_retry_token_round_trip as test_retry__test_retry_token_round_trip,
)
from test_retry import (
    test_retry_token_address_mismatch_rejected as test_retry__test_retry_token_address_mismatch_rejected,
)
from test_retry import (
    test_retry_token_expired_rejected as test_retry__test_retry_token_expired_rejected,
)
from test_retry import (
    test_retry_token_tamper_rejected as test_retry__test_retry_token_tamper_rejected,
)
from test_retry import (
    test_retry_token_wrong_key_rejected as test_retry__test_retry_token_wrong_key_rejected,
)
from test_retry import (
    test_version_negotiation_shape as test_retry__test_version_negotiation_shape,
)
from test_rfc9001_appendix_a import (
    test_a1_initial_secrets as test_rfc9001_appendix_a__test_a1_initial_secrets,
)
from test_rfc9001_appendix_a import (
    test_a1_client_packet_keys as test_rfc9001_appendix_a__test_a1_client_packet_keys,
)
from test_rfc9001_appendix_a import (
    test_a1_server_packet_keys as test_rfc9001_appendix_a__test_a1_server_packet_keys,
)
from test_rfc9001_appendix_a import (
    test_a2_client_initial_aead_round_trip as test_rfc9001_appendix_a__test_a2_client_initial_aead_round_trip,
)
from test_rfc9001_appendix_a import (
    test_a3_server_initial_aead_round_trip as test_rfc9001_appendix_a__test_a3_server_initial_aead_round_trip,
)
from test_rfc9001_appendix_a import (
    test_a2_client_initial_full_ciphertext_bytes as test_rfc9001_appendix_a__test_a2_client_initial_full_ciphertext_bytes,
)
from test_rfc9001_appendix_a import (
    test_handshake_round_trip_short_payload as test_rfc9001_appendix_a__test_handshake_round_trip_short_payload,
)
from test_rfc9001_appendix_a import (
    test_handshake_round_trip_aes_256_gcm as test_rfc9001_appendix_a__test_handshake_round_trip_aes_256_gcm,
)
from test_rfc9001_appendix_a import (
    test_1rtt_round_trip_synthetic as test_rfc9001_appendix_a__test_1rtt_round_trip_synthetic,
)
from test_rfc9001_appendix_a import (
    test_1rtt_round_trip_empty_dcid_pn_length_3 as test_rfc9001_appendix_a__test_1rtt_round_trip_empty_dcid_pn_length_3,
)
from test_rfc9001_appendix_a import (
    test_a5_chacha20_short_header_round_trip as test_rfc9001_appendix_a__test_a5_chacha20_short_header_round_trip,
)
from test_rfc9001_appendix_a import (
    test_handshake_rejects_short_header as test_rfc9001_appendix_a__test_handshake_rejects_short_header,
)
from test_rfc9001_appendix_a import (
    test_1rtt_rejects_long_header as test_rfc9001_appendix_a__test_1rtt_rejects_long_header,
)
from test_server_scaffold import (
    test_config_defaults as test_server_scaffold__test_config_defaults,
)
from test_server_scaffold import (
    test_config_carries_overrides as test_server_scaffold__test_config_carries_overrides,
)
from test_server_scaffold import (
    test_quic_connection_starts_alive_in_handshake as test_server_scaffold__test_quic_connection_starts_alive_in_handshake,
)
from test_server_scaffold import (
    test_quic_connection_records_cids as test_server_scaffold__test_quic_connection_records_cids,
)
from test_server_scaffold import (
    test_cid_table_register_lookup_retire as test_server_scaffold__test_cid_table_register_lookup_retire,
)
from test_server_scaffold import (
    test_cid_table_lookup_missing_returns_minus_one as test_server_scaffold__test_cid_table_lookup_missing_returns_minus_one,
)
from test_server_scaffold import (
    test_cid_table_register_overwrites as test_server_scaffold__test_cid_table_register_overwrites,
)
from test_state import (
    test_initial_connection_state as test_state__test_initial_connection_state,
)
from test_state import (
    test_handshake_done_advances_state as test_state__test_handshake_done_advances_state,
)
from test_state import (
    test_mark_handshake_complete_explicit_hook as test_state__test_mark_handshake_complete_explicit_hook,
)
from test_state import (
    test_stream_frame_opens_stream as test_state__test_stream_frame_opens_stream,
)
from test_state import (
    test_stream_frame_with_fin_finishes_stream as test_state__test_stream_frame_with_fin_finishes_stream,
)
from test_state import (
    test_ack_eliciting_flag_flips_pending as test_state__test_ack_eliciting_flag_flips_pending,
)
from test_state import (
    test_padding_does_not_flip_ack_pending as test_state__test_padding_does_not_flip_ack_pending,
)
from test_state import (
    test_max_data_advances_send_limit as test_state__test_max_data_advances_send_limit,
)
from test_state import (
    test_connection_close_frame_drains as test_state__test_connection_close_frame_drains,
)
from test_state import (
    test_connection_close_explicit_helper as test_state__test_connection_close_explicit_helper,
)
from test_state import (
    test_idle_timeout_detection as test_state__test_idle_timeout_detection,
)
from test_state import (
    test_flow_control_violation_raises as test_state__test_flow_control_violation_raises,
)
from test_state import (
    test_ack_frame_advances_largest_acked as test_state__test_ack_frame_advances_largest_acked,
)
from test_state import (
    test_new_connection_id_stores_peer_cid as test_state__test_new_connection_id_stores_peer_cid,
)
from test_state import (
    test_new_connection_id_retire_prior_to_queues_retire as test_state__test_new_connection_id_retire_prior_to_queues_retire,
)
from test_state import (
    test_new_connection_id_bad_length_raises as test_state__test_new_connection_id_bad_length_raises,
)
from test_state import (
    test_retire_connection_id_acks as test_state__test_retire_connection_id_acks,
)
from test_state import (
    test_path_challenge_queues_response as test_state__test_path_challenge_queues_response,
)
from test_state import (
    test_path_response_validates_matching_challenge as test_state__test_path_response_validates_matching_challenge,
)
from test_state import (
    test_path_response_mismatch_ignored as test_state__test_path_response_mismatch_ignored,
)
from test_transport_params import (
    test_round_trip_full_set as test_transport_params__test_round_trip_full_set,
)
from test_transport_params import (
    test_empty_params_roundtrip as test_transport_params__test_empty_params_roundtrip,
)
from test_transport_params import (
    test_disable_active_migration_zero_length as test_transport_params__test_disable_active_migration_zero_length,
)
from test_transport_params import (
    test_stateless_reset_token_must_be_16_bytes as test_transport_params__test_stateless_reset_token_must_be_16_bytes,
)
from test_transport_params import (
    test_max_udp_payload_size_below_1200_rejected as test_transport_params__test_max_udp_payload_size_below_1200_rejected,
)
from test_transport_params import (
    test_ack_delay_exponent_above_20_rejected as test_transport_params__test_ack_delay_exponent_above_20_rejected,
)
from test_transport_params import (
    test_active_connection_id_limit_below_2_rejected as test_transport_params__test_active_connection_id_limit_below_2_rejected,
)
from test_transport_params import (
    test_duplicate_id_rejected as test_transport_params__test_duplicate_id_rejected,
)
from test_transport_params import (
    test_unknown_id_silently_dropped as test_transport_params__test_unknown_id_silently_dropped,
)
from test_transport_params import (
    test_truncated_value_rejected as test_transport_params__test_truncated_value_rejected,
)
from test_transport_params import (
    test_max_datagram_frame_size_roundtrip as test_transport_params__test_max_datagram_frame_size_roundtrip,
)
from test_transport_params import (
    test_derive_peer_send_limits_defaults as test_transport_params__test_derive_peer_send_limits_defaults,
)
from test_transport_params import (
    test_derive_peer_send_limits_set as test_transport_params__test_derive_peer_send_limits_set,
)
from test_varint import (
    test_rfc9000_appendix_a_1byte_form as test_varint__test_rfc9000_appendix_a_1byte_form,
)
from test_varint import (
    test_rfc9000_appendix_a_2byte_form as test_varint__test_rfc9000_appendix_a_2byte_form,
)
from test_varint import (
    test_rfc9000_appendix_a_4byte_form as test_varint__test_rfc9000_appendix_a_4byte_form,
)
from test_varint import (
    test_rfc9000_appendix_a_8byte_form as test_varint__test_rfc9000_appendix_a_8byte_form,
)
from test_varint import (
    test_boundary_values as test_varint__test_boundary_values,
)
from test_varint import (
    test_zero_round_trips as test_varint__test_zero_round_trips,
)
from test_varint import (
    test_encoder_rejects_overflow as test_varint__test_encoder_rejects_overflow,
)
from test_varint import (
    test_decoder_rejects_empty_buffer as test_varint__test_decoder_rejects_empty_buffer,
)
from test_varint import (
    test_decoder_rejects_truncated_input as test_varint__test_decoder_rejects_truncated_input,
)
from test_varint import (
    test_round_trip_many_values as test_varint__test_round_trip_many_values,
)
from test_varint import (
    test_decoder_consumes_only_first_varint as test_varint__test_decoder_consumes_only_first_varint,
)


def main() raises:
    var suite = TestSuite()
    # tests/quic/test_aead_ffi.mojo
    suite.test[test_aead_ffi__test_build_nonce_zero_pn]()
    suite.test[test_aead_ffi__test_build_nonce_xor_low_bytes]()
    suite.test[test_aead_ffi__test_aes_128_gcm_round_trip]()
    suite.test[test_aead_ffi__test_aes_256_gcm_round_trip]()
    suite.test[test_aead_ffi__test_chacha20_poly1305_round_trip]()
    suite.test[test_aead_ffi__test_open_rejects_tampered_tag]()
    suite.test[test_aead_ffi__test_open_rejects_tampered_aad]()
    suite.test[test_aead_ffi__test_open_rejects_wrong_packet_number]()
    suite.test[test_aead_ffi__test_empty_plaintext_round_trip]()
    suite.test[test_aead_ffi__test_empty_aad_round_trip]()
    # tests/quic/test_crypto.mojo
    suite.test[test_crypto__test_initial_salt_matches_rfc9001]()
    suite.test[test_crypto__test_hkdf_extract_matches_rfc9001_a1]()
    suite.test[test_crypto__test_client_initial_secret_matches_rfc9001_a1]()
    suite.test[test_crypto__test_server_initial_secret_matches_rfc9001_a1]()
    suite.test[
        test_crypto__test_derive_initial_secrets_bundles_both_directions
    ]()
    suite.test[test_crypto__test_hkdf_expand_length_zero]()
    suite.test[test_crypto__test_hkdf_expand_truncates_to_length]()
    suite.test[test_crypto__test_stub_backend_reports_aead_choice]()
    suite.test[test_crypto__test_stub_backend_raises_on_encrypt]()
    suite.test[test_crypto__test_stub_backend_raises_on_decrypt]()
    suite.test[test_crypto__test_stub_backend_raises_on_header_protection]()
    # tests/quic/test_frame.mojo
    suite.test[test_frame__test_padding_single_byte]()
    suite.test[test_frame__test_ping_round_trip]()
    suite.test[test_frame__test_ack_round_trip]()
    suite.test[test_frame__test_ack_ecn_round_trip]()
    suite.test[test_frame__test_reset_stream_round_trip]()
    suite.test[test_frame__test_stop_sending_round_trip]()
    suite.test[test_frame__test_crypto_round_trip]()
    suite.test[test_frame__test_new_token_round_trip]()
    suite.test[test_frame__test_new_token_empty_rejected]()
    suite.test[test_frame__test_stream_round_trip_with_offset_and_fin]()
    suite.test[test_frame__test_stream_round_trip_no_offset_no_fin]()
    suite.test[test_frame__test_max_data_round_trip]()
    suite.test[test_frame__test_max_stream_data_round_trip]()
    suite.test[test_frame__test_max_streams_bidi_and_uni]()
    suite.test[test_frame__test_data_blocked_round_trip]()
    suite.test[test_frame__test_stream_data_blocked_round_trip]()
    suite.test[test_frame__test_streams_blocked_bidi_and_uni]()
    suite.test[test_frame__test_new_connection_id_round_trip]()
    suite.test[test_frame__test_retire_connection_id_round_trip]()
    suite.test[test_frame__test_path_challenge_round_trip]()
    suite.test[test_frame__test_path_response_round_trip]()
    suite.test[test_frame__test_connection_close_transport_round_trip]()
    suite.test[test_frame__test_connection_close_application_round_trip]()
    suite.test[test_frame__test_handshake_done_round_trip]()
    suite.test[test_frame__test_unknown_frame_type_rejected]()
    suite.test[test_frame__test_truncated_crypto_rejected]()
    suite.test[test_frame__test_datagram_with_length_round_trip]()
    suite.test[test_frame__test_datagram_no_length_runs_to_end]()
    # tests/quic/test_hp_mask_ffi.mojo
    suite.test[test_hp_mask_ffi__test_rfc9001_a2_aes128_client_initial]()
    suite.test[test_hp_mask_ffi__test_rfc9001_a5_chacha20_short_header]()
    suite.test[test_hp_mask_ffi__test_aes256_deterministic]()
    suite.test[test_hp_mask_ffi__test_aes256_sample_change_flips_mask]()
    suite.test[test_hp_mask_ffi__test_chacha20_sample_change_flips_mask]()
    # tests/quic/test_loss_recovery.mojo
    suite.test[test_loss_recovery__test_ack_retires_and_resets_backoff]()
    suite.test[
        test_loss_recovery__test_ack_gap_leaves_lost_packet_outstanding
    ]()
    suite.test[test_loss_recovery__test_pto_deadline_and_backoff]()
    suite.test[test_loss_recovery__test_fire_pto_empty_is_noop]()
    suite.test[test_loss_recovery__test_expand_ack_single_range]()
    suite.test[test_loss_recovery__test_expand_ack_with_gap]()
    suite.test[test_loss_recovery__test_rtt_sample_drives_pto]()
    suite.test[
        test_loss_recovery__test_ack_based_loss_detection_packet_threshold
    ]()
    suite.test[test_loss_recovery__test_cc_reduces_window_on_loss]()
    # tests/quic/test_openssl_quic_crypto.mojo
    suite.test[
        test_openssl_quic_crypto__test_derive_packet_keys_rfc9001_a5_chacha20
    ]()
    suite.test[test_openssl_quic_crypto__test_round_trip_aes_128_gcm]()
    suite.test[test_openssl_quic_crypto__test_round_trip_aes_256_gcm]()
    suite.test[test_openssl_quic_crypto__test_round_trip_chacha20_poly1305]()
    suite.test[
        test_openssl_quic_crypto__test_decrypt_rejects_tampered_ciphertext
    ]()
    suite.test[test_openssl_quic_crypto__test_decrypt_short_ciphertext_raises]()
    suite.test[test_openssl_quic_crypto__test_hp_mask_returns_5_bytes]()
    suite.test[
        test_openssl_quic_crypto__test_hp_mask_rejects_wrong_sample_length
    ]()
    suite.test[test_openssl_quic_crypto__test_from_secret_factory]()
    # tests/quic/test_packet.mojo
    suite.test[test_packet__test_long_header_initial_round_trip]()
    suite.test[test_packet__test_long_header_all_packet_types]()
    suite.test[test_packet__test_long_header_rejects_missing_long_bit]()
    suite.test[test_packet__test_long_header_rejects_missing_fixed_bit]()
    suite.test[test_packet__test_long_header_rejects_oversized_cid]()
    suite.test[test_packet__test_version_negotiation_detection]()
    suite.test[test_packet__test_initial_extras_round_trip]()
    suite.test[test_packet__test_short_header_round_trip]()
    suite.test[test_packet__test_short_header_rejects_long_bit]()
    suite.test[test_packet__test_short_header_rejects_bad_dcid_length]()
    suite.test[test_packet__test_encoder_rejects_oversized_cid]()
    # tests/quic/test_quic_0rtt_replay.mojo
    suite.test[test_quic_0rtt_replay__test_disabled_by_default_rejects_all]()
    suite.test[test_quic_0rtt_replay__test_admits_fresh_in_order]()
    suite.test[test_quic_0rtt_replay__test_rejects_duplicate_packet_number]()
    suite.test[test_quic_0rtt_replay__test_admits_reordered_within_window]()
    suite.test[test_quic_0rtt_replay__test_rejects_stale_outside_window]()
    suite.test[test_quic_0rtt_replay__test_byte_budget_enforced]()
    suite.test[
        test_quic_0rtt_replay__test_early_data_packet_len_matches_total
    ]()
    suite.test[test_quic_0rtt_replay__test_strike_fresh_then_replay_refused]()
    suite.test[test_quic_0rtt_replay__test_strike_distinct_keys_independent]()
    suite.test[test_quic_0rtt_replay__test_strike_expired_window_allows_again]()
    suite.test[test_quic_0rtt_replay__test_strike_capacity_fail_closed]()
    # tests/quic/test_quic_cc.mojo
    suite.test[test_quic_cc__test_choice_tag]()
    suite.test[test_quic_cc__test_reno_initial_window]()
    suite.test[test_quic_cc__test_reno_slow_start_growth]()
    suite.test[test_quic_cc__test_reno_loss_halves_window]()
    suite.test[test_quic_cc__test_reno_minimum_window_floor]()
    suite.test[test_quic_cc__test_cubic_initial_and_loss]()
    suite.test[test_quic_cc__test_cubic_slow_start_grows]()
    suite.test[test_quic_cc__test_cubic_hystart_exits_on_rtt_rise]()
    suite.test[test_quic_cc__test_cubic_minimum_window_floor]()
    # tests/quic/test_quic_client.mojo
    suite.test[test_quic_client__test_client_handshake_completes]()
    suite.test[test_quic_client__test_client_send_stream_after_handshake]()
    suite.test[test_quic_client__test_client_handshake_through_retry]()
    suite.test[
        test_quic_client__test_stream_control_frames_are_retransmitted_on_pto
    ]()
    suite.test[
        test_quic_client__test_cancel_stream_forbids_further_stream_frames
    ]()
    # tests/quic/test_quic_handle_packet.mojo
    suite.test[test_quic_handle_packet__test_decode_packet_number_rfc_a3]()
    suite.test[test_quic_handle_packet__test_decode_packet_number_no_wrap]()
    suite.test[test_quic_handle_packet__test_protect_unprotect_round_trip]()
    suite.test[
        test_quic_handle_packet__test_handle_packet_drives_state_machine_through_stream_frame
    ]()
    suite.test[
        test_quic_handle_packet__test_listener_dispatch_routes_into_handle_packet
    ]()
    suite.test[
        test_quic_handle_packet__test_dispatch_garbled_initial_drops_silently
    ]()
    suite.test[
        test_quic_handle_packet__test_handle_packet_drops_short_header_silently
    ]()
    suite.test[
        test_quic_handle_packet__test_handle_packet_drops_handshake_long_silently
    ]()
    # tests/quic/test_quic_handshake_bridge.mojo
    suite.test[
        test_quic_handshake_bridge__test_events_crypto_frames_starts_empty
    ]()
    suite.test[
        test_quic_handshake_bridge__test_handle_frame_buf_surfaces_crypto_frame
    ]()
    suite.test[
        test_quic_handshake_bridge__test_listener_bind_empty_pem_yields_null_acceptor
    ]()
    suite.test[
        test_quic_handshake_bridge__test_listener_bind_real_pem_yields_live_acceptor
    ]()
    suite.test[
        test_quic_handshake_bridge__test_accept_initial_materializes_real_session
    ]()
    suite.test[
        test_quic_handshake_bridge__test_accept_initial_empty_pem_keeps_null_sentinel
    ]()
    suite.test[
        test_quic_handshake_bridge__test_bridge_dispatches_crypto_frame_no_crash_real_pem
    ]()
    suite.test[
        test_quic_handshake_bridge__test_bridge_dispatches_crypto_frame_no_crash_empty_pem
    ]()
    suite.test[
        test_quic_handshake_bridge__test_retransmit_does_not_grow_session_slab
    ]()
    suite.test[test_quic_handshake_bridge__test_listener_teardown_no_leak]()
    # tests/quic/test_quic_keys_install.mojo
    suite.test[
        test_quic_keys_install__test_per_level_egress_queues_allocated_in_lockstep
    ]()
    suite.test[
        test_quic_keys_install__test_synth_initial_does_not_flip_handshake_or_1rtt_keys
    ]()
    suite.test[
        test_quic_keys_install__test_multiple_synth_initials_keep_egress_queues_in_lockstep
    ]()
    # tests/quic/test_quic_loopback_integration.mojo
    suite.test[
        test_quic_loopback_integration__test_loopback_initial_handshake_round_trip
    ]()
    suite.test[
        test_quic_loopback_integration__test_loopback_retransmit_routes_to_existing_slot
    ]()
    suite.test[
        test_quic_loopback_integration__test_loopback_idle_close_retires_cid
    ]()
    suite.test[
        test_quic_loopback_integration__test_loopback_unknown_short_header_stateless_reset
    ]()
    suite.test[
        test_quic_loopback_integration__test_egress_build_initial_response_decrypts_at_client
    ]()
    suite.test[
        test_quic_loopback_integration__test_egress_drain_clears_queue_and_advances_counters
    ]()
    suite.test[
        test_quic_loopback_integration__test_egress_no_op_when_queue_empty
    ]()
    suite.test[
        test_quic_loopback_integration__test_io_loop_tick_drives_recv_dispatch_drain
    ]()
    # tests/quic/test_quic_migration.mojo
    suite.test[test_quic_migration__test_client_migrates_to_new_path]()
    # tests/quic/test_quic_migration_probe.mojo
    suite.test[
        test_quic_migration_probe__test_idle_probe_allows_and_should_start
    ]()
    suite.test[test_quic_migration_probe__test_amplification_budget_3x]()
    suite.test[test_quic_migration_probe__test_note_rx_only_counts_candidate]()
    suite.test[test_quic_migration_probe__test_validation_lifts_cap]()
    suite.test[
        test_quic_migration_probe__test_should_start_on_candidate_change
    ]()
    suite.test[test_quic_migration_probe__test_new_path_challenge_encoding]()
    # tests/quic/test_quic_post_initial_decrypt.mojo
    suite.test[
        test_quic_post_initial_decrypt__test_decrypt_post_initial_raises_slot_out_of_range
    ]()
    suite.test[
        test_quic_post_initial_decrypt__test_decrypt_post_initial_raises_on_truncated_handshake
    ]()
    suite.test[
        test_quic_post_initial_decrypt__test_handle_inbound_drops_handshake_without_sentinel
    ]()
    suite.test[
        test_quic_post_initial_decrypt__test_handle_inbound_drops_1rtt_without_sentinel
    ]()
    suite.test[
        test_quic_post_initial_decrypt__test_ack_ranges_exclude_skipped_pn
    ]()
    suite.test[
        test_quic_post_initial_decrypt__test_ack_ranges_contiguous_single_range
    ]()
    suite.test[
        test_quic_post_initial_decrypt__test_ack_ranges_duplicate_pn_is_idempotent
    ]()
    # tests/quic/test_quic_post_initial_egress.mojo
    suite.test[
        test_quic_post_initial_egress__test_handshake_response_empty_when_slot_out_of_range
    ]()
    suite.test[
        test_quic_post_initial_egress__test_1rtt_response_empty_when_slot_out_of_range
    ]()
    suite.test[
        test_quic_post_initial_egress__test_handshake_response_empty_without_readiness_sentinel
    ]()
    suite.test[
        test_quic_post_initial_egress__test_1rtt_response_empty_without_readiness_sentinel
    ]()
    suite.test[
        test_quic_post_initial_egress__test_handshake_response_empty_when_queue_empty
    ]()
    suite.test[
        test_quic_post_initial_egress__test_drain_and_send_noop_on_closed_slot
    ]()
    # tests/quic/test_quic_reactor.mojo
    suite.test[test_quic_reactor__test_bind_opens_real_udp_socket]()
    suite.test[test_quic_reactor__test_bind_honors_explicit_port_zero]()
    suite.test[test_quic_reactor__test_tick_returns_false_on_timeout]()
    suite.test[test_quic_reactor__test_shutdown_makes_run_exit]()
    suite.test[test_quic_reactor__test_dispatch_initial_creates_new_slot]()
    suite.test[
        test_quic_reactor__test_dispatch_initial_retransmit_routes_to_same_slot
    ]()
    suite.test[
        test_quic_reactor__test_dispatch_handshake_with_unknown_dcid_drops
    ]()
    suite.test[test_quic_reactor__test_dispatch_short_unknown_dcid_drops]()
    suite.test[test_quic_reactor__test_dispatch_short_known_dcid_routes]()
    suite.test[test_quic_reactor__test_dispatch_empty_datagram_drops]()
    suite.test[test_quic_reactor__test_live_loopback_tick_routes_initial]()
    suite.test[test_quic_reactor__test_cid_to_hex_round_trip]()
    # tests/quic/test_quic_resumption.mojo
    suite.test[test_quic_resumption__test_resumption_installs_early_keys]()
    # tests/quic/test_quic_retry_server.mojo
    suite.test[test_quic_retry_server__test_quic_retry_server]()
    # tests/quic/test_quic_server_loss_recovery.mojo
    suite.test[
        test_quic_server_loss_recovery__test_loss_slab_starts_empty_and_parallels_connections
    ]()
    suite.test[
        test_quic_server_loss_recovery__test_max_pto_count_has_a_bounded_default
    ]()
    suite.test[
        test_quic_server_loss_recovery__test_slab_tracks_sent_packets_and_retires_them_on_ack
    ]()
    suite.test[
        test_quic_server_loss_recovery__test_pto_fires_frames_for_retransmission
    ]()
    suite.test[
        test_quic_server_loss_recovery__test_ack_of_everything_disarms_the_timer
    ]()
    # tests/quic/test_quic_timers.mojo
    suite.test[test_quic_timers__test_token_round_trip]()
    suite.test[test_quic_timers__test_encode_rejects_invalid_kind]()
    suite.test[test_quic_timers__test_encode_rejects_invalid_slot]()
    suite.test[test_quic_timers__test_decode_rejects_unknown_kind]()
    suite.test[test_quic_timers__test_timer_kind_name]()
    suite.test[test_quic_timers__test_schedule_idle_cancels_previous]()
    suite.test[test_quic_timers__test_advance_idle_closes_connection]()
    suite.test[test_quic_timers__test_dispatch_arms_idle_timer_on_accept]()
    suite.test[
        test_quic_timers__test_on_idle_callback_is_idempotent_to_double_fire
    ]()
    # tests/quic/test_retry.mojo
    suite.test[test_retry__test_retry_integrity_tag_rfc9001_a4]()
    suite.test[test_retry__test_verify_retry_integrity_round_trip]()
    suite.test[test_retry__test_retry_token_round_trip]()
    suite.test[test_retry__test_retry_token_address_mismatch_rejected]()
    suite.test[test_retry__test_retry_token_expired_rejected]()
    suite.test[test_retry__test_retry_token_tamper_rejected]()
    suite.test[test_retry__test_retry_token_wrong_key_rejected]()
    suite.test[test_retry__test_version_negotiation_shape]()
    # tests/quic/test_rfc9001_appendix_a.mojo
    suite.test[test_rfc9001_appendix_a__test_a1_initial_secrets]()
    suite.test[test_rfc9001_appendix_a__test_a1_client_packet_keys]()
    suite.test[test_rfc9001_appendix_a__test_a1_server_packet_keys]()
    suite.test[
        test_rfc9001_appendix_a__test_a2_client_initial_aead_round_trip
    ]()
    suite.test[
        test_rfc9001_appendix_a__test_a3_server_initial_aead_round_trip
    ]()
    suite.test[
        test_rfc9001_appendix_a__test_a2_client_initial_full_ciphertext_bytes
    ]()
    suite.test[
        test_rfc9001_appendix_a__test_handshake_round_trip_short_payload
    ]()
    suite.test[test_rfc9001_appendix_a__test_handshake_round_trip_aes_256_gcm]()
    suite.test[test_rfc9001_appendix_a__test_1rtt_round_trip_synthetic]()
    suite.test[
        test_rfc9001_appendix_a__test_1rtt_round_trip_empty_dcid_pn_length_3
    ]()
    suite.test[
        test_rfc9001_appendix_a__test_a5_chacha20_short_header_round_trip
    ]()
    suite.test[test_rfc9001_appendix_a__test_handshake_rejects_short_header]()
    suite.test[test_rfc9001_appendix_a__test_1rtt_rejects_long_header]()
    # tests/quic/test_server_scaffold.mojo
    suite.test[test_server_scaffold__test_config_defaults]()
    suite.test[test_server_scaffold__test_config_carries_overrides]()
    suite.test[
        test_server_scaffold__test_quic_connection_starts_alive_in_handshake
    ]()
    suite.test[test_server_scaffold__test_quic_connection_records_cids]()
    suite.test[test_server_scaffold__test_cid_table_register_lookup_retire]()
    suite.test[
        test_server_scaffold__test_cid_table_lookup_missing_returns_minus_one
    ]()
    suite.test[test_server_scaffold__test_cid_table_register_overwrites]()
    # tests/quic/test_state.mojo
    suite.test[test_state__test_initial_connection_state]()
    suite.test[test_state__test_handshake_done_advances_state]()
    suite.test[test_state__test_mark_handshake_complete_explicit_hook]()
    suite.test[test_state__test_stream_frame_opens_stream]()
    suite.test[test_state__test_stream_frame_with_fin_finishes_stream]()
    suite.test[test_state__test_ack_eliciting_flag_flips_pending]()
    suite.test[test_state__test_padding_does_not_flip_ack_pending]()
    suite.test[test_state__test_max_data_advances_send_limit]()
    suite.test[test_state__test_connection_close_frame_drains]()
    suite.test[test_state__test_connection_close_explicit_helper]()
    suite.test[test_state__test_idle_timeout_detection]()
    suite.test[test_state__test_flow_control_violation_raises]()
    suite.test[test_state__test_ack_frame_advances_largest_acked]()
    suite.test[test_state__test_new_connection_id_stores_peer_cid]()
    suite.test[
        test_state__test_new_connection_id_retire_prior_to_queues_retire
    ]()
    suite.test[test_state__test_new_connection_id_bad_length_raises]()
    suite.test[test_state__test_retire_connection_id_acks]()
    suite.test[test_state__test_path_challenge_queues_response]()
    suite.test[test_state__test_path_response_validates_matching_challenge]()
    suite.test[test_state__test_path_response_mismatch_ignored]()
    # tests/quic/test_transport_params.mojo
    suite.test[test_transport_params__test_round_trip_full_set]()
    suite.test[test_transport_params__test_empty_params_roundtrip]()
    suite.test[
        test_transport_params__test_disable_active_migration_zero_length
    ]()
    suite.test[
        test_transport_params__test_stateless_reset_token_must_be_16_bytes
    ]()
    suite.test[
        test_transport_params__test_max_udp_payload_size_below_1200_rejected
    ]()
    suite.test[
        test_transport_params__test_ack_delay_exponent_above_20_rejected
    ]()
    suite.test[
        test_transport_params__test_active_connection_id_limit_below_2_rejected
    ]()
    suite.test[test_transport_params__test_duplicate_id_rejected]()
    suite.test[test_transport_params__test_unknown_id_silently_dropped]()
    suite.test[test_transport_params__test_truncated_value_rejected]()
    suite.test[test_transport_params__test_max_datagram_frame_size_roundtrip]()
    suite.test[test_transport_params__test_derive_peer_send_limits_defaults]()
    suite.test[test_transport_params__test_derive_peer_send_limits_set]()
    # tests/quic/test_varint.mojo
    suite.test[test_varint__test_rfc9000_appendix_a_1byte_form]()
    suite.test[test_varint__test_rfc9000_appendix_a_2byte_form]()
    suite.test[test_varint__test_rfc9000_appendix_a_4byte_form]()
    suite.test[test_varint__test_rfc9000_appendix_a_8byte_form]()
    suite.test[test_varint__test_boundary_values]()
    suite.test[test_varint__test_zero_round_trips]()
    suite.test[test_varint__test_encoder_rejects_overflow]()
    suite.test[test_varint__test_decoder_rejects_empty_buffer]()
    suite.test[test_varint__test_decoder_rejects_truncated_input]()
    suite.test[test_varint__test_round_trip_many_values]()
    suite.test[test_varint__test_decoder_consumes_only_first_varint]()
    suite^.run()
