"""GENERATED by tests/tools/gen_test_aggregates.py -- do not edit.

Aggregates the 2 test files of ``tests/uds/`` into one compiled
binary so the 2 separate compiler invocations become one. Run it with
``mojo -I . -I tests/uds`` (see tests/tools/run_test_aggregates.sh).

Regenerate with ``python3 tests/tools/gen_test_aggregates.py``; CI fails if this
file is out of date with the tree.
"""

from std.testing import TestSuite
from test_frame_mux import (
    test_encode_decode_roundtrip as test_frame_mux__test_encode_decode_roundtrip,
)
from test_frame_mux import (
    test_decode_short_buffer_raises as test_frame_mux__test_decode_short_buffer_raises,
)
from test_frame_mux import (
    test_demux_multiple_frames_one_feed as test_frame_mux__test_demux_multiple_frames_one_feed,
)
from test_frame_mux import (
    test_demux_split_across_feeds as test_frame_mux__test_demux_split_across_feeds,
)
from test_frame_mux import (
    test_demux_oversize_length_raises as test_frame_mux__test_demux_oversize_length_raises,
)
from test_frame_mux import (
    test_demux_thousand_streams_isolated as test_frame_mux__test_demux_thousand_streams_isolated,
)
from test_uds_listener import (
    test_af_unix_constant as test_uds_listener__test_af_unix_constant,
)
from test_uds_listener import (
    test_sun_path_max_is_platform_correct as test_uds_listener__test_sun_path_max_is_platform_correct,
)
from test_uds_listener import (
    test_bind_then_query_local_path as test_uds_listener__test_bind_then_query_local_path,
)
from test_uds_listener import (
    test_bind_unlinks_stale_socket_by_default as test_uds_listener__test_bind_unlinks_stale_socket_by_default,
)
from test_uds_listener import (
    test_round_trip_bytes as test_uds_listener__test_round_trip_bytes,
)
from test_uds_listener import (
    test_eof_on_peer_close as test_uds_listener__test_eof_on_peer_close,
)
from test_uds_listener import (
    test_accept_via_borrowed_fd as test_uds_listener__test_accept_via_borrowed_fd,
)
from test_uds_listener import (
    test_path_too_long_raises as test_uds_listener__test_path_too_long_raises,
)
from test_uds_listener import (
    test_embedded_nul_raises as test_uds_listener__test_embedded_nul_raises,
)
from test_uds_listener import (
    test_connect_to_nonexistent_path_raises_refused as test_uds_listener__test_connect_to_nonexistent_path_raises_refused,
)


def main() raises:
    var suite = TestSuite()
    # tests/uds/test_frame_mux.mojo
    suite.test[test_frame_mux__test_encode_decode_roundtrip]()
    suite.test[test_frame_mux__test_decode_short_buffer_raises]()
    suite.test[test_frame_mux__test_demux_multiple_frames_one_feed]()
    suite.test[test_frame_mux__test_demux_split_across_feeds]()
    suite.test[test_frame_mux__test_demux_oversize_length_raises]()
    suite.test[test_frame_mux__test_demux_thousand_streams_isolated]()
    # tests/uds/test_uds_listener.mojo
    suite.test[test_uds_listener__test_af_unix_constant]()
    suite.test[test_uds_listener__test_sun_path_max_is_platform_correct]()
    suite.test[test_uds_listener__test_bind_then_query_local_path]()
    suite.test[test_uds_listener__test_bind_unlinks_stale_socket_by_default]()
    suite.test[test_uds_listener__test_round_trip_bytes]()
    suite.test[test_uds_listener__test_eof_on_peer_close]()
    suite.test[test_uds_listener__test_accept_via_borrowed_fd]()
    suite.test[test_uds_listener__test_path_too_long_raises]()
    suite.test[test_uds_listener__test_embedded_nul_raises]()
    suite.test[
        test_uds_listener__test_connect_to_nonexistent_path_raises_refused
    ]()
    suite^.run()
