"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 18 test files of ``tests/runtime/`` into one compiled
binary so the 18 separate compiler invocations become one. Run it with
``mojo -I . -I tests/runtime`` (see tools/run_test_aggregates.sh).

Regenerate with ``python3 tools/gen_test_aggregates.py``; CI fails if this
file is out of date with the tree.
"""

from std.testing import TestSuite
from test_buffer_pool import (
    test_size_for_rounds_up_to_size_class as test_buffer_pool__test_size_for_rounds_up_to_size_class,
)
from test_buffer_pool import (
    test_size_for_oversize_returns_caller_request_verbatim as test_buffer_pool__test_size_for_oversize_returns_caller_request_verbatim,
)
from test_buffer_pool import (
    test_handle_for_class_reserves_size_class_capacity as test_buffer_pool__test_handle_for_class_reserves_size_class_capacity,
)
from test_buffer_pool import (
    test_handle_reset_preserves_capacity as test_buffer_pool__test_handle_reset_preserves_capacity,
)
from test_buffer_pool import (
    test_pool_default_class_capacity_is_eight as test_buffer_pool__test_pool_default_class_capacity_is_eight,
)
from test_buffer_pool import (
    test_pool_with_class_capacity_factory as test_buffer_pool__test_pool_with_class_capacity_factory,
)
from test_buffer_pool import (
    test_pool_with_class_capacity_clamps_minimum_to_one as test_buffer_pool__test_pool_with_class_capacity_clamps_minimum_to_one,
)
from test_buffer_pool import (
    test_pool_acquire_from_empty_constructs_fresh_class_0 as test_buffer_pool__test_pool_acquire_from_empty_constructs_fresh_class_0,
)
from test_buffer_pool import (
    test_pool_acquire_dispatches_to_correct_class as test_buffer_pool__test_pool_acquire_dispatches_to_correct_class,
)
from test_buffer_pool import (
    test_pool_acquire_oversize_bypasses_pool as test_buffer_pool__test_pool_acquire_oversize_bypasses_pool,
)
from test_buffer_pool import (
    test_pool_release_oversize_does_not_grow_any_bucket as test_buffer_pool__test_pool_release_oversize_does_not_grow_any_bucket,
)
from test_buffer_pool import (
    test_pool_release_then_acquire_recycles_capacity as test_buffer_pool__test_pool_release_then_acquire_recycles_capacity,
)
from test_buffer_pool import (
    test_pool_release_past_class_capacity_drops_extras as test_buffer_pool__test_pool_release_past_class_capacity_drops_extras,
)
from test_buffer_pool import (
    test_pool_buckets_are_independent as test_buffer_pool__test_pool_buckets_are_independent,
)
from test_buffer_pool import (
    test_pool_acquire_release_acquire_lifo_within_class as test_buffer_pool__test_pool_acquire_release_acquire_lifo_within_class,
)
from test_buffer_pool import (
    test_pool_size_accessor_handles_out_of_range as test_buffer_pool__test_pool_size_accessor_handles_out_of_range,
)
from test_buffer_pool import (
    test_pool_release_with_invalid_class_index_drops_silently as test_buffer_pool__test_pool_release_with_invalid_class_index_drops_silently,
)
from test_compact_read_buf import (
    test_drop_zero_keeps_full_buffer as test_compact_read_buf__test_drop_zero_keeps_full_buffer,
)
from test_compact_read_buf import (
    test_drop_one_shifts_remaining as test_compact_read_buf__test_drop_one_shifts_remaining,
)
from test_compact_read_buf import (
    test_drop_prefix_keeps_trailing as test_compact_read_buf__test_drop_prefix_keeps_trailing,
)
from test_compact_read_buf import (
    test_drop_all_clears_buffer as test_compact_read_buf__test_drop_all_clears_buffer,
)
from test_compact_read_buf import (
    test_drop_more_than_len_clears_buffer as test_compact_read_buf__test_drop_more_than_len_clears_buffer,
)
from test_compact_read_buf import (
    test_drop_from_empty_is_noop as test_compact_read_buf__test_drop_from_empty_is_noop,
)
from test_compact_read_buf import (
    test_drop_long_buffer_preserves_byte_order as test_compact_read_buf__test_drop_long_buffer_preserves_byte_order,
)
from test_date_cache import (
    test_cache_primes_on_construction as test_date_cache__test_cache_primes_on_construction,
)
from test_date_cache import (
    test_cache_layout_imf_fixdate_shape as test_date_cache__test_cache_layout_imf_fixdate_shape,
)
from test_date_cache import (
    test_weekday_in_known_set as test_date_cache__test_weekday_in_known_set,
)
from test_date_cache import (
    test_month_in_known_set as test_date_cache__test_month_in_known_set,
)
from test_date_cache import (
    test_year_at_or_after_2026 as test_date_cache__test_year_at_or_after_2026,
)
from test_date_cache import (
    test_hour_minute_second_in_range as test_date_cache__test_hour_minute_second_in_range,
)
from test_date_cache import (
    test_refresh_is_noop_within_same_second as test_date_cache__test_refresh_is_noop_within_same_second,
)
from test_date_cache import (
    test_refresh_advances_after_one_second as test_date_cache__test_refresh_advances_after_one_second,
)
from test_date_cache import (
    test_current_bytes_and_string_agree as test_date_cache__test_current_bytes_and_string_agree,
)
from test_date_cache import (
    test_format_known_unix_seconds as test_date_cache__test_format_known_unix_seconds,
)
from test_date_cache import (
    test_format_y2038_cusp as test_date_cache__test_format_y2038_cusp,
)
from test_date_cache import (
    test_format_distant_future as test_date_cache__test_format_distant_future,
)
from test_date_cache import (
    test_format_leap_day_2024 as test_date_cache__test_format_leap_day_2024,
)
from test_date_cache import (
    test_format_unix_epoch as test_date_cache__test_format_unix_epoch,
)
from test_io_uring import (
    test_syscall_numbers_match_linux_abi as test_io_uring__test_syscall_numbers_match_linux_abi,
)
from test_io_uring import (
    test_io_uring_params_empty_factory_zeroes_all_fields as test_io_uring__test_io_uring_params_empty_factory_zeroes_all_fields,
)
from test_io_uring import (
    test_is_io_uring_available_returns_bool as test_io_uring__test_is_io_uring_available_returns_bool,
)
from test_io_uring import (
    test_is_io_uring_available_false_on_non_linux as test_io_uring__test_is_io_uring_available_false_on_non_linux,
)
from test_io_uring import (
    test_setup_and_teardown_a_ring_when_available as test_io_uring__test_setup_and_teardown_a_ring_when_available,
)
from test_io_uring import (
    test_setup_returns_features_flags as test_io_uring__test_setup_returns_features_flags,
)
from test_io_uring import (
    test_setup_rounds_entries_up_to_power_of_two as test_io_uring__test_setup_rounds_entries_up_to_power_of_two,
)
from test_io_uring import (
    test_multiple_rings_are_independent as test_io_uring__test_multiple_rings_are_independent,
)
from test_io_uring import (
    test_setup_flags_zero_default_works as test_io_uring__test_setup_flags_zero_default_works,
)
from test_io_uring import (
    test_setup_flag_coop_taskrun_accepted_or_einval as test_io_uring__test_setup_flag_coop_taskrun_accepted_or_einval,
)
from test_io_uring import (
    test_setup_flag_combined_bufring_recipe_accepted_or_einval as test_io_uring__test_setup_flag_combined_bufring_recipe_accepted_or_einval,
)
from test_io_uring_driver import (
    test_driver_construction_succeeds as test_io_uring_driver__test_driver_construction_succeeds,
)
from test_io_uring_driver import (
    test_fresh_driver_has_no_pending_cqes as test_io_uring_driver__test_fresh_driver_has_no_pending_cqes,
)
from test_io_uring_driver import (
    test_nop_round_trip_returns_user_data as test_io_uring_driver__test_nop_round_trip_returns_user_data,
)
from test_io_uring_driver import (
    test_multi_nop_round_trip_preserves_order as test_io_uring_driver__test_multi_nop_round_trip_preserves_order,
)
from test_io_uring_driver import (
    test_reap_cqe_drains_then_returns_none as test_io_uring_driver__test_reap_cqe_drains_then_returns_none,
)
from test_io_uring_driver import (
    test_next_sqe_advances_sequentially as test_io_uring_driver__test_next_sqe_advances_sequentially,
)
from test_io_uring_multishot_accept import (
    test_multishot_accept_round_trip as test_io_uring_multishot_accept__test_multishot_accept_round_trip,
)
from test_iovec import (
    test_iovec_size_for_returns_16_per_cell as test_iovec__test_iovec_size_for_returns_16_per_cell,
)
from test_iovec import (
    test_iovec_count_matches_constructor_arg as test_iovec__test_iovec_count_matches_constructor_arg,
)
from test_iovec import (
    test_iovec_set_then_read_back_round_trip as test_iovec__test_iovec_set_then_read_back_round_trip,
)
from test_iovec import (
    test_iovec_unset_cells_default_to_null_zero as test_iovec__test_iovec_unset_cells_default_to_null_zero,
)
from test_iovec import (
    test_iovec_set_overwrites_previous_value as test_iovec__test_iovec_set_overwrites_previous_value,
)
from test_iovec import (
    test_writev_delivers_concatenated_bytes_to_peer as test_iovec__test_writev_delivers_concatenated_bytes_to_peer,
)
from test_iovec import (
    test_writev_with_zero_length_cells_skips_them as test_iovec__test_writev_with_zero_length_cells_skips_them,
)
from test_iovec import (
    test_writev_single_cell_matches_send_semantics as test_iovec__test_writev_single_cell_matches_send_semantics,
)
from test_iovec import (
    test_writev_buf_all_zeroes_consumed_cells as test_iovec__test_writev_buf_all_zeroes_consumed_cells,
)
from test_libc_time import (
    test_usleep_small_returns_zero as test_libc_time__test_usleep_small_returns_zero,
)
from test_libc_time import (
    test_usleep_zero_is_noop as test_libc_time__test_usleep_zero_is_noop,
)
from test_libc_time import (
    test_usleep_negative_is_noop as test_libc_time__test_usleep_negative_is_noop,
)
from test_libc_time import (
    test_usleep_10ms_takes_at_least_5ms as test_libc_time__test_usleep_10ms_takes_at_least_5ms,
)
from test_libc_time import (
    test_nanosleep_zero_is_noop as test_libc_time__test_nanosleep_zero_is_noop,
)
from test_libc_time import (
    test_nanosleep_negative_is_noop as test_libc_time__test_nanosleep_negative_is_noop,
)
from test_libc_time import (
    test_nanosleep_50ms_within_budget as test_libc_time__test_nanosleep_50ms_within_budget,
)
from test_libc_time import (
    test_nanosleep_200ms_takes_at_least_100ms as test_libc_time__test_nanosleep_200ms_takes_at_least_100ms,
)
from test_libc_time import (
    test_monotonic_is_non_decreasing as test_libc_time__test_monotonic_is_non_decreasing,
)
from test_libc_time import (
    test_monotonic_tracks_a_sleep as test_libc_time__test_monotonic_tracks_a_sleep,
)
from test_libc_time import (
    test_hundred_one_ms_sleeps_within_2000ms as test_libc_time__test_hundred_one_ms_sleeps_within_2000ms,
)
from test_pool import (
    test_alloc_returns_nonzero_address as test_pool__test_alloc_returns_nonzero_address,
)
from test_pool import (
    test_alloc_then_get_ptr_reads_value as test_pool__test_alloc_then_get_ptr_reads_value,
)
from test_pool import (
    test_free_calls_destructor_exactly_once as test_pool__test_free_calls_destructor_exactly_once,
)
from test_pool import (
    test_free_zero_is_noop as test_pool__test_free_zero_is_noop,
)
from test_pool import (
    test_alloc_free_cycle_no_leak as test_pool__test_alloc_free_cycle_no_leak,
)
from test_pool import test_thousand_cycles as test_pool__test_thousand_cycles
from test_pool import (
    test_pool_with_string_field as test_pool__test_pool_with_string_field,
)
from test_reactor import (
    test_create_and_destroy as test_reactor__test_create_and_destroy,
)
from test_reactor import (
    test_many_create_destroy_no_leak as test_reactor__test_many_create_destroy_no_leak,
)
from test_reactor import (
    test_register_then_is_registered as test_reactor__test_register_then_is_registered,
)
from test_reactor import (
    test_register_rejects_wakeup_token as test_reactor__test_register_rejects_wakeup_token,
)
from test_reactor import (
    test_register_rejects_empty_interest as test_reactor__test_register_rejects_empty_interest,
)
from test_reactor import (
    test_register_same_fd_twice_raises as test_reactor__test_register_same_fd_twice_raises,
)
from test_reactor import (
    test_unregister_unknown_fd_raises as test_reactor__test_unregister_unknown_fd_raises,
)
from test_reactor import (
    test_unregister_after_close_succeeds as test_reactor__test_unregister_after_close_succeeds,
)
from test_reactor import (
    test_unregister_after_close_frees_fd_for_reuse as test_reactor__test_unregister_after_close_frees_fd_for_reuse,
)
from test_reactor import (
    test_modify_unknown_fd_raises as test_reactor__test_modify_unknown_fd_raises,
)
from test_reactor import (
    test_modify_from_read_to_write as test_reactor__test_modify_from_read_to_write,
)
from test_reactor import (
    test_poll_timeout_zero_returns_empty as test_reactor__test_poll_timeout_zero_returns_empty,
)
from test_reactor import (
    test_poll_timeout_short_returns_empty as test_reactor__test_poll_timeout_short_returns_empty,
)
from test_reactor import (
    test_poll_detects_readable_on_writable_peer as test_reactor__test_poll_detects_readable_on_writable_peer,
)
from test_reactor import (
    test_poll_detects_writable as test_reactor__test_poll_detects_writable,
)
from test_reactor import (
    test_poll_detects_hup_on_peer_close as test_reactor__test_poll_detects_hup_on_peer_close,
)
from test_reactor import (
    test_poll_multiple_fds as test_reactor__test_poll_multiple_fds,
)
from test_reactor import (
    test_wakeup_breaks_blocking_poll as test_reactor__test_wakeup_breaks_blocking_poll,
)
from test_reactor import (
    test_wakeup_does_not_appear_without_call as test_reactor__test_wakeup_does_not_appear_without_call,
)
from test_reactor import (
    test_wakeup_after_drain_can_fire_again as test_reactor__test_wakeup_after_drain_can_fire_again,
)
from test_reactor import (
    test_poll_reuses_event_buffer_across_calls as test_reactor__test_poll_reuses_event_buffer_across_calls,
)
from test_reactor import (
    test_poll_honors_max_events_cap as test_reactor__test_poll_honors_max_events_cap,
)
from test_reactor import (
    test_event_flag_helpers as test_reactor__test_event_flag_helpers,
)
from test_reactor_shutdown import (
    test_server_config_shutdown_timeout_default as test_reactor_shutdown__test_server_config_shutdown_timeout_default,
)
from test_reactor_shutdown import (
    test_server_config_shutdown_timeout_custom as test_reactor_shutdown__test_server_config_shutdown_timeout_custom,
)
from test_reactor_shutdown import (
    test_server_close_is_idempotent as test_reactor_shutdown__test_server_close_is_idempotent,
)
from test_reactor_shutdown import (
    test_server_close_sets_stopping_flag as test_reactor_shutdown__test_server_close_sets_stopping_flag,
)
from test_reactor_shutdown import (
    test_server_rebind_after_close as test_reactor_shutdown__test_server_rebind_after_close,
)
from test_reactor_shutdown import (
    test_server_bind_same_port_twice_fails as test_reactor_shutdown__test_server_bind_same_port_twice_fails,
)
from test_reactor_shutdown import (
    test_server_config_is_copyable_for_struct_literal_reuse as test_reactor_shutdown__test_server_config_is_copyable_for_struct_literal_reuse,
)
from test_safety_asserts import (
    test_iovec_set_at_every_legal_index as test_safety_asserts__test_iovec_set_at_every_legal_index,
)
from test_safety_asserts import (
    test_iovec_set_zero_len_with_null_ptr_is_legal as test_safety_asserts__test_iovec_set_zero_len_with_null_ptr_is_legal,
)
from test_safety_asserts import (
    test_iovec_set_nonzero_len_with_real_ptr_is_legal as test_safety_asserts__test_iovec_set_nonzero_len_with_real_ptr_is_legal,
)
from test_safety_asserts import (
    test_buffer_pool_acquire_at_each_size_class as test_safety_asserts__test_buffer_pool_acquire_at_each_size_class,
)
from test_safety_asserts import (
    test_buffer_pool_acquire_zero_min_capacity_is_legal as test_safety_asserts__test_buffer_pool_acquire_zero_min_capacity_is_legal,
)
from test_safety_asserts import (
    test_response_pool_with_capacity_clamps_zero_input as test_safety_asserts__test_response_pool_with_capacity_clamps_zero_input,
)
from test_safety_asserts import (
    test_response_pool_acquire_release_round_trip as test_safety_asserts__test_response_pool_acquire_release_round_trip,
)
from test_safety_asserts import (
    test_date_cache_construct_and_refresh as test_safety_asserts__test_date_cache_construct_and_refresh,
)
from test_safety_asserts import (
    test_date_cache_two_digit_writes_cover_full_range as test_safety_asserts__test_date_cache_two_digit_writes_cover_full_range,
)
from test_safety_asserts import (
    test_huffman_encode_byte_range_assert_holds as test_safety_asserts__test_huffman_encode_byte_range_assert_holds,
)
from test_safety_asserts import (
    test_huffman_decode_empty_input_is_legal as test_safety_asserts__test_huffman_decode_empty_input_is_legal,
)
from test_safety_asserts import (
    test_simd_memmem_empty_haystack_no_assert as test_safety_asserts__test_simd_memmem_empty_haystack_no_assert,
)
from test_safety_asserts import (
    test_simd_percent_decode_empty_input_no_assert as test_safety_asserts__test_simd_percent_decode_empty_input_no_assert,
)
from test_safety_asserts import (
    test_simd_cookie_scan_empty_input_no_assert as test_safety_asserts__test_simd_cookie_scan_empty_input_no_assert,
)
from test_safety_asserts import (
    test_io_uring_feature_detection_no_assert as test_safety_asserts__test_io_uring_feature_detection_no_assert,
)
from test_scheduler import (
    test_default_worker_count_positive as test_scheduler__test_default_worker_count_positive,
)
from test_scheduler import (
    test_scheduler_start_and_shutdown_n2 as test_scheduler__test_scheduler_start_and_shutdown_n2,
)
from test_scheduler import (
    test_scheduler_start_and_shutdown_n4 as test_scheduler__test_scheduler_start_and_shutdown_n4,
)
from test_scheduler import (
    test_scheduler_drain_returns_per_worker_reports as test_scheduler__test_scheduler_drain_returns_per_worker_reports,
)
from test_scheduler import (
    test_scheduler_drain_zero_timeout_is_hard_stop as test_scheduler__test_scheduler_drain_zero_timeout_is_hard_stop,
)
from test_scheduler import (
    test_scheduler_shutdown_idempotent as test_scheduler__test_scheduler_shutdown_idempotent,
)
from test_scheduler import (
    test_scheduler_multiple_start_cycles as test_scheduler__test_scheduler_multiple_start_cycles,
)
from test_scheduler import (
    test_scheduler_pin_cores_flag_default_no_crash as test_scheduler__test_scheduler_pin_cores_flag_default_no_crash,
)
from test_syscall_ffi import (
    test_epoll_constants_distinct_bits as test_syscall_ffi__test_epoll_constants_distinct_bits,
)
from test_syscall_ffi import (
    test_epoll_ctl_op_constants as test_syscall_ffi__test_epoll_ctl_op_constants,
)
from test_syscall_ffi import (
    test_epoll_event_size_matches_arch as test_syscall_ffi__test_epoll_event_size_matches_arch,
)
from test_syscall_ffi import (
    test_epoll_event_set_and_read_back as test_syscall_ffi__test_epoll_event_set_and_read_back,
)
from test_syscall_ffi import (
    test_epoll_create1_and_close as test_syscall_ffi__test_epoll_create1_and_close,
)
from test_syscall_ffi import (
    test_epoll_create1_with_cloexec as test_syscall_ffi__test_epoll_create1_with_cloexec,
)
from test_syscall_ffi import (
    test_epoll_ctl_add_then_del_ok as test_syscall_ffi__test_epoll_ctl_add_then_del_ok,
)
from test_syscall_ffi import (
    test_epoll_wait_timeout_zero_returns_empty as test_syscall_ffi__test_epoll_wait_timeout_zero_returns_empty,
)
from test_syscall_ffi import (
    test_epoll_wait_detects_readable as test_syscall_ffi__test_epoll_wait_detects_readable,
)
from test_syscall_ffi import (
    test_kqueue_filter_constants as test_syscall_ffi__test_kqueue_filter_constants,
)
from test_syscall_ffi import (
    test_kqueue_flag_constants_distinct_bits as test_syscall_ffi__test_kqueue_flag_constants_distinct_bits,
)
from test_syscall_ffi import (
    test_kevent_size_is_32 as test_syscall_ffi__test_kevent_size_is_32,
)
from test_syscall_ffi import (
    test_kevent_set_and_read_back_positive_fields as test_syscall_ffi__test_kevent_set_and_read_back_positive_fields,
)
from test_syscall_ffi import (
    test_kevent_set_filter_negative_roundtrip as test_syscall_ffi__test_kevent_set_filter_negative_roundtrip,
)
from test_syscall_ffi import (
    test_kqueue_create_and_close as test_syscall_ffi__test_kqueue_create_and_close,
)
from test_syscall_ffi import (
    test_kevent_zero_changes_zero_events_timeout_returns_zero as test_syscall_ffi__test_kevent_zero_changes_zero_events_timeout_returns_zero,
)
from test_syscall_ffi import (
    test_kevent_detects_readable as test_syscall_ffi__test_kevent_detects_readable,
)
from test_syscall_ffi import (
    test_eventfd_write_then_read_counts as test_syscall_ffi__test_eventfd_write_then_read_counts,
)
from test_syscall_ffi import (
    test_pipe_round_trip_byte as test_syscall_ffi__test_pipe_round_trip_byte,
)
from test_syscall_ffi import (
    test_epoll_wait_on_invalid_fd_returns_negative as test_syscall_ffi__test_epoll_wait_on_invalid_fd_returns_negative,
)
from test_syscall_ffi import (
    test_kevent_on_invalid_fd_returns_negative as test_syscall_ffi__test_kevent_on_invalid_fd_returns_negative,
)
from test_syscall_ffi import (
    test_set_nonblocking_toggle_does_not_raise as test_syscall_ffi__test_set_nonblocking_toggle_does_not_raise,
)
from test_thread_ffi import (
    test_num_cpus_at_least_one as test_thread_ffi__test_num_cpus_at_least_one,
)
from test_thread_ffi import (
    test_num_cpus_reasonable as test_thread_ffi__test_num_cpus_reasonable,
)
from test_thread_ffi import (
    test_current_thread_id_nonzero as test_thread_ffi__test_current_thread_id_nonzero,
)
from test_thread_ffi import (
    test_spawn_join_noop as test_thread_ffi__test_spawn_join_noop,
)
from test_thread_ffi import (
    test_spawn_writes_argument as test_thread_ffi__test_spawn_writes_argument,
)
from test_thread_ffi import (
    test_spawn_multiple_threads as test_thread_ffi__test_spawn_multiple_threads,
)
from test_thread_ffi import (
    test_pin_to_cpu0_after_spawn as test_thread_ffi__test_pin_to_cpu0_after_spawn,
)
from test_thread_ffi import (
    test_pin_to_cpu_min_of_available as test_thread_ffi__test_pin_to_cpu_min_of_available,
)
from test_thread_ffi import (
    test_many_spawn_join_cycles as test_thread_ffi__test_many_spawn_join_cycles,
)
from test_thread_ffi import (
    test_thread_id_unique_across_workers as test_thread_ffi__test_thread_id_unique_across_workers,
)
from test_timer_wheel import (
    test_schedule_returns_unique_ids as test_timer_wheel__test_schedule_returns_unique_ids,
)
from test_timer_wheel import (
    test_empty_wheel_active_count_zero as test_timer_wheel__test_empty_wheel_active_count_zero,
)
from test_timer_wheel import (
    test_schedule_increments_active_count as test_timer_wheel__test_schedule_increments_active_count,
)
from test_timer_wheel import (
    test_timer_fires_after_correct_delay as test_timer_wheel__test_timer_fires_after_correct_delay,
)
from test_timer_wheel import (
    test_multiple_timers_fire_in_order as test_timer_wheel__test_multiple_timers_fire_in_order,
)
from test_timer_wheel import (
    test_immediate_timer_fires_next_advance as test_timer_wheel__test_immediate_timer_fires_next_advance,
)
from test_timer_wheel import (
    test_zero_advance_fires_nothing as test_timer_wheel__test_zero_advance_fires_nothing,
)
from test_timer_wheel import (
    test_cancel_is_idempotent as test_timer_wheel__test_cancel_is_idempotent,
)
from test_timer_wheel import (
    test_cancel_unknown_id_returns_false as test_timer_wheel__test_cancel_unknown_id_returns_false,
)
from test_timer_wheel import (
    test_cancelled_timer_does_not_fire as test_timer_wheel__test_cancelled_timer_does_not_fire,
)
from test_timer_wheel import (
    test_timer_past_one_rotation_fires_eventually as test_timer_wheel__test_timer_past_one_rotation_fires_eventually,
)
from test_timer_wheel import (
    test_timer_at_exactly_512ms_fires as test_timer_wheel__test_timer_at_exactly_512ms_fires,
)
from test_timer_wheel import (
    test_multiple_rotations_still_fire as test_timer_wheel__test_multiple_rotations_still_fire,
)
from test_timer_wheel import (
    test_1000_short_timers_all_fire as test_timer_wheel__test_1000_short_timers_all_fire,
)
from test_timer_wheel import (
    test_many_cancels_dont_leak as test_timer_wheel__test_many_cancels_dont_leak,
)
from test_timer_wheel import (
    test_now_ms_reflects_advance as test_timer_wheel__test_now_ms_reflects_advance,
)
from test_timer_wheel import (
    test_next_fire_ms_returns_earliest as test_timer_wheel__test_next_fire_ms_returns_earliest,
)
from test_timer_wheel import (
    test_next_fire_ms_empty_returns_sentinel as test_timer_wheel__test_next_fire_ms_empty_returns_sentinel,
)
from test_timer_wheel import (
    test_next_fire_ms_overflow_only_returns_rotation as test_timer_wheel__test_next_fire_ms_overflow_only_returns_rotation,
)
from test_timer_wheel import (
    test_next_fire_ms_recovers_after_advance as test_timer_wheel__test_next_fire_ms_recovers_after_advance,
)
from test_timer_wheel import (
    test_next_fire_ms_cancel_is_lower_bound as test_timer_wheel__test_next_fire_ms_cancel_is_lower_bound,
)
from test_uring_reactor import (
    test_pack_unpack_round_trip as test_uring_reactor__test_pack_unpack_round_trip,
)
from test_uring_reactor import (
    test_pack_op_does_not_clobber_conn_id as test_uring_reactor__test_pack_op_does_not_clobber_conn_id,
)
from test_uring_reactor import (
    test_construction_succeeds as test_uring_reactor__test_construction_succeeds,
)
from test_uring_reactor import (
    test_idle_poll_returns_zero as test_uring_reactor__test_idle_poll_returns_zero,
)
from test_uring_reactor import (
    test_arm_listener_multishot_round_trip as test_uring_reactor__test_arm_listener_multishot_round_trip,
)
from test_uring_reactor import (
    test_submit_send_round_trip as test_uring_reactor__test_submit_send_round_trip,
)
from test_uring_reactor import (
    test_wakeup_releases_blocking_poll as test_uring_reactor__test_wakeup_releases_blocking_poll,
)
from test_uring_reactor import (
    test_arm_poll_readable_multishot_round_trip as test_uring_reactor__test_arm_poll_readable_multishot_round_trip,
)
from test_uring_reactor import (
    test_cancel_poll_terminates_multishot as test_uring_reactor__test_cancel_poll_terminates_multishot,
)
from test_uring_reactor import (
    test_use_uring_backend_consistent_with_availability as test_uring_reactor__test_use_uring_backend_consistent_with_availability,
)
from test_uring_reactor import (
    test_use_uring_backend_respects_disable_env as test_uring_reactor__test_use_uring_backend_respects_disable_env,
)
from test_uring_reactor import (
    test_buffer_ring_recv_round_trip as test_uring_reactor__test_buffer_ring_recv_round_trip,
)
from test_uring_reactor import (
    test_register_pbuf_ring_recv_round_trip as test_uring_reactor__test_register_pbuf_ring_recv_round_trip,
)
from test_uring_reactor import (
    test_register_pbuf_ring_multishot_continues as test_uring_reactor__test_register_pbuf_ring_multishot_continues,
)
from test_watchdog import (
    test_watchdog_flips_cell_on_deadline as test_watchdog__test_watchdog_flips_cell_on_deadline,
)
from test_watchdog import (
    test_watchdog_disarm_prevents_flip as test_watchdog__test_watchdog_disarm_prevents_flip,
)


def main() raises:
    var suite = TestSuite()
    # tests/runtime/test_buffer_pool.mojo
    suite.test[test_buffer_pool__test_size_for_rounds_up_to_size_class]()
    suite.test[
        test_buffer_pool__test_size_for_oversize_returns_caller_request_verbatim
    ]()
    suite.test[
        test_buffer_pool__test_handle_for_class_reserves_size_class_capacity
    ]()
    suite.test[test_buffer_pool__test_handle_reset_preserves_capacity]()
    suite.test[test_buffer_pool__test_pool_default_class_capacity_is_eight]()
    suite.test[test_buffer_pool__test_pool_with_class_capacity_factory]()
    suite.test[
        test_buffer_pool__test_pool_with_class_capacity_clamps_minimum_to_one
    ]()
    suite.test[
        test_buffer_pool__test_pool_acquire_from_empty_constructs_fresh_class_0
    ]()
    suite.test[
        test_buffer_pool__test_pool_acquire_dispatches_to_correct_class
    ]()
    suite.test[test_buffer_pool__test_pool_acquire_oversize_bypasses_pool]()
    suite.test[
        test_buffer_pool__test_pool_release_oversize_does_not_grow_any_bucket
    ]()
    suite.test[
        test_buffer_pool__test_pool_release_then_acquire_recycles_capacity
    ]()
    suite.test[
        test_buffer_pool__test_pool_release_past_class_capacity_drops_extras
    ]()
    suite.test[test_buffer_pool__test_pool_buckets_are_independent]()
    suite.test[
        test_buffer_pool__test_pool_acquire_release_acquire_lifo_within_class
    ]()
    suite.test[test_buffer_pool__test_pool_size_accessor_handles_out_of_range]()
    suite.test[
        test_buffer_pool__test_pool_release_with_invalid_class_index_drops_silently
    ]()
    # tests/runtime/test_compact_read_buf.mojo
    suite.test[test_compact_read_buf__test_drop_zero_keeps_full_buffer]()
    suite.test[test_compact_read_buf__test_drop_one_shifts_remaining]()
    suite.test[test_compact_read_buf__test_drop_prefix_keeps_trailing]()
    suite.test[test_compact_read_buf__test_drop_all_clears_buffer]()
    suite.test[test_compact_read_buf__test_drop_more_than_len_clears_buffer]()
    suite.test[test_compact_read_buf__test_drop_from_empty_is_noop]()
    suite.test[
        test_compact_read_buf__test_drop_long_buffer_preserves_byte_order
    ]()
    # tests/runtime/test_date_cache.mojo
    suite.test[test_date_cache__test_cache_primes_on_construction]()
    suite.test[test_date_cache__test_cache_layout_imf_fixdate_shape]()
    suite.test[test_date_cache__test_weekday_in_known_set]()
    suite.test[test_date_cache__test_month_in_known_set]()
    suite.test[test_date_cache__test_year_at_or_after_2026]()
    suite.test[test_date_cache__test_hour_minute_second_in_range]()
    suite.test[test_date_cache__test_refresh_is_noop_within_same_second]()
    suite.test[test_date_cache__test_refresh_advances_after_one_second]()
    suite.test[test_date_cache__test_current_bytes_and_string_agree]()
    suite.test[test_date_cache__test_format_known_unix_seconds]()
    suite.test[test_date_cache__test_format_y2038_cusp]()
    suite.test[test_date_cache__test_format_distant_future]()
    suite.test[test_date_cache__test_format_leap_day_2024]()
    suite.test[test_date_cache__test_format_unix_epoch]()
    # tests/runtime/test_io_uring.mojo
    suite.test[test_io_uring__test_syscall_numbers_match_linux_abi]()
    suite.test[
        test_io_uring__test_io_uring_params_empty_factory_zeroes_all_fields
    ]()
    suite.test[test_io_uring__test_is_io_uring_available_returns_bool]()
    suite.test[test_io_uring__test_is_io_uring_available_false_on_non_linux]()
    suite.test[test_io_uring__test_setup_and_teardown_a_ring_when_available]()
    suite.test[test_io_uring__test_setup_returns_features_flags]()
    suite.test[test_io_uring__test_setup_rounds_entries_up_to_power_of_two]()
    suite.test[test_io_uring__test_multiple_rings_are_independent]()
    suite.test[test_io_uring__test_setup_flags_zero_default_works]()
    suite.test[test_io_uring__test_setup_flag_coop_taskrun_accepted_or_einval]()
    suite.test[
        test_io_uring__test_setup_flag_combined_bufring_recipe_accepted_or_einval
    ]()
    # tests/runtime/test_io_uring_driver.mojo
    suite.test[test_io_uring_driver__test_driver_construction_succeeds]()
    suite.test[test_io_uring_driver__test_fresh_driver_has_no_pending_cqes]()
    suite.test[test_io_uring_driver__test_nop_round_trip_returns_user_data]()
    suite.test[
        test_io_uring_driver__test_multi_nop_round_trip_preserves_order
    ]()
    suite.test[test_io_uring_driver__test_reap_cqe_drains_then_returns_none]()
    suite.test[test_io_uring_driver__test_next_sqe_advances_sequentially]()
    # tests/runtime/test_io_uring_multishot_accept.mojo
    suite.test[
        test_io_uring_multishot_accept__test_multishot_accept_round_trip
    ]()
    # tests/runtime/test_iovec.mojo
    suite.test[test_iovec__test_iovec_size_for_returns_16_per_cell]()
    suite.test[test_iovec__test_iovec_count_matches_constructor_arg]()
    suite.test[test_iovec__test_iovec_set_then_read_back_round_trip]()
    suite.test[test_iovec__test_iovec_unset_cells_default_to_null_zero]()
    suite.test[test_iovec__test_iovec_set_overwrites_previous_value]()
    suite.test[test_iovec__test_writev_delivers_concatenated_bytes_to_peer]()
    suite.test[test_iovec__test_writev_with_zero_length_cells_skips_them]()
    suite.test[test_iovec__test_writev_single_cell_matches_send_semantics]()
    suite.test[test_iovec__test_writev_buf_all_zeroes_consumed_cells]()
    # tests/runtime/test_libc_time.mojo
    suite.test[test_libc_time__test_usleep_small_returns_zero]()
    suite.test[test_libc_time__test_usleep_zero_is_noop]()
    suite.test[test_libc_time__test_usleep_negative_is_noop]()
    suite.test[test_libc_time__test_usleep_10ms_takes_at_least_5ms]()
    suite.test[test_libc_time__test_nanosleep_zero_is_noop]()
    suite.test[test_libc_time__test_nanosleep_negative_is_noop]()
    suite.test[test_libc_time__test_nanosleep_50ms_within_budget]()
    suite.test[test_libc_time__test_nanosleep_200ms_takes_at_least_100ms]()
    suite.test[test_libc_time__test_monotonic_is_non_decreasing]()
    suite.test[test_libc_time__test_monotonic_tracks_a_sleep]()
    suite.test[test_libc_time__test_hundred_one_ms_sleeps_within_2000ms]()
    # tests/runtime/test_pool.mojo
    suite.test[test_pool__test_alloc_returns_nonzero_address]()
    suite.test[test_pool__test_alloc_then_get_ptr_reads_value]()
    suite.test[test_pool__test_free_calls_destructor_exactly_once]()
    suite.test[test_pool__test_free_zero_is_noop]()
    suite.test[test_pool__test_alloc_free_cycle_no_leak]()
    suite.test[test_pool__test_thousand_cycles]()
    suite.test[test_pool__test_pool_with_string_field]()
    # tests/runtime/test_reactor.mojo
    suite.test[test_reactor__test_create_and_destroy]()
    suite.test[test_reactor__test_many_create_destroy_no_leak]()
    suite.test[test_reactor__test_register_then_is_registered]()
    suite.test[test_reactor__test_register_rejects_wakeup_token]()
    suite.test[test_reactor__test_register_rejects_empty_interest]()
    suite.test[test_reactor__test_register_same_fd_twice_raises]()
    suite.test[test_reactor__test_unregister_unknown_fd_raises]()
    suite.test[test_reactor__test_unregister_after_close_succeeds]()
    suite.test[test_reactor__test_unregister_after_close_frees_fd_for_reuse]()
    suite.test[test_reactor__test_modify_unknown_fd_raises]()
    suite.test[test_reactor__test_modify_from_read_to_write]()
    suite.test[test_reactor__test_poll_timeout_zero_returns_empty]()
    suite.test[test_reactor__test_poll_timeout_short_returns_empty]()
    suite.test[test_reactor__test_poll_detects_readable_on_writable_peer]()
    suite.test[test_reactor__test_poll_detects_writable]()
    suite.test[test_reactor__test_poll_detects_hup_on_peer_close]()
    suite.test[test_reactor__test_poll_multiple_fds]()
    suite.test[test_reactor__test_wakeup_breaks_blocking_poll]()
    suite.test[test_reactor__test_wakeup_does_not_appear_without_call]()
    suite.test[test_reactor__test_wakeup_after_drain_can_fire_again]()
    suite.test[test_reactor__test_poll_reuses_event_buffer_across_calls]()
    suite.test[test_reactor__test_poll_honors_max_events_cap]()
    suite.test[test_reactor__test_event_flag_helpers]()
    # tests/runtime/test_reactor_shutdown.mojo
    suite.test[
        test_reactor_shutdown__test_server_config_shutdown_timeout_default
    ]()
    suite.test[
        test_reactor_shutdown__test_server_config_shutdown_timeout_custom
    ]()
    suite.test[test_reactor_shutdown__test_server_close_is_idempotent]()
    suite.test[test_reactor_shutdown__test_server_close_sets_stopping_flag]()
    suite.test[test_reactor_shutdown__test_server_rebind_after_close]()
    suite.test[test_reactor_shutdown__test_server_bind_same_port_twice_fails]()
    suite.test[
        test_reactor_shutdown__test_server_config_is_copyable_for_struct_literal_reuse
    ]()
    # tests/runtime/test_safety_asserts.mojo
    suite.test[test_safety_asserts__test_iovec_set_at_every_legal_index]()
    suite.test[
        test_safety_asserts__test_iovec_set_zero_len_with_null_ptr_is_legal
    ]()
    suite.test[
        test_safety_asserts__test_iovec_set_nonzero_len_with_real_ptr_is_legal
    ]()
    suite.test[
        test_safety_asserts__test_buffer_pool_acquire_at_each_size_class
    ]()
    suite.test[
        test_safety_asserts__test_buffer_pool_acquire_zero_min_capacity_is_legal
    ]()
    suite.test[
        test_safety_asserts__test_response_pool_with_capacity_clamps_zero_input
    ]()
    suite.test[
        test_safety_asserts__test_response_pool_acquire_release_round_trip
    ]()
    suite.test[test_safety_asserts__test_date_cache_construct_and_refresh]()
    suite.test[
        test_safety_asserts__test_date_cache_two_digit_writes_cover_full_range
    ]()
    suite.test[
        test_safety_asserts__test_huffman_encode_byte_range_assert_holds
    ]()
    suite.test[test_safety_asserts__test_huffman_decode_empty_input_is_legal]()
    suite.test[test_safety_asserts__test_simd_memmem_empty_haystack_no_assert]()
    suite.test[
        test_safety_asserts__test_simd_percent_decode_empty_input_no_assert
    ]()
    suite.test[
        test_safety_asserts__test_simd_cookie_scan_empty_input_no_assert
    ]()
    suite.test[test_safety_asserts__test_io_uring_feature_detection_no_assert]()
    # tests/runtime/test_scheduler.mojo
    suite.test[test_scheduler__test_default_worker_count_positive]()
    suite.test[test_scheduler__test_scheduler_start_and_shutdown_n2]()
    suite.test[test_scheduler__test_scheduler_start_and_shutdown_n4]()
    suite.test[
        test_scheduler__test_scheduler_drain_returns_per_worker_reports
    ]()
    suite.test[test_scheduler__test_scheduler_drain_zero_timeout_is_hard_stop]()
    suite.test[test_scheduler__test_scheduler_shutdown_idempotent]()
    suite.test[test_scheduler__test_scheduler_multiple_start_cycles]()
    suite.test[test_scheduler__test_scheduler_pin_cores_flag_default_no_crash]()
    # tests/runtime/test_syscall_ffi.mojo
    suite.test[test_syscall_ffi__test_epoll_constants_distinct_bits]()
    suite.test[test_syscall_ffi__test_epoll_ctl_op_constants]()
    suite.test[test_syscall_ffi__test_epoll_event_size_matches_arch]()
    suite.test[test_syscall_ffi__test_epoll_event_set_and_read_back]()
    suite.test[test_syscall_ffi__test_epoll_create1_and_close]()
    suite.test[test_syscall_ffi__test_epoll_create1_with_cloexec]()
    suite.test[test_syscall_ffi__test_epoll_ctl_add_then_del_ok]()
    suite.test[test_syscall_ffi__test_epoll_wait_timeout_zero_returns_empty]()
    suite.test[test_syscall_ffi__test_epoll_wait_detects_readable]()
    suite.test[test_syscall_ffi__test_kqueue_filter_constants]()
    suite.test[test_syscall_ffi__test_kqueue_flag_constants_distinct_bits]()
    suite.test[test_syscall_ffi__test_kevent_size_is_32]()
    suite.test[
        test_syscall_ffi__test_kevent_set_and_read_back_positive_fields
    ]()
    suite.test[test_syscall_ffi__test_kevent_set_filter_negative_roundtrip]()
    suite.test[test_syscall_ffi__test_kqueue_create_and_close]()
    suite.test[
        test_syscall_ffi__test_kevent_zero_changes_zero_events_timeout_returns_zero
    ]()
    suite.test[test_syscall_ffi__test_kevent_detects_readable]()
    suite.test[test_syscall_ffi__test_eventfd_write_then_read_counts]()
    suite.test[test_syscall_ffi__test_pipe_round_trip_byte]()
    suite.test[
        test_syscall_ffi__test_epoll_wait_on_invalid_fd_returns_negative
    ]()
    suite.test[test_syscall_ffi__test_kevent_on_invalid_fd_returns_negative]()
    suite.test[test_syscall_ffi__test_set_nonblocking_toggle_does_not_raise]()
    # tests/runtime/test_thread_ffi.mojo
    suite.test[test_thread_ffi__test_num_cpus_at_least_one]()
    suite.test[test_thread_ffi__test_num_cpus_reasonable]()
    suite.test[test_thread_ffi__test_current_thread_id_nonzero]()
    suite.test[test_thread_ffi__test_spawn_join_noop]()
    suite.test[test_thread_ffi__test_spawn_writes_argument]()
    suite.test[test_thread_ffi__test_spawn_multiple_threads]()
    suite.test[test_thread_ffi__test_pin_to_cpu0_after_spawn]()
    suite.test[test_thread_ffi__test_pin_to_cpu_min_of_available]()
    suite.test[test_thread_ffi__test_many_spawn_join_cycles]()
    suite.test[test_thread_ffi__test_thread_id_unique_across_workers]()
    # tests/runtime/test_timer_wheel.mojo
    suite.test[test_timer_wheel__test_schedule_returns_unique_ids]()
    suite.test[test_timer_wheel__test_empty_wheel_active_count_zero]()
    suite.test[test_timer_wheel__test_schedule_increments_active_count]()
    suite.test[test_timer_wheel__test_timer_fires_after_correct_delay]()
    suite.test[test_timer_wheel__test_multiple_timers_fire_in_order]()
    suite.test[test_timer_wheel__test_immediate_timer_fires_next_advance]()
    suite.test[test_timer_wheel__test_zero_advance_fires_nothing]()
    suite.test[test_timer_wheel__test_cancel_is_idempotent]()
    suite.test[test_timer_wheel__test_cancel_unknown_id_returns_false]()
    suite.test[test_timer_wheel__test_cancelled_timer_does_not_fire]()
    suite.test[
        test_timer_wheel__test_timer_past_one_rotation_fires_eventually
    ]()
    suite.test[test_timer_wheel__test_timer_at_exactly_512ms_fires]()
    suite.test[test_timer_wheel__test_multiple_rotations_still_fire]()
    suite.test[test_timer_wheel__test_1000_short_timers_all_fire]()
    suite.test[test_timer_wheel__test_many_cancels_dont_leak]()
    suite.test[test_timer_wheel__test_now_ms_reflects_advance]()
    suite.test[test_timer_wheel__test_next_fire_ms_returns_earliest]()
    suite.test[test_timer_wheel__test_next_fire_ms_empty_returns_sentinel]()
    suite.test[
        test_timer_wheel__test_next_fire_ms_overflow_only_returns_rotation
    ]()
    suite.test[test_timer_wheel__test_next_fire_ms_recovers_after_advance]()
    suite.test[test_timer_wheel__test_next_fire_ms_cancel_is_lower_bound]()
    # tests/runtime/test_uring_reactor.mojo
    suite.test[test_uring_reactor__test_pack_unpack_round_trip]()
    suite.test[test_uring_reactor__test_pack_op_does_not_clobber_conn_id]()
    suite.test[test_uring_reactor__test_construction_succeeds]()
    suite.test[test_uring_reactor__test_idle_poll_returns_zero]()
    suite.test[test_uring_reactor__test_arm_listener_multishot_round_trip]()
    suite.test[test_uring_reactor__test_submit_send_round_trip]()
    suite.test[test_uring_reactor__test_wakeup_releases_blocking_poll]()
    suite.test[
        test_uring_reactor__test_arm_poll_readable_multishot_round_trip
    ]()
    suite.test[test_uring_reactor__test_cancel_poll_terminates_multishot]()
    suite.test[
        test_uring_reactor__test_use_uring_backend_consistent_with_availability
    ]()
    suite.test[
        test_uring_reactor__test_use_uring_backend_respects_disable_env
    ]()
    suite.test[test_uring_reactor__test_buffer_ring_recv_round_trip]()
    suite.test[test_uring_reactor__test_register_pbuf_ring_recv_round_trip]()
    suite.test[
        test_uring_reactor__test_register_pbuf_ring_multishot_continues
    ]()
    # tests/runtime/test_watchdog.mojo
    suite.test[test_watchdog__test_watchdog_flips_cell_on_deadline]()
    suite.test[test_watchdog__test_watchdog_disarm_prevents_flip]()
    suite^.run()
