"""GENERATED by tests/tools/gen_test_aggregates.py -- do not edit.

Aggregates the 13 test files of ``tests/http2/`` into one compiled
binary so the 13 separate compiler invocations become one. Run it with
``mojo -I . -I tests/http2`` (see tests/tools/run_test_aggregates.sh).

Regenerate with ``python3 tests/tools/gen_test_aggregates.py``; CI fails if this
file is out of date with the tree.
"""

from std.testing import TestSuite
from test_h2_client_conn import (
    test_preface_emitted_on_construction as test_h2_client_conn__test_preface_emitted_on_construction,
)
from test_h2_client_conn import (
    test_settings_exchange_roundtrip as test_h2_client_conn__test_settings_exchange_roundtrip,
)
from test_h2_client_conn import (
    test_get_request_response_roundtrip as test_h2_client_conn__test_get_request_response_roundtrip,
)
from test_h2_client_conn import (
    test_post_request_with_body as test_h2_client_conn__test_post_request_with_body,
)
from test_h2_client_conn import (
    test_two_sequential_requests_share_connection as test_h2_client_conn__test_two_sequential_requests_share_connection,
)
from test_h2_client_conn import (
    test_response_with_chunked_body as test_h2_client_conn__test_response_with_chunked_body,
)
from test_h2_client_conn import (
    test_rst_stream_surfaced as test_h2_client_conn__test_rst_stream_surfaced,
)
from test_h2_client_conn import (
    test_goaway_received_flag as test_h2_client_conn__test_goaway_received_flag,
)
from test_h2_client_conn import (
    test_push_promise_rejected_by_rst_stream as test_h2_client_conn__test_push_promise_rejected_by_rst_stream,
)
from test_h2_client_conn import (
    test_oversized_headers_split_across_continuation as test_h2_client_conn__test_oversized_headers_split_across_continuation,
)
from test_h2_client_conn import (
    test_pending_body_drains_on_window_update as test_h2_client_conn__test_pending_body_drains_on_window_update,
)
from test_h2_config import (
    test_default_config_matches_rfc_and_v0_6_shape as test_h2_config__test_default_config_matches_rfc_and_v0_6_shape,
)
from test_h2_config import (
    test_default_config_validates as test_h2_config__test_default_config_validates,
)
from test_h2_config import (
    test_with_config_default_emits_extra_max_header_list_size as test_h2_config__test_with_config_default_emits_extra_max_header_list_size,
)
from test_h2_config import (
    test_with_config_zero_header_list_byte_matches_h2connection as test_h2_config__test_with_config_zero_header_list_byte_matches_h2connection,
)
from test_h2_config import (
    test_validate_rejects_negative_max_concurrent_streams as test_h2_config__test_validate_rejects_negative_max_concurrent_streams,
)
from test_h2_config import (
    test_validate_rejects_initial_window_size_overflow as test_h2_config__test_validate_rejects_initial_window_size_overflow,
)
from test_h2_config import (
    test_validate_accepts_initial_window_size_at_boundary as test_h2_config__test_validate_accepts_initial_window_size_at_boundary,
)
from test_h2_config import (
    test_validate_rejects_max_frame_size_below_floor as test_h2_config__test_validate_rejects_max_frame_size_below_floor,
)
from test_h2_config import (
    test_validate_accepts_max_frame_size_at_floor as test_h2_config__test_validate_accepts_max_frame_size_at_floor,
)
from test_h2_config import (
    test_validate_rejects_max_frame_size_above_ceiling as test_h2_config__test_validate_rejects_max_frame_size_above_ceiling,
)
from test_h2_config import (
    test_validate_accepts_max_frame_size_at_ceiling as test_h2_config__test_validate_accepts_max_frame_size_at_ceiling,
)
from test_h2_config import (
    test_validate_rejects_negative_max_header_list_size as test_h2_config__test_validate_rejects_negative_max_header_list_size,
)
from test_h2_config import (
    test_validate_rejects_negative_header_table_size as test_h2_config__test_validate_rejects_negative_header_table_size,
)
from test_h2_config import (
    test_with_config_propagates_to_connection_fields as test_h2_config__test_with_config_propagates_to_connection_fields,
)
from test_h2_config import (
    test_with_config_full_emits_all_non_default_settings as test_h2_config__test_with_config_full_emits_all_non_default_settings,
)
from test_h2_config import (
    test_with_config_validates_inputs as test_h2_config__test_with_config_validates_inputs,
)
from test_h2_config import (
    test_request_body_limit_resets_only_oversized_stream as test_h2_config__test_request_body_limit_resets_only_oversized_stream,
)
from test_h2_config import (
    test_request_body_limit_rejects_negative_config as test_h2_config__test_request_body_limit_rejects_negative_config,
)
from test_h2_conn_handle import (
    test_h2_conn_handle_init_smoke as test_h2_conn_handle__test_h2_conn_handle_init_smoke,
)
from test_h2_conn_handle import (
    test_h2_conn_handle_get_round_trip as test_h2_conn_handle__test_h2_conn_handle_get_round_trip,
)
from test_h2_conn_handle import (
    test_h2_conn_handle_concurrent_streaming as test_h2_conn_handle__test_h2_conn_handle_concurrent_streaming,
)
from test_h2_extended_connect import (
    test_settings_enable_connect_protocol_off_by_default as test_h2_extended_connect__test_settings_enable_connect_protocol_off_by_default,
)
from test_h2_extended_connect import (
    test_settings_enable_connect_protocol_when_opted_in as test_h2_extended_connect__test_settings_enable_connect_protocol_when_opted_in,
)
from test_h2_extended_connect import (
    test_extended_connect_headers_landed_on_stream as test_h2_extended_connect__test_extended_connect_headers_landed_on_stream,
)
from test_h2_extended_connect import (
    test_extended_connect_protocol_empty_for_plain_get as test_h2_extended_connect__test_extended_connect_protocol_empty_for_plain_get,
)
from test_h2_extended_connect import (
    test_peer_enable_connect_protocol_latched_on_settings_recv as test_h2_extended_connect__test_peer_enable_connect_protocol_latched_on_settings_recv,
)
from test_h2_frame import (
    test_frame_type_codes as test_h2_frame__test_frame_type_codes,
)
from test_h2_frame import (
    test_frame_flag_constants as test_h2_frame__test_frame_flag_constants,
)
from test_h2_frame import (
    test_preface_constant as test_h2_frame__test_preface_constant,
)
from test_h2_frame import (
    test_empty_payload_roundtrip as test_h2_frame__test_empty_payload_roundtrip,
)
from test_h2_frame import (
    test_payload_roundtrip as test_h2_frame__test_payload_roundtrip,
)
from test_h2_frame import (
    test_truncated_returns_none as test_h2_frame__test_truncated_returns_none,
)
from test_h2_frame import (
    test_length_overflow_raises as test_h2_frame__test_length_overflow_raises,
)
from test_h2_frame import (
    test_reserved_bit_masked_on_parse as test_h2_frame__test_reserved_bit_masked_on_parse,
)
from test_h2_frame import (
    test_default_frame_size_constant as test_h2_frame__test_default_frame_size_constant,
)
from test_h2_hpack import (
    test_decode_integer_short as test_h2_hpack__test_decode_integer_short,
)
from test_h2_hpack import (
    test_rfc_7541_c1_5bit_1337 as test_h2_hpack__test_rfc_7541_c1_5bit_1337,
)
from test_h2_hpack import (
    test_integer_roundtrip_boundaries as test_h2_hpack__test_integer_roundtrip_boundaries,
)
from test_h2_hpack import (
    test_integer_truncated_raises as test_h2_hpack__test_integer_truncated_raises,
)
from test_h2_hpack import (
    test_decode_indexed_static as test_h2_hpack__test_decode_indexed_static,
)
from test_h2_hpack import (
    test_decode_literal_with_indexing_grows_dynamic as test_h2_hpack__test_decode_literal_with_indexing_grows_dynamic,
)
from test_h2_hpack import (
    test_decode_literal_without_indexing as test_h2_hpack__test_decode_literal_without_indexing,
)
from test_h2_hpack import (
    test_decode_huffman_raises_when_disabled as test_h2_hpack__test_decode_huffman_raises_when_disabled,
)
from test_h2_hpack import (
    test_decode_huffman_appendix_c4_www_example_com as test_h2_hpack__test_decode_huffman_appendix_c4_www_example_com,
)
from test_h2_hpack import (
    test_encoder_decoder_roundtrip_with_huffman as test_h2_hpack__test_encoder_decoder_roundtrip_with_huffman,
)
from test_h2_hpack import (
    test_encoder_huffman_picks_shorter_form as test_h2_hpack__test_encoder_huffman_picks_shorter_form,
)
from test_h2_hpack import (
    test_decode_dynamic_size_update_shrinks as test_h2_hpack__test_decode_dynamic_size_update_shrinks,
)
from test_h2_hpack import (
    test_decode_size_update_above_cap_raises as test_h2_hpack__test_decode_size_update_above_cap_raises,
)
from test_h2_hpack import (
    test_encoder_decoder_roundtrip as test_h2_hpack__test_encoder_decoder_roundtrip,
)
from test_h2_hpack import (
    test_encoder_status_uses_static_name_index as test_h2_hpack__test_encoder_status_uses_static_name_index,
)
from test_h2_parked_response import (
    test_parked_response_is_not_redispatched as test_h2_parked_response__test_parked_response_is_not_redispatched,
)
from test_h2_parked_response import (
    test_parked_response_sends_one_head as test_h2_parked_response__test_parked_response_sends_one_head,
)
from test_h2_parked_response import (
    test_whole_body_survives_the_park as test_h2_parked_response__test_whole_body_survives_the_park,
)
from test_h2_per_stream_cancel import (
    test_rst_stream_flips_only_target_cell as test_h2_per_stream_cancel__test_rst_stream_flips_only_target_cell,
)
from test_h2_per_stream_cancel import (
    test_concurrent_streams_isolated as test_h2_per_stream_cancel__test_concurrent_streams_isolated,
)
from test_h2_per_stream_cancel import (
    test_goaway_flips_all_cells as test_h2_per_stream_cancel__test_goaway_flips_all_cells,
)
from test_h2_per_stream_cancel import (
    test_drain_flips_all_cells_with_shutdown_reason as test_h2_per_stream_cancel__test_drain_flips_all_cells_with_shutdown_reason,
)
from test_h2_per_stream_cancel import (
    test_cell_freed_after_dispatch_is_idempotent as test_h2_per_stream_cancel__test_cell_freed_after_dispatch_is_idempotent,
)
from test_h2_per_stream_cancel import (
    test_on_readable_cancel_dispatches_through_cancel_handler as test_h2_per_stream_cancel__test_on_readable_cancel_dispatches_through_cancel_handler,
)
from test_h2_server import (
    test_alpn_dispatch as test_h2_server__test_alpn_dispatch,
)
from test_h2_server import (
    test_h2c_upgrade_detection as test_h2_server__test_h2c_upgrade_detection,
)
from test_h2_server import (
    test_preface_only_emits_settings as test_h2_server__test_preface_only_emits_settings,
)
from test_h2_server import (
    test_bad_preface_goaways as test_h2_server__test_bad_preface_goaways,
)
from test_h2_server import (
    test_request_round_trip as test_h2_server__test_request_round_trip,
)
from test_h2_server import (
    test_stream_response_incremental_frames as test_h2_server__test_stream_response_incremental_frames,
)
from test_h2_server import (
    test_stream_response_no_trailers_ends_with_empty_data as test_h2_server__test_stream_response_no_trailers_ends_with_empty_data,
)
from test_h2_server import (
    test_stream_data_bounded_by_send_window as test_h2_server__test_stream_data_bounded_by_send_window,
)
from test_h2_server import (
    test_partial_feed_buffers_frames as test_h2_server__test_partial_feed_buffers_frames,
)
from test_h2_server_handler import (
    test_h2_server_simple_handler as test_h2_server_handler__test_h2_server_simple_handler,
)
from test_h2_server_handler import (
    test_h2_server_router_dispatch as test_h2_server_handler__test_h2_server_router_dispatch,
)
from test_h2_server_handler import (
    test_h2_server_request_body_round_trip as test_h2_server_handler__test_h2_server_request_body_round_trip,
)
from test_h2_server_handler import (
    test_h2_server_request_headers_visible as test_h2_server_handler__test_h2_server_request_headers_visible,
)
from test_h2_server_handler import (
    test_h2_server_streaming_response as test_h2_server_handler__test_h2_server_streaming_response,
)
from test_h2_state import (
    test_initial_settings_is_one_setting as test_h2_state__test_initial_settings_is_one_setting,
)
from test_h2_state import (
    test_inbound_settings_acks as test_h2_state__test_inbound_settings_acks,
)
from test_h2_state import (
    test_settings_ack_recorded as test_h2_state__test_settings_ack_recorded,
)
from test_h2_state import (
    test_headers_on_stream_0_raises as test_h2_state__test_headers_on_stream_0_raises,
)
from test_h2_state import (
    test_headers_end_stream_transitions_to_half_closed_remote as test_h2_state__test_headers_end_stream_transitions_to_half_closed_remote,
)
from test_h2_state import (
    test_data_appends_and_emits_window_update as test_h2_state__test_data_appends_and_emits_window_update,
)
from test_h2_state import (
    test_window_update_adjusts_send_window as test_h2_state__test_window_update_adjusts_send_window,
)
from test_h2_state import (
    test_ping_auto_replies_with_ack as test_h2_state__test_ping_auto_replies_with_ack,
)
from test_h2_state import (
    test_make_response_no_body_sets_end_stream_on_headers as test_h2_state__test_make_response_no_body_sets_end_stream_on_headers,
)
from test_h2_state import (
    test_make_response_with_body_emits_two_frames as test_h2_state__test_make_response_with_body_emits_two_frames,
)
from test_h2_state import (
    test_oversized_header_list_rsts_enhance_your_calm as test_h2_state__test_oversized_header_list_rsts_enhance_your_calm,
)
from test_h2_state import (
    test_continuation_flood_rsts as test_h2_state__test_continuation_flood_rsts,
)
from test_h2_state import (
    test_rst_flood_triggers_goaway as test_h2_state__test_rst_flood_triggers_goaway,
)
from test_h2_state import (
    test_priority_accepted_and_ignored as test_h2_state__test_priority_accepted_and_ignored,
)
from test_h2_streaming_state import (
    test_h2_informationals_and_length_survives_body_drains as test_h2_streaming_state__test_h2_informationals_and_length_survives_body_drains,
)
from test_h2_streaming_state import (
    test_h2_head_metadata_does_not_require_data as test_h2_streaming_state__test_h2_head_metadata_does_not_require_data,
)
from test_h2_streaming_state import (
    test_h2_truncated_content_length_is_a_stream_error as test_h2_streaming_state__test_h2_truncated_content_length_is_a_stream_error,
)
from test_h2_streaming_state import (
    test_h2_streaming_credit_follows_body_drains as test_h2_streaming_state__test_h2_streaming_credit_follows_body_drains,
)
from test_h2_streaming_state import (
    test_h2_undrained_stream_cannot_exceed_receive_window as test_h2_streaming_state__test_h2_undrained_stream_cannot_exceed_receive_window,
)
from test_h2_streaming_state import (
    test_h2_rejects_data_before_final_response_headers as test_h2_streaming_state__test_h2_rejects_data_before_final_response_headers,
)
from test_h2_streaming_state import (
    test_h2_no_error_reset_only_preserves_complete_response as test_h2_streaming_state__test_h2_no_error_reset_only_preserves_complete_response,
)
from test_h2_streaming_state import (
    test_h2_window_update_before_rejection_does_not_resume_upload as test_h2_streaming_state__test_h2_window_update_before_rejection_does_not_resume_upload,
)
from test_h2_streaming_state import (
    test_h2_malformed_response_does_not_kill_sibling_streams as test_h2_streaming_state__test_h2_malformed_response_does_not_kill_sibling_streams,
)
from test_h2_streaming_state import (
    test_h2_goaway_marks_unprocessed_streams_refused as test_h2_streaming_state__test_h2_goaway_marks_unprocessed_streams_refused,
)
from test_stream_slab import (
    test_empty_slab_is_empty as test_stream_slab__test_empty_slab_is_empty,
)
from test_stream_slab import (
    test_fast_tier_roundtrip as test_stream_slab__test_fast_tier_roundtrip,
)
from test_stream_slab import (
    test_overflow_tier_roundtrip as test_stream_slab__test_overflow_tier_roundtrip,
)
from test_stream_slab import (
    test_both_tiers_coexist as test_stream_slab__test_both_tiers_coexist,
)
from test_stream_slab import (
    test_overwrite_does_not_double_count as test_stream_slab__test_overwrite_does_not_double_count,
)
from test_stream_slab import (
    test_getitem_on_missing_raises as test_stream_slab__test_getitem_on_missing_raises,
)
from test_stream_slab import (
    test_get_returns_optional as test_stream_slab__test_get_returns_optional,
)
from test_stream_slab import (
    test_pop_clears_slot as test_stream_slab__test_pop_clears_slot,
)
from test_stream_slab import (
    test_items_lists_everything as test_stream_slab__test_items_lists_everything,
)
from test_stream_slab import (
    test_stress_roundtrip as test_stream_slab__test_stress_roundtrip,
)


def main() raises:
    var suite = TestSuite()
    # tests/http2/test_h2_client_conn.mojo
    suite.test[test_h2_client_conn__test_preface_emitted_on_construction]()
    suite.test[test_h2_client_conn__test_settings_exchange_roundtrip]()
    suite.test[test_h2_client_conn__test_get_request_response_roundtrip]()
    suite.test[test_h2_client_conn__test_post_request_with_body]()
    suite.test[
        test_h2_client_conn__test_two_sequential_requests_share_connection
    ]()
    suite.test[test_h2_client_conn__test_response_with_chunked_body]()
    suite.test[test_h2_client_conn__test_rst_stream_surfaced]()
    suite.test[test_h2_client_conn__test_goaway_received_flag]()
    suite.test[test_h2_client_conn__test_push_promise_rejected_by_rst_stream]()
    suite.test[
        test_h2_client_conn__test_oversized_headers_split_across_continuation
    ]()
    suite.test[test_h2_client_conn__test_pending_body_drains_on_window_update]()
    # tests/http2/test_h2_config.mojo
    suite.test[test_h2_config__test_default_config_matches_rfc_and_v0_6_shape]()
    suite.test[test_h2_config__test_default_config_validates]()
    suite.test[
        test_h2_config__test_with_config_default_emits_extra_max_header_list_size
    ]()
    suite.test[
        test_h2_config__test_with_config_zero_header_list_byte_matches_h2connection
    ]()
    suite.test[
        test_h2_config__test_validate_rejects_negative_max_concurrent_streams
    ]()
    suite.test[
        test_h2_config__test_validate_rejects_initial_window_size_overflow
    ]()
    suite.test[
        test_h2_config__test_validate_accepts_initial_window_size_at_boundary
    ]()
    suite.test[
        test_h2_config__test_validate_rejects_max_frame_size_below_floor
    ]()
    suite.test[test_h2_config__test_validate_accepts_max_frame_size_at_floor]()
    suite.test[
        test_h2_config__test_validate_rejects_max_frame_size_above_ceiling
    ]()
    suite.test[
        test_h2_config__test_validate_accepts_max_frame_size_at_ceiling
    ]()
    suite.test[
        test_h2_config__test_validate_rejects_negative_max_header_list_size
    ]()
    suite.test[
        test_h2_config__test_validate_rejects_negative_header_table_size
    ]()
    suite.test[
        test_h2_config__test_with_config_propagates_to_connection_fields
    ]()
    suite.test[
        test_h2_config__test_with_config_full_emits_all_non_default_settings
    ]()
    suite.test[test_h2_config__test_with_config_validates_inputs]()
    suite.test[
        test_h2_config__test_request_body_limit_resets_only_oversized_stream
    ]()
    suite.test[
        test_h2_config__test_request_body_limit_rejects_negative_config
    ]()
    # tests/http2/test_h2_conn_handle.mojo
    suite.test[test_h2_conn_handle__test_h2_conn_handle_init_smoke]()
    suite.test[test_h2_conn_handle__test_h2_conn_handle_get_round_trip]()
    suite.test[test_h2_conn_handle__test_h2_conn_handle_concurrent_streaming]()
    # tests/http2/test_h2_extended_connect.mojo
    suite.test[
        test_h2_extended_connect__test_settings_enable_connect_protocol_off_by_default
    ]()
    suite.test[
        test_h2_extended_connect__test_settings_enable_connect_protocol_when_opted_in
    ]()
    suite.test[
        test_h2_extended_connect__test_extended_connect_headers_landed_on_stream
    ]()
    suite.test[
        test_h2_extended_connect__test_extended_connect_protocol_empty_for_plain_get
    ]()
    suite.test[
        test_h2_extended_connect__test_peer_enable_connect_protocol_latched_on_settings_recv
    ]()
    # tests/http2/test_h2_frame.mojo
    suite.test[test_h2_frame__test_frame_type_codes]()
    suite.test[test_h2_frame__test_frame_flag_constants]()
    suite.test[test_h2_frame__test_preface_constant]()
    suite.test[test_h2_frame__test_empty_payload_roundtrip]()
    suite.test[test_h2_frame__test_payload_roundtrip]()
    suite.test[test_h2_frame__test_truncated_returns_none]()
    suite.test[test_h2_frame__test_length_overflow_raises]()
    suite.test[test_h2_frame__test_reserved_bit_masked_on_parse]()
    suite.test[test_h2_frame__test_default_frame_size_constant]()
    # tests/http2/test_h2_hpack.mojo
    suite.test[test_h2_hpack__test_decode_integer_short]()
    suite.test[test_h2_hpack__test_rfc_7541_c1_5bit_1337]()
    suite.test[test_h2_hpack__test_integer_roundtrip_boundaries]()
    suite.test[test_h2_hpack__test_integer_truncated_raises]()
    suite.test[test_h2_hpack__test_decode_indexed_static]()
    suite.test[test_h2_hpack__test_decode_literal_with_indexing_grows_dynamic]()
    suite.test[test_h2_hpack__test_decode_literal_without_indexing]()
    suite.test[test_h2_hpack__test_decode_huffman_raises_when_disabled]()
    suite.test[test_h2_hpack__test_decode_huffman_appendix_c4_www_example_com]()
    suite.test[test_h2_hpack__test_encoder_decoder_roundtrip_with_huffman]()
    suite.test[test_h2_hpack__test_encoder_huffman_picks_shorter_form]()
    suite.test[test_h2_hpack__test_decode_dynamic_size_update_shrinks]()
    suite.test[test_h2_hpack__test_decode_size_update_above_cap_raises]()
    suite.test[test_h2_hpack__test_encoder_decoder_roundtrip]()
    suite.test[test_h2_hpack__test_encoder_status_uses_static_name_index]()
    # tests/http2/test_h2_parked_response.mojo
    suite.test[
        test_h2_parked_response__test_parked_response_is_not_redispatched
    ]()
    suite.test[test_h2_parked_response__test_parked_response_sends_one_head]()
    suite.test[test_h2_parked_response__test_whole_body_survives_the_park]()
    # tests/http2/test_h2_per_stream_cancel.mojo
    suite.test[
        test_h2_per_stream_cancel__test_rst_stream_flips_only_target_cell
    ]()
    suite.test[test_h2_per_stream_cancel__test_concurrent_streams_isolated]()
    suite.test[test_h2_per_stream_cancel__test_goaway_flips_all_cells]()
    suite.test[
        test_h2_per_stream_cancel__test_drain_flips_all_cells_with_shutdown_reason
    ]()
    suite.test[
        test_h2_per_stream_cancel__test_cell_freed_after_dispatch_is_idempotent
    ]()
    suite.test[
        test_h2_per_stream_cancel__test_on_readable_cancel_dispatches_through_cancel_handler
    ]()
    # tests/http2/test_h2_server.mojo
    suite.test[test_h2_server__test_alpn_dispatch]()
    suite.test[test_h2_server__test_h2c_upgrade_detection]()
    suite.test[test_h2_server__test_preface_only_emits_settings]()
    suite.test[test_h2_server__test_bad_preface_goaways]()
    suite.test[test_h2_server__test_request_round_trip]()
    suite.test[test_h2_server__test_stream_response_incremental_frames]()
    suite.test[
        test_h2_server__test_stream_response_no_trailers_ends_with_empty_data
    ]()
    suite.test[test_h2_server__test_stream_data_bounded_by_send_window]()
    suite.test[test_h2_server__test_partial_feed_buffers_frames]()
    # tests/http2/test_h2_server_handler.mojo
    suite.test[test_h2_server_handler__test_h2_server_simple_handler]()
    suite.test[test_h2_server_handler__test_h2_server_router_dispatch]()
    suite.test[test_h2_server_handler__test_h2_server_request_body_round_trip]()
    suite.test[test_h2_server_handler__test_h2_server_request_headers_visible]()
    suite.test[test_h2_server_handler__test_h2_server_streaming_response]()
    # tests/http2/test_h2_state.mojo
    suite.test[test_h2_state__test_initial_settings_is_one_setting]()
    suite.test[test_h2_state__test_inbound_settings_acks]()
    suite.test[test_h2_state__test_settings_ack_recorded]()
    suite.test[test_h2_state__test_headers_on_stream_0_raises]()
    suite.test[
        test_h2_state__test_headers_end_stream_transitions_to_half_closed_remote
    ]()
    suite.test[test_h2_state__test_data_appends_and_emits_window_update]()
    suite.test[test_h2_state__test_window_update_adjusts_send_window]()
    suite.test[test_h2_state__test_ping_auto_replies_with_ack]()
    suite.test[
        test_h2_state__test_make_response_no_body_sets_end_stream_on_headers
    ]()
    suite.test[test_h2_state__test_make_response_with_body_emits_two_frames]()
    suite.test[
        test_h2_state__test_oversized_header_list_rsts_enhance_your_calm
    ]()
    suite.test[test_h2_state__test_continuation_flood_rsts]()
    suite.test[test_h2_state__test_rst_flood_triggers_goaway]()
    suite.test[test_h2_state__test_priority_accepted_and_ignored]()
    # tests/http2/test_h2_streaming_state.mojo
    suite.test[
        test_h2_streaming_state__test_h2_informationals_and_length_survives_body_drains
    ]()
    suite.test[
        test_h2_streaming_state__test_h2_head_metadata_does_not_require_data
    ]()
    suite.test[
        test_h2_streaming_state__test_h2_truncated_content_length_is_a_stream_error
    ]()
    suite.test[
        test_h2_streaming_state__test_h2_streaming_credit_follows_body_drains
    ]()
    suite.test[
        test_h2_streaming_state__test_h2_undrained_stream_cannot_exceed_receive_window
    ]()
    suite.test[
        test_h2_streaming_state__test_h2_rejects_data_before_final_response_headers
    ]()
    suite.test[
        test_h2_streaming_state__test_h2_no_error_reset_only_preserves_complete_response
    ]()
    suite.test[
        test_h2_streaming_state__test_h2_window_update_before_rejection_does_not_resume_upload
    ]()
    suite.test[
        test_h2_streaming_state__test_h2_malformed_response_does_not_kill_sibling_streams
    ]()
    suite.test[
        test_h2_streaming_state__test_h2_goaway_marks_unprocessed_streams_refused
    ]()
    # tests/http2/test_stream_slab.mojo
    suite.test[test_stream_slab__test_empty_slab_is_empty]()
    suite.test[test_stream_slab__test_fast_tier_roundtrip]()
    suite.test[test_stream_slab__test_overflow_tier_roundtrip]()
    suite.test[test_stream_slab__test_both_tiers_coexist]()
    suite.test[test_stream_slab__test_overwrite_does_not_double_count]()
    suite.test[test_stream_slab__test_getitem_on_missing_raises]()
    suite.test[test_stream_slab__test_get_returns_optional]()
    suite.test[test_stream_slab__test_pop_clears_slot]()
    suite.test[test_stream_slab__test_items_lists_everything]()
    suite.test[test_stream_slab__test_stress_roundtrip]()
    suite^.run()
