"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 3 test files of ``tests/dns/`` into one compiled
binary so the 3 separate compiler invocations become one. Run it with
``mojo -I . -I tests/dns`` (see tools/run_test_aggregates.sh).

Regenerate with ``python3 tools/gen_test_aggregates.py``; CI fails if this
file is out of date with the tree.
"""

from std.testing import TestSuite
from test_async_resolve import (
    test_resolve_async_matches_sync_localhost as test_async_resolve__test_resolve_async_matches_sync_localhost,
)
from test_async_resolve import (
    test_resolve_async_empty_host_raises as test_async_resolve__test_resolve_async_empty_host_raises,
)
from test_async_resolve import (
    test_resolve_async_preflipped_cancel_raises as test_async_resolve__test_resolve_async_preflipped_cancel_raises,
)
from test_async_resolve import (
    test_happy_eyeballs_interleaves_families as test_async_resolve__test_happy_eyeballs_interleaves_families,
)
from test_async_resolve import (
    test_happy_eyeballs_uneven_families as test_async_resolve__test_happy_eyeballs_uneven_families,
)
from test_async_resolve import (
    test_cache_async_serves_hit_without_spawn as test_async_resolve__test_cache_async_serves_hit_without_spawn,
)
from test_dns import (
    test_resolve_localhost_non_empty as test_dns__test_resolve_localhost_non_empty,
)
from test_dns import (
    test_resolve_localhost_has_loopback as test_dns__test_resolve_localhost_has_loopback,
)
from test_dns import (
    test_resolve_v4_localhost_non_empty as test_dns__test_resolve_v4_localhost_non_empty,
)
from test_dns import (
    test_resolve_v4_all_ipv4 as test_dns__test_resolve_v4_all_ipv4,
)
from test_dns import (
    test_resolve_v4_contains_127 as test_dns__test_resolve_v4_contains_127,
)
from test_dns import (
    test_resolve_numeric_ipv4_passthrough as test_dns__test_resolve_numeric_ipv4_passthrough,
)
from test_dns import (
    test_resolve_numeric_ipv6_passthrough as test_dns__test_resolve_numeric_ipv6_passthrough,
)
from test_dns import (
    test_resolve_numeric_v4_192 as test_dns__test_resolve_numeric_v4_192,
)
from test_dns import (
    test_resolve_v6_localhost_includes_v6_or_raises as test_dns__test_resolve_v6_localhost_includes_v6_or_raises,
)
from test_dns import (
    test_resolve_fqdn_trailing_dot as test_dns__test_resolve_fqdn_trailing_dot,
)
from test_dns import (
    test_resolve_empty_host_raises as test_dns__test_resolve_empty_host_raises,
)
from test_dns import (
    test_resolve_nonexistent_raises as test_dns__test_resolve_nonexistent_raises,
)
from test_dns import (
    test_resolve_null_byte_injection_raises as test_dns__test_resolve_null_byte_injection_raises,
)
from test_dns import (
    test_resolve_crlf_injection_raises as test_dns__test_resolve_crlf_injection_raises,
)
from test_dns import (
    test_resolve_at_sign_raises as test_dns__test_resolve_at_sign_raises,
)
from test_dns import (
    test_resolve_hostname_too_long_raises as test_dns__test_resolve_hostname_too_long_raises,
)
from test_dns import (
    test_resolve_label_too_long_raises as test_dns__test_resolve_label_too_long_raises,
)
from test_dns_cache import (
    test_within_ttl_no_second_syscall as test_dns_cache__test_within_ttl_no_second_syscall,
)
from test_dns_cache import (
    test_zero_ttl_always_resolves as test_dns_cache__test_zero_ttl_always_resolves,
)
from test_dns_cache import (
    test_distinct_hosts_each_resolve as test_dns_cache__test_distinct_hosts_each_resolve,
)
from test_dns_cache import (
    test_invalidate_forces_resolve as test_dns_cache__test_invalidate_forces_resolve,
)
from test_dns_cache import (
    test_clear_drops_all as test_dns_cache__test_clear_drops_all,
)


def main() raises:
    var suite = TestSuite()
    # tests/dns/test_async_resolve.mojo
    suite.test[test_async_resolve__test_resolve_async_matches_sync_localhost]()
    suite.test[test_async_resolve__test_resolve_async_empty_host_raises]()
    suite.test[
        test_async_resolve__test_resolve_async_preflipped_cancel_raises
    ]()
    suite.test[test_async_resolve__test_happy_eyeballs_interleaves_families]()
    suite.test[test_async_resolve__test_happy_eyeballs_uneven_families]()
    suite.test[test_async_resolve__test_cache_async_serves_hit_without_spawn]()
    # tests/dns/test_dns.mojo
    suite.test[test_dns__test_resolve_localhost_non_empty]()
    suite.test[test_dns__test_resolve_localhost_has_loopback]()
    suite.test[test_dns__test_resolve_v4_localhost_non_empty]()
    suite.test[test_dns__test_resolve_v4_all_ipv4]()
    suite.test[test_dns__test_resolve_v4_contains_127]()
    suite.test[test_dns__test_resolve_numeric_ipv4_passthrough]()
    suite.test[test_dns__test_resolve_numeric_ipv6_passthrough]()
    suite.test[test_dns__test_resolve_numeric_v4_192]()
    suite.test[test_dns__test_resolve_v6_localhost_includes_v6_or_raises]()
    suite.test[test_dns__test_resolve_fqdn_trailing_dot]()
    suite.test[test_dns__test_resolve_empty_host_raises]()
    suite.test[test_dns__test_resolve_nonexistent_raises]()
    suite.test[test_dns__test_resolve_null_byte_injection_raises]()
    suite.test[test_dns__test_resolve_crlf_injection_raises]()
    suite.test[test_dns__test_resolve_at_sign_raises]()
    suite.test[test_dns__test_resolve_hostname_too_long_raises]()
    suite.test[test_dns__test_resolve_label_too_long_raises]()
    # tests/dns/test_dns_cache.mojo
    suite.test[test_dns_cache__test_within_ttl_no_second_syscall]()
    suite.test[test_dns_cache__test_zero_ttl_always_resolves]()
    suite.test[test_dns_cache__test_distinct_hosts_each_resolve]()
    suite.test[test_dns_cache__test_invalidate_forces_resolve]()
    suite.test[test_dns_cache__test_clear_drops_all]()
    suite^.run()
