"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 2 test files of ``tests/crypto/`` into one compiled
binary so the 2 separate compiler invocations become one. Run it with
``mojo -I . -I tests/crypto`` (see tools/run_test_aggregates.sh).

Regenerate with ``python3 tools/gen_test_aggregates.py``; CI fails if this
file is out of date with the tree.
"""

from std.testing import TestSuite
from test_base64 import (
    test_base64_rfc4648_test_vectors as test_base64__test_base64_rfc4648_test_vectors,
)
from test_base64 import (
    test_base64_round_trip_byte_range as test_base64__test_base64_round_trip_byte_range,
)
from test_base64 import (
    test_base64_decode_tolerates_missing_padding as test_base64__test_base64_decode_tolerates_missing_padding,
)
from test_base64 import (
    test_base64_decode_rejects_invalid_byte as test_base64__test_base64_decode_rejects_invalid_byte,
)
from test_hmac import (
    test_rfc4231_test_case_1 as test_hmac__test_rfc4231_test_case_1,
)
from test_hmac import (
    test_rfc4231_test_case_2 as test_hmac__test_rfc4231_test_case_2,
)
from test_hmac import (
    test_rfc4231_test_case_3 as test_hmac__test_rfc4231_test_case_3,
)
from test_hmac import (
    test_rfc4231_test_case_4 as test_hmac__test_rfc4231_test_case_4,
)
from test_hmac import (
    test_verify_happy_path as test_hmac__test_verify_happy_path,
)
from test_hmac import (
    test_verify_tampered_payload_rejects as test_hmac__test_verify_tampered_payload_rejects,
)
from test_hmac import (
    test_verify_wrong_key_rejects as test_hmac__test_verify_wrong_key_rejects,
)
from test_hmac import (
    test_verify_short_mac_rejects as test_hmac__test_verify_short_mac_rejects,
)
from test_hmac import (
    test_empty_key_and_msg as test_hmac__test_empty_key_and_msg,
)
from test_hmac import test_b64url_empty as test_hmac__test_b64url_empty
from test_hmac import (
    test_b64url_simple_roundtrip as test_hmac__test_b64url_simple_roundtrip,
)
from test_hmac import (
    test_b64url_padding_tolerated as test_hmac__test_b64url_padding_tolerated,
)
from test_hmac import (
    test_b64url_url_safe_chars as test_hmac__test_b64url_url_safe_chars,
)
from test_hmac import (
    test_b64url_invalid_character_raises as test_hmac__test_b64url_invalid_character_raises,
)


def main() raises:
    var suite = TestSuite()
    # tests/crypto/test_base64.mojo
    suite.test[test_base64__test_base64_rfc4648_test_vectors]()
    suite.test[test_base64__test_base64_round_trip_byte_range]()
    suite.test[test_base64__test_base64_decode_tolerates_missing_padding]()
    suite.test[test_base64__test_base64_decode_rejects_invalid_byte]()
    # tests/crypto/test_hmac.mojo
    suite.test[test_hmac__test_rfc4231_test_case_1]()
    suite.test[test_hmac__test_rfc4231_test_case_2]()
    suite.test[test_hmac__test_rfc4231_test_case_3]()
    suite.test[test_hmac__test_rfc4231_test_case_4]()
    suite.test[test_hmac__test_verify_happy_path]()
    suite.test[test_hmac__test_verify_tampered_payload_rejects]()
    suite.test[test_hmac__test_verify_wrong_key_rejects]()
    suite.test[test_hmac__test_verify_short_mac_rejects]()
    suite.test[test_hmac__test_empty_key_and_msg]()
    suite.test[test_hmac__test_b64url_empty]()
    suite.test[test_hmac__test_b64url_simple_roundtrip]()
    suite.test[test_hmac__test_b64url_padding_tolerated]()
    suite.test[test_hmac__test_b64url_url_safe_chars]()
    suite.test[test_hmac__test_b64url_invalid_character_raises]()
    suite^.run()
