"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 3 test files of ``tests/testing/`` into one compiled
binary so the 3 separate compiler invocations become one. Run it with
``mojo -I . -I tests/testing`` (see tools/run_test_aggregates.sh).

Regenerate with ``python3 tools/gen_test_aggregates.py``; CI fails if this
file is out of date with the tree.
"""

from std.testing import TestSuite
from test_fork_server import (
    test_fork_server_bare_function_overload as test_fork_server__test_fork_server_bare_function_overload,
)
from test_fork_server import (
    test_fork_server_handler_struct_overload as test_fork_server__test_fork_server_handler_struct_overload,
)
from test_fork_server import (
    test_fork_server_router_handler_only as test_fork_server__test_fork_server_router_handler_only,
)
from test_h2c_test_client import (
    test_get_round_trips_over_h2 as test_h2c_test_client__test_get_round_trips_over_h2,
)
from test_h2c_test_client import (
    test_post_body_flows_over_h2 as test_h2c_test_client__test_post_body_flows_over_h2,
)
from test_h2c_test_client import (
    test_put_patch_delete_over_h2 as test_h2c_test_client__test_put_patch_delete_over_h2,
)
from test_h2c_test_client import (
    test_custom_header_flows_over_h2 as test_h2c_test_client__test_custom_header_flows_over_h2,
)
from test_test_client import (
    test_get_dispatches_correctly as test_test_client__test_get_dispatches_correctly,
)
from test_test_client import (
    test_post_body_flows_through as test_test_client__test_post_body_flows_through,
)
from test_test_client import (
    test_put_patch_delete_dispatch as test_test_client__test_put_patch_delete_dispatch,
)
from test_test_client import (
    test_head_options_dispatch as test_test_client__test_head_options_dispatch,
)
from test_test_client import (
    test_custom_headers_flow_through as test_test_client__test_custom_headers_flow_through,
)


def main() raises:
    var suite = TestSuite()
    # tests/testing/test_fork_server.mojo
    suite.test[test_fork_server__test_fork_server_bare_function_overload]()
    suite.test[test_fork_server__test_fork_server_handler_struct_overload]()
    suite.test[test_fork_server__test_fork_server_router_handler_only]()
    # tests/testing/test_h2c_test_client.mojo
    suite.test[test_h2c_test_client__test_get_round_trips_over_h2]()
    suite.test[test_h2c_test_client__test_post_body_flows_over_h2]()
    suite.test[test_h2c_test_client__test_put_patch_delete_over_h2]()
    suite.test[test_h2c_test_client__test_custom_header_flows_over_h2]()
    # tests/testing/test_test_client.mojo
    suite.test[test_test_client__test_get_dispatches_correctly]()
    suite.test[test_test_client__test_post_body_flows_through]()
    suite.test[test_test_client__test_put_patch_delete_dispatch]()
    suite.test[test_test_client__test_head_options_dispatch]()
    suite.test[test_test_client__test_custom_headers_flow_through]()
    suite^.run()
