"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 2 test files of ``tests/_root/`` into one compiled
binary so the 2 separate compiler invocations become one. Run it with
``mojo -I . -I tests/_root`` (see tools/run_test_aggregates.sh).

Regenerate with ``python3 tools/gen_test_aggregates.py``; CI fails if this
file is out of date with the tree.
"""

from std.testing import TestSuite
from test_errors import (
    test_validation_error_construct_and_field_access as test_errors__test_validation_error_construct_and_field_access,
)
from test_errors import (
    test_validation_error_write_to_renders_field_and_reason as test_errors__test_validation_error_write_to_renders_field_and_reason,
)
from test_errors import (
    test_validation_error_typed_round_trip_preserves_fields as test_errors__test_validation_error_typed_round_trip_preserves_fields,
)
from test_errors import (
    test_validation_error_survives_bare_raises_propagation as test_errors__test_validation_error_survives_bare_raises_propagation,
)
from test_errors import (
    test_io_error_construct_and_field_access as test_errors__test_io_error_construct_and_field_access,
)
from test_errors import (
    test_io_error_write_to_includes_errno_when_nonzero as test_errors__test_io_error_write_to_includes_errno_when_nonzero,
)
from test_errors import (
    test_io_error_write_to_omits_errno_when_zero as test_errors__test_io_error_write_to_omits_errno_when_zero,
)
from test_errors import (
    test_io_error_typed_round_trip_preserves_fields as test_errors__test_io_error_typed_round_trip_preserves_fields,
)
from test_errors import (
    test_http_status_error_render as test_errors__test_http_status_error_render,
)
from test_errors import (
    test_http_status_error_default_message as test_errors__test_http_status_error_default_message,
)
from test_errors import (
    test_status_error_codec_round_trip as test_errors__test_status_error_codec_round_trip,
)
from test_errors import (
    test_status_error_codec_rejects_non_status as test_errors__test_status_error_codec_rejects_non_status,
)
from test_errors import (
    test_map_http_status_error_through_bare_raises as test_errors__test_map_http_status_error_through_bare_raises,
)
from test_errors import (
    test_map_validation_error_sanitized as test_errors__test_map_validation_error_sanitized,
)
from test_errors import (
    test_map_validation_error_exposed as test_errors__test_map_validation_error_exposed,
)
from test_errors import (
    test_map_generic_error_defaults_to_500 as test_errors__test_map_generic_error_defaults_to_500,
)
from test_errors import (
    test_map_malformed_status_error_falls_back_to_500 as test_errors__test_map_malformed_status_error_falls_back_to_500,
)
from test_errors import (
    test_map_out_of_range_status_falls_back_to_500 as test_errors__test_map_out_of_range_status_falls_back_to_500,
)
from test_errors import (
    test_reason_phrase_fallbacks as test_errors__test_reason_phrase_fallbacks,
)
from test_prelude_surface import (
    test_core_types_are_the_same_entity as test_prelude_surface__test_core_types_are_the_same_entity,
)
from test_prelude_surface import (
    test_response_helpers_agree as test_prelude_surface__test_response_helpers_agree,
)
from test_prelude_surface import (
    test_request_roundtrips_through_either_import as test_prelude_surface__test_request_roundtrips_through_either_import,
)
from test_prelude_surface import (
    test_prelude_is_not_the_wide_surface as test_prelude_surface__test_prelude_is_not_the_wide_surface,
)


def main() raises:
    var suite = TestSuite()
    # tests/test_errors.mojo
    suite.test[test_errors__test_validation_error_construct_and_field_access]()
    suite.test[
        test_errors__test_validation_error_write_to_renders_field_and_reason
    ]()
    suite.test[
        test_errors__test_validation_error_typed_round_trip_preserves_fields
    ]()
    suite.test[
        test_errors__test_validation_error_survives_bare_raises_propagation
    ]()
    suite.test[test_errors__test_io_error_construct_and_field_access]()
    suite.test[
        test_errors__test_io_error_write_to_includes_errno_when_nonzero
    ]()
    suite.test[test_errors__test_io_error_write_to_omits_errno_when_zero]()
    suite.test[test_errors__test_io_error_typed_round_trip_preserves_fields]()
    suite.test[test_errors__test_http_status_error_render]()
    suite.test[test_errors__test_http_status_error_default_message]()
    suite.test[test_errors__test_status_error_codec_round_trip]()
    suite.test[test_errors__test_status_error_codec_rejects_non_status]()
    suite.test[test_errors__test_map_http_status_error_through_bare_raises]()
    suite.test[test_errors__test_map_validation_error_sanitized]()
    suite.test[test_errors__test_map_validation_error_exposed]()
    suite.test[test_errors__test_map_generic_error_defaults_to_500]()
    suite.test[test_errors__test_map_malformed_status_error_falls_back_to_500]()
    suite.test[test_errors__test_map_out_of_range_status_falls_back_to_500]()
    suite.test[test_errors__test_reason_phrase_fallbacks]()
    # tests/test_prelude_surface.mojo
    suite.test[test_prelude_surface__test_core_types_are_the_same_entity]()
    suite.test[test_prelude_surface__test_response_helpers_agree]()
    suite.test[
        test_prelude_surface__test_request_roundtrips_through_either_import
    ]()
    suite.test[test_prelude_surface__test_prelude_is_not_the_wide_surface]()
    suite^.run()
