"""GENERATED by tests/tools/gen_test_aggregates.py -- do not edit.

Aggregates the 2 test files of ``tests/udp/`` into one compiled
binary so the 2 separate compiler invocations become one. Run it with
``mojo -I . -I tests/udp`` (see tests/tools/run_test_aggregates.sh).

Regenerate with ``python3 tests/tools/gen_test_aggregates.py``; CI fails if this
file is out of date with the tree.
"""

from std.testing import TestSuite
from test_udp import test_bind_assigns_port as test_udp__test_bind_assigns_port
from test_udp import (
    test_unbound_socket_creates_ok as test_udp__test_unbound_socket_creates_ok,
)
from test_udp import test_close_idempotent as test_udp__test_close_idempotent
from test_udp import test_round_trip_1_byte as test_udp__test_round_trip_1_byte
from test_udp import (
    test_round_trip_512_bytes as test_udp__test_round_trip_512_bytes,
)
from test_udp import (
    test_round_trip_returns_sender_addr as test_udp__test_round_trip_returns_sender_addr,
)
from test_udp import (
    test_recv_from_multiple_datagrams as test_udp__test_recv_from_multiple_datagrams,
)
from test_udp import (
    test_datagram_too_large_raises as test_udp__test_datagram_too_large_raises,
)
from test_udp import (
    test_datagram_large_payload as test_udp__test_datagram_large_payload,
)
from test_udp import (
    test_recv_timeout_raises as test_udp__test_recv_timeout_raises,
)
from test_udp_batch import (
    test_recvmmsg_batch_round_trip as test_udp_batch__test_recvmmsg_batch_round_trip,
)
from test_udp_batch import (
    test_sendmmsg_batch_round_trip as test_udp_batch__test_sendmmsg_batch_round_trip,
)
from test_udp_batch import (
    test_gso_segmented_send as test_udp_batch__test_gso_segmented_send,
)


def main() raises:
    var suite = TestSuite()
    # tests/udp/test_udp.mojo
    suite.test[test_udp__test_bind_assigns_port]()
    suite.test[test_udp__test_unbound_socket_creates_ok]()
    suite.test[test_udp__test_close_idempotent]()
    suite.test[test_udp__test_round_trip_1_byte]()
    suite.test[test_udp__test_round_trip_512_bytes]()
    suite.test[test_udp__test_round_trip_returns_sender_addr]()
    suite.test[test_udp__test_recv_from_multiple_datagrams]()
    suite.test[test_udp__test_datagram_too_large_raises]()
    suite.test[test_udp__test_datagram_large_payload]()
    suite.test[test_udp__test_recv_timeout_raises]()
    # tests/udp/test_udp_batch.mojo
    suite.test[test_udp_batch__test_recvmmsg_batch_round_trip]()
    suite.test[test_udp_batch__test_sendmmsg_batch_round_trip]()
    suite.test[test_udp_batch__test_gso_segmented_send]()
    suite^.run()
