"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 12 test files of ``tests/grpc/`` into one compiled
binary so the 12 separate compiler invocations become one. Run it with
``mojo -I . -I tests/grpc`` (see tools/run_test_aggregates.sh).

Regenerate with ``python3 tools/gen_test_aggregates.py``; CI fails if this
file is out of date with the tree.
"""

from std.testing import TestSuite
from proto.test_codegen import (
    test_point_round_trip as proto__test_codegen__test_point_round_trip,
)
from proto.test_codegen import (
    test_point_defaults_omitted as proto__test_codegen__test_point_defaults_omitted,
)
from proto.test_codegen import (
    test_shape_round_trip as proto__test_codegen__test_shape_round_trip,
)
from proto.test_codegen import (
    test_packed_repeated_scalar_decodes as proto__test_codegen__test_packed_repeated_scalar_decodes,
)
from proto.test_codegen import (
    test_service_path_consts as proto__test_codegen__test_service_path_consts,
)
from proto.test_codegen import (
    test_file_descriptor_emitted as proto__test_codegen__test_file_descriptor_emitted,
)
from test_grpc import (
    test_lpm_round_trip_short_payload as test_grpc__test_lpm_round_trip_short_payload,
)
from test_grpc import (
    test_lpm_round_trip_compressed_flag as test_grpc__test_lpm_round_trip_compressed_flag,
)
from test_grpc import (
    test_lpm_empty_payload as test_grpc__test_lpm_empty_payload,
)
from test_grpc import (
    test_lpm_decoder_needs_more_on_partial_header as test_grpc__test_lpm_decoder_needs_more_on_partial_header,
)
from test_grpc import (
    test_lpm_decoder_needs_more_on_partial_payload as test_grpc__test_lpm_decoder_needs_more_on_partial_payload,
)
from test_grpc import (
    test_lpm_decoder_handles_back_to_back_frames as test_grpc__test_lpm_decoder_handles_back_to_back_frames,
)
from test_grpc import (
    test_compression_flag_reserved_bits as test_grpc__test_compression_flag_reserved_bits,
)
from test_grpc import (
    test_status_numeric_constants as test_grpc__test_status_numeric_constants,
)
from test_grpc import (
    test_status_ok_and_err_constructors as test_grpc__test_status_ok_and_err_constructors,
)
from test_grpc import (
    test_status_with_details_round_trip as test_grpc__test_status_with_details_round_trip,
)
from test_grpc import test_status_names as test_grpc__test_status_names
from test_grpc_client import (
    test_unary_echo_ok as test_grpc_client__test_unary_echo_ok,
)
from test_grpc_client import (
    test_unary_non_ok_status as test_grpc_client__test_unary_non_ok_status,
)
from test_grpc_client import (
    test_unary_metadata_forwarded as test_grpc_client__test_unary_metadata_forwarded,
)
from test_grpc_compression import (
    test_response_compressed_when_accepted as test_grpc_compression__test_response_compressed_when_accepted,
)
from test_grpc_compression import (
    test_response_uncompressed_when_not_accepted as test_grpc_compression__test_response_uncompressed_when_not_accepted,
)
from test_grpc_compression import (
    test_small_response_not_compressed as test_grpc_compression__test_small_response_not_compressed,
)
from test_grpc_compression import (
    test_request_decompression_gzip as test_grpc_compression__test_request_decompression_gzip,
)
from test_grpc_compression import (
    test_compressed_request_without_encoding_raises as test_grpc_compression__test_compressed_request_without_encoding_raises,
)
from test_grpc_interceptor_health import (
    test_interceptor_passthrough_and_after as test_grpc_interceptor_health__test_interceptor_passthrough_and_after,
)
from test_grpc_interceptor_health import (
    test_interceptor_short_circuit as test_grpc_interceptor_health__test_interceptor_short_circuit,
)
from test_grpc_interceptor_health import (
    test_interceptor_chain_nested as test_grpc_interceptor_health__test_interceptor_chain_nested,
)
from test_grpc_interceptor_health import (
    test_health_serving as test_grpc_interceptor_health__test_health_serving,
)
from test_grpc_interceptor_health import (
    test_health_not_serving as test_grpc_interceptor_health__test_health_not_serving,
)
from test_grpc_interceptor_health import (
    test_health_unknown_service as test_grpc_interceptor_health__test_health_unknown_service,
)
from test_grpc_interceptor_health import (
    test_health_request_roundtrip as test_grpc_interceptor_health__test_health_request_roundtrip,
)
from test_grpc_interceptor_health import (
    test_watch_replays_status_transitions as test_grpc_interceptor_health__test_watch_replays_status_transitions,
)
from test_grpc_interceptor_health import (
    test_watch_unknown_service_reports_unknown as test_grpc_interceptor_health__test_watch_unknown_service_reports_unknown,
)
from test_grpc_proto import (
    test_varint_round_trip as test_grpc_proto__test_varint_round_trip,
)
from test_grpc_proto import (
    test_zigzag_sint as test_grpc_proto__test_zigzag_sint,
)
from test_grpc_proto import (
    test_string_and_bytes as test_grpc_proto__test_string_and_bytes,
)
from test_grpc_proto import (
    test_fixed_and_float as test_grpc_proto__test_fixed_and_float,
)
from test_grpc_proto import (
    test_embedded_message as test_grpc_proto__test_embedded_message,
)
from test_grpc_proto import (
    test_skip_unknown_field as test_grpc_proto__test_skip_unknown_field,
)
from test_grpc_reflection import (
    test_request_decode_list_services as test_grpc_reflection__test_request_decode_list_services,
)
from test_grpc_reflection import (
    test_list_services_response as test_grpc_reflection__test_list_services_response,
)
from test_grpc_reflection import (
    test_unregistered_descriptor_returns_not_found as test_grpc_reflection__test_unregistered_descriptor_returns_not_found,
)
from test_grpc_reflection import (
    test_file_by_filename_returns_descriptor as test_grpc_reflection__test_file_by_filename_returns_descriptor,
)
from test_grpc_reflection import (
    test_file_containing_symbol_returns_descriptor as test_grpc_reflection__test_file_containing_symbol_returns_descriptor,
)
from test_grpc_reflection import (
    test_bidi_handler_answers_each_message as test_grpc_reflection__test_bidi_handler_answers_each_message,
)
from test_grpc_server_stream import (
    test_stream_yields_n_frames as test_grpc_server_stream__test_stream_yields_n_frames,
)
from test_grpc_server_stream import (
    test_stream_zero_messages as test_grpc_server_stream__test_stream_zero_messages,
)
from test_grpc_server_stream import (
    test_stream_handler_raises_maps_internal as test_grpc_server_stream__test_stream_handler_raises_maps_internal,
)
from test_grpc_streaming import (
    test_server_streaming_service_incremental_frames as test_grpc_streaming__test_server_streaming_service_incremental_frames,
)
from test_grpc_streaming import (
    test_server_streaming_yields_n_messages_in_order as test_grpc_streaming__test_server_streaming_yields_n_messages_in_order,
)
from test_grpc_streaming import (
    test_client_streaming_counts_messages as test_grpc_streaming__test_client_streaming_counts_messages,
)
from test_grpc_streaming import (
    test_bidi_echoes_each_message as test_grpc_streaming__test_bidi_echoes_each_message,
)
from test_grpc_streaming import (
    test_client_streaming_service_counts_messages as test_grpc_streaming__test_client_streaming_service_counts_messages,
)
from test_grpc_streaming import (
    test_bidi_service_echoes_each_message as test_grpc_streaming__test_bidi_service_echoes_each_message,
)
from test_grpc_unary_mount import (
    test_mounted_unary_echo as test_grpc_unary_mount__test_mounted_unary_echo,
)
from test_grpc_unary_mount import (
    test_mounted_unary_error as test_grpc_unary_mount__test_mounted_unary_error,
)
from test_grpc_unary_mount import (
    test_mounted_deadline_exceeded as test_grpc_unary_mount__test_mounted_deadline_exceeded,
)
from test_metadata import (
    test_append_text_round_trip as test_metadata__test_append_text_round_trip,
)
from test_metadata import (
    test_append_binary_round_trip as test_metadata__test_append_binary_round_trip,
)
from test_metadata import (
    test_rejects_reserved_grpc_prefix as test_metadata__test_rejects_reserved_grpc_prefix,
)
from test_metadata import (
    test_rejects_text_for_binary_key as test_metadata__test_rejects_text_for_binary_key,
)
from test_metadata import (
    test_missing_key_returns_none as test_metadata__test_missing_key_returns_none,
)
from test_metadata import (
    test_text_vs_binary_get_mismatch_raises as test_metadata__test_text_vs_binary_get_mismatch_raises,
)
from test_metadata import (
    test_insertion_order_preserved as test_metadata__test_insertion_order_preserved,
)
from test_server import (
    test_parse_request_headers_minimal as test_server__test_parse_request_headers_minimal,
)
from test_server import (
    test_parse_request_headers_proto_flavor as test_server__test_parse_request_headers_proto_flavor,
)
from test_server import (
    test_parse_request_headers_rejects_get as test_server__test_parse_request_headers_rejects_get,
)
from test_server import (
    test_parse_request_headers_rejects_bad_content_type as test_server__test_parse_request_headers_rejects_bad_content_type,
)
from test_server import (
    test_parse_request_headers_rejects_missing_trailers as test_server__test_parse_request_headers_rejects_missing_trailers,
)
from test_server import (
    test_parse_request_headers_rejects_path_without_method as test_server__test_parse_request_headers_rejects_path_without_method,
)
from test_server import (
    test_parse_request_headers_parses_timeout as test_server__test_parse_request_headers_parses_timeout,
)
from test_server import (
    test_parse_request_headers_timeout_units as test_server__test_parse_request_headers_timeout_units,
)
from test_server import (
    test_parse_request_headers_te_case_insensitive as test_server__test_parse_request_headers_te_case_insensitive,
)
from test_server import (
    test_parse_request_headers_missing_optionals_default as test_server__test_parse_request_headers_missing_optionals_default,
)
from test_server import (
    test_stitch_single_lpm_frame as test_server__test_stitch_single_lpm_frame,
)
from test_server import (
    test_stitch_multiple_lpm_frames as test_server__test_stitch_multiple_lpm_frames,
)
from test_server import (
    test_stitch_rejects_truncated_frame as test_server__test_stitch_rejects_truncated_frame,
)
from test_server import (
    test_stitch_rejects_compressed_frame as test_server__test_stitch_rejects_compressed_frame,
)
from test_server import (
    test_run_unary_call_echo as test_server__test_run_unary_call_echo,
)
from test_server import (
    test_run_unary_call_invalid_method_emits_invalid_argument as test_server__test_run_unary_call_invalid_method_emits_invalid_argument,
)
from test_server import (
    test_run_unary_call_truncated_lpm_emits_invalid_argument as test_server__test_run_unary_call_truncated_lpm_emits_invalid_argument,
)
from test_server import (
    test_run_unary_call_handler_raise_emits_internal as test_server__test_run_unary_call_handler_raise_emits_internal,
)
from test_server import (
    test_emit_trailing_headers_status_ok_minimal as test_server__test_emit_trailing_headers_status_ok_minimal,
)
from test_server import (
    test_emit_trailing_headers_status_err_with_message as test_server__test_emit_trailing_headers_status_err_with_message,
)
from test_server import (
    test_emit_trailing_headers_status_with_details_bin as test_server__test_emit_trailing_headers_status_with_details_bin,
)
from test_server import (
    test_run_unary_call_error_status_emits_empty_body as test_server__test_run_unary_call_error_status_emits_empty_body,
)


def main() raises:
    var suite = TestSuite()
    # tests/grpc/proto/test_codegen.mojo
    suite.test[proto__test_codegen__test_point_round_trip]()
    suite.test[proto__test_codegen__test_point_defaults_omitted]()
    suite.test[proto__test_codegen__test_shape_round_trip]()
    suite.test[proto__test_codegen__test_packed_repeated_scalar_decodes]()
    suite.test[proto__test_codegen__test_service_path_consts]()
    suite.test[proto__test_codegen__test_file_descriptor_emitted]()
    # tests/grpc/test_grpc.mojo
    suite.test[test_grpc__test_lpm_round_trip_short_payload]()
    suite.test[test_grpc__test_lpm_round_trip_compressed_flag]()
    suite.test[test_grpc__test_lpm_empty_payload]()
    suite.test[test_grpc__test_lpm_decoder_needs_more_on_partial_header]()
    suite.test[test_grpc__test_lpm_decoder_needs_more_on_partial_payload]()
    suite.test[test_grpc__test_lpm_decoder_handles_back_to_back_frames]()
    suite.test[test_grpc__test_compression_flag_reserved_bits]()
    suite.test[test_grpc__test_status_numeric_constants]()
    suite.test[test_grpc__test_status_ok_and_err_constructors]()
    suite.test[test_grpc__test_status_with_details_round_trip]()
    suite.test[test_grpc__test_status_names]()
    # tests/grpc/test_grpc_client.mojo
    suite.test[test_grpc_client__test_unary_echo_ok]()
    suite.test[test_grpc_client__test_unary_non_ok_status]()
    suite.test[test_grpc_client__test_unary_metadata_forwarded]()
    # tests/grpc/test_grpc_compression.mojo
    suite.test[test_grpc_compression__test_response_compressed_when_accepted]()
    suite.test[
        test_grpc_compression__test_response_uncompressed_when_not_accepted
    ]()
    suite.test[test_grpc_compression__test_small_response_not_compressed]()
    suite.test[test_grpc_compression__test_request_decompression_gzip]()
    suite.test[
        test_grpc_compression__test_compressed_request_without_encoding_raises
    ]()
    # tests/grpc/test_grpc_interceptor_health.mojo
    suite.test[
        test_grpc_interceptor_health__test_interceptor_passthrough_and_after
    ]()
    suite.test[test_grpc_interceptor_health__test_interceptor_short_circuit]()
    suite.test[test_grpc_interceptor_health__test_interceptor_chain_nested]()
    suite.test[test_grpc_interceptor_health__test_health_serving]()
    suite.test[test_grpc_interceptor_health__test_health_not_serving]()
    suite.test[test_grpc_interceptor_health__test_health_unknown_service]()
    suite.test[test_grpc_interceptor_health__test_health_request_roundtrip]()
    suite.test[
        test_grpc_interceptor_health__test_watch_replays_status_transitions
    ]()
    suite.test[
        test_grpc_interceptor_health__test_watch_unknown_service_reports_unknown
    ]()
    # tests/grpc/test_grpc_proto.mojo
    suite.test[test_grpc_proto__test_varint_round_trip]()
    suite.test[test_grpc_proto__test_zigzag_sint]()
    suite.test[test_grpc_proto__test_string_and_bytes]()
    suite.test[test_grpc_proto__test_fixed_and_float]()
    suite.test[test_grpc_proto__test_embedded_message]()
    suite.test[test_grpc_proto__test_skip_unknown_field]()
    # tests/grpc/test_grpc_reflection.mojo
    suite.test[test_grpc_reflection__test_request_decode_list_services]()
    suite.test[test_grpc_reflection__test_list_services_response]()
    suite.test[
        test_grpc_reflection__test_unregistered_descriptor_returns_not_found
    ]()
    suite.test[test_grpc_reflection__test_file_by_filename_returns_descriptor]()
    suite.test[
        test_grpc_reflection__test_file_containing_symbol_returns_descriptor
    ]()
    suite.test[test_grpc_reflection__test_bidi_handler_answers_each_message]()
    # tests/grpc/test_grpc_server_stream.mojo
    suite.test[test_grpc_server_stream__test_stream_yields_n_frames]()
    suite.test[test_grpc_server_stream__test_stream_zero_messages]()
    suite.test[
        test_grpc_server_stream__test_stream_handler_raises_maps_internal
    ]()
    # tests/grpc/test_grpc_streaming.mojo
    suite.test[
        test_grpc_streaming__test_server_streaming_service_incremental_frames
    ]()
    suite.test[
        test_grpc_streaming__test_server_streaming_yields_n_messages_in_order
    ]()
    suite.test[test_grpc_streaming__test_client_streaming_counts_messages]()
    suite.test[test_grpc_streaming__test_bidi_echoes_each_message]()
    suite.test[
        test_grpc_streaming__test_client_streaming_service_counts_messages
    ]()
    suite.test[test_grpc_streaming__test_bidi_service_echoes_each_message]()
    # tests/grpc/test_grpc_unary_mount.mojo
    suite.test[test_grpc_unary_mount__test_mounted_unary_echo]()
    suite.test[test_grpc_unary_mount__test_mounted_unary_error]()
    suite.test[test_grpc_unary_mount__test_mounted_deadline_exceeded]()
    # tests/grpc/test_metadata.mojo
    suite.test[test_metadata__test_append_text_round_trip]()
    suite.test[test_metadata__test_append_binary_round_trip]()
    suite.test[test_metadata__test_rejects_reserved_grpc_prefix]()
    suite.test[test_metadata__test_rejects_text_for_binary_key]()
    suite.test[test_metadata__test_missing_key_returns_none]()
    suite.test[test_metadata__test_text_vs_binary_get_mismatch_raises]()
    suite.test[test_metadata__test_insertion_order_preserved]()
    # tests/grpc/test_server.mojo
    suite.test[test_server__test_parse_request_headers_minimal]()
    suite.test[test_server__test_parse_request_headers_proto_flavor]()
    suite.test[test_server__test_parse_request_headers_rejects_get]()
    suite.test[
        test_server__test_parse_request_headers_rejects_bad_content_type
    ]()
    suite.test[
        test_server__test_parse_request_headers_rejects_missing_trailers
    ]()
    suite.test[
        test_server__test_parse_request_headers_rejects_path_without_method
    ]()
    suite.test[test_server__test_parse_request_headers_parses_timeout]()
    suite.test[test_server__test_parse_request_headers_timeout_units]()
    suite.test[test_server__test_parse_request_headers_te_case_insensitive]()
    suite.test[
        test_server__test_parse_request_headers_missing_optionals_default
    ]()
    suite.test[test_server__test_stitch_single_lpm_frame]()
    suite.test[test_server__test_stitch_multiple_lpm_frames]()
    suite.test[test_server__test_stitch_rejects_truncated_frame]()
    suite.test[test_server__test_stitch_rejects_compressed_frame]()
    suite.test[test_server__test_run_unary_call_echo]()
    suite.test[
        test_server__test_run_unary_call_invalid_method_emits_invalid_argument
    ]()
    suite.test[
        test_server__test_run_unary_call_truncated_lpm_emits_invalid_argument
    ]()
    suite.test[test_server__test_run_unary_call_handler_raise_emits_internal]()
    suite.test[test_server__test_emit_trailing_headers_status_ok_minimal]()
    suite.test[
        test_server__test_emit_trailing_headers_status_err_with_message
    ]()
    suite.test[
        test_server__test_emit_trailing_headers_status_with_details_bin
    ]()
    suite.test[test_server__test_run_unary_call_error_status_emits_empty_body]()
    suite^.run()
