"""GENERATED by tests/tools/gen_test_aggregates.py -- do not edit.

Aggregates the 1 test files of ``tests/net/`` into one compiled
binary so the 1 separate compiler invocations become one. Run it with
``mojo -I . -I tests/net`` (see tests/tools/run_test_aggregates.sh).

Regenerate with ``python3 tests/tools/gen_test_aggregates.py``; CI fails if this
file is out of date with the tree.
"""

from std.testing import TestSuite
from test_net import test_ip_addr_localhost as test_net__test_ip_addr_localhost
from test_net import (
    test_ip_addr_localhost_v6 as test_net__test_ip_addr_localhost_v6,
)
from test_net import (
    test_ip_addr_unspecified_v4 as test_net__test_ip_addr_unspecified_v4,
)
from test_net import (
    test_ip_addr_unspecified_v6 as test_net__test_ip_addr_unspecified_v6,
)
from test_net import test_ip_addr_broadcast as test_net__test_ip_addr_broadcast
from test_net import test_ip_addr_min_octet as test_net__test_ip_addr_min_octet
from test_net import (
    test_ip_addr_private_10 as test_net__test_ip_addr_private_10,
)
from test_net import (
    test_ip_addr_private_172 as test_net__test_ip_addr_private_172,
)
from test_net import (
    test_ip_addr_private_192 as test_net__test_ip_addr_private_192,
)
from test_net import (
    test_ip_addr_not_private_public as test_net__test_ip_addr_not_private_public,
)
from test_net import (
    test_ip_addr_not_private_172_boundary_below as test_net__test_ip_addr_not_private_172_boundary_below,
)
from test_net import (
    test_ip_addr_not_private_172_boundary_above as test_net__test_ip_addr_not_private_172_boundary_above,
)
from test_net import (
    test_ip_addr_loopback_127_any as test_net__test_ip_addr_loopback_127_any,
)
from test_net import (
    test_ip_addr_loopback_v6 as test_net__test_ip_addr_loopback_v6,
)
from test_net import (
    test_ip_addr_v6_loopback_full as test_net__test_ip_addr_v6_loopback_full,
)
from test_net import (
    test_ip_addr_v6_compressed as test_net__test_ip_addr_v6_compressed,
)
from test_net import (
    test_ip_addr_v6_all_zeros_long as test_net__test_ip_addr_v6_all_zeros_long,
)
from test_net import (
    test_ip_addr_v6_link_local as test_net__test_ip_addr_v6_link_local,
)
from test_net import (
    test_ip_addr_equality_v4 as test_net__test_ip_addr_equality_v4,
)
from test_net import (
    test_ip_addr_inequality_v4 as test_net__test_ip_addr_inequality_v4,
)
from test_net import (
    test_ip_addr_v4_not_equal_v6 as test_net__test_ip_addr_v4_not_equal_v6,
)
from test_net import (
    test_ip_addr_parse_too_many_octets_raises as test_net__test_ip_addr_parse_too_many_octets_raises,
)
from test_net import (
    test_ip_addr_parse_octet_overflow_raises as test_net__test_ip_addr_parse_octet_overflow_raises,
)
from test_net import (
    test_ip_addr_parse_negative_octet_raises as test_net__test_ip_addr_parse_negative_octet_raises,
)
from test_net import (
    test_ip_addr_parse_empty_raises as test_net__test_ip_addr_parse_empty_raises,
)
from test_net import (
    test_ip_addr_parse_alpha_raises as test_net__test_ip_addr_parse_alpha_raises,
)
from test_net import (
    test_ip_addr_parse_hex_no_prefix_raises as test_net__test_ip_addr_parse_hex_no_prefix_raises,
)
from test_net import (
    test_ip_addr_parse_newline_injection_raises as test_net__test_ip_addr_parse_newline_injection_raises,
)
from test_net import (
    test_ip_addr_parse_null_byte_raises as test_net__test_ip_addr_parse_null_byte_raises,
)
from test_net import test_socket_addr_str as test_net__test_socket_addr_str
from test_net import (
    test_socket_addr_localhost as test_net__test_socket_addr_localhost,
)
from test_net import (
    test_socket_addr_unspecified as test_net__test_socket_addr_unspecified,
)
from test_net import (
    test_socket_addr_max_port as test_net__test_socket_addr_max_port,
)
from test_net import (
    test_socket_addr_port_zero as test_net__test_socket_addr_port_zero,
)
from test_net import (
    test_socket_addr_port_well_known_http as test_net__test_socket_addr_port_well_known_http,
)
from test_net import (
    test_socket_addr_port_well_known_https as test_net__test_socket_addr_port_well_known_https,
)
from test_net import (
    test_socket_addr_parse_v4 as test_net__test_socket_addr_parse_v4,
)
from test_net import (
    test_socket_addr_parse_ipv6 as test_net__test_socket_addr_parse_ipv6,
)
from test_net import (
    test_socket_addr_equality as test_net__test_socket_addr_equality,
)
from test_net import (
    test_socket_addr_inequality_port as test_net__test_socket_addr_inequality_port,
)
from test_net import (
    test_socket_addr_inequality_ip as test_net__test_socket_addr_inequality_ip,
)
from test_net import (
    test_socket_addr_parse_missing_port_raises as test_net__test_socket_addr_parse_missing_port_raises,
)
from test_net import (
    test_socket_addr_parse_bad_ip_raises as test_net__test_socket_addr_parse_bad_ip_raises,
)
from test_net import (
    test_socket_addr_parse_empty_raises as test_net__test_socket_addr_parse_empty_raises,
)
from test_net import (
    test_socket_addr_parse_newline_injection_raises as test_net__test_socket_addr_parse_newline_injection_raises,
)
from test_net import (
    test_network_error_str_no_code as test_net__test_network_error_str_no_code,
)
from test_net import (
    test_network_error_str_with_code as test_net__test_network_error_str_with_code,
)
from test_net import (
    test_network_error_message_preserved as test_net__test_network_error_message_preserved,
)
from test_net import (
    test_connection_refused_str as test_net__test_connection_refused_str,
)
from test_net import (
    test_connection_timeout_str as test_net__test_connection_timeout_str,
)
from test_net import (
    test_address_in_use_str as test_net__test_address_in_use_str,
)
from test_net import (
    test_address_parse_error_str as test_net__test_address_parse_error_str,
)
from test_net import (
    test_address_parse_error_preserves_injection_attempt as test_net__test_address_parse_error_preserves_injection_attempt,
)
from test_net import (
    test_broken_pipe_no_addr as test_net__test_broken_pipe_no_addr,
)
from test_net import (
    test_broken_pipe_with_addr as test_net__test_broken_pipe_with_addr,
)
from test_net import test_dns_error_str as test_net__test_dns_error_str
from test_net import (
    test_dns_error_zero_code as test_net__test_dns_error_zero_code,
)


def main() raises:
    var suite = TestSuite()
    # tests/net/test_net.mojo
    suite.test[test_net__test_ip_addr_localhost]()
    suite.test[test_net__test_ip_addr_localhost_v6]()
    suite.test[test_net__test_ip_addr_unspecified_v4]()
    suite.test[test_net__test_ip_addr_unspecified_v6]()
    suite.test[test_net__test_ip_addr_broadcast]()
    suite.test[test_net__test_ip_addr_min_octet]()
    suite.test[test_net__test_ip_addr_private_10]()
    suite.test[test_net__test_ip_addr_private_172]()
    suite.test[test_net__test_ip_addr_private_192]()
    suite.test[test_net__test_ip_addr_not_private_public]()
    suite.test[test_net__test_ip_addr_not_private_172_boundary_below]()
    suite.test[test_net__test_ip_addr_not_private_172_boundary_above]()
    suite.test[test_net__test_ip_addr_loopback_127_any]()
    suite.test[test_net__test_ip_addr_loopback_v6]()
    suite.test[test_net__test_ip_addr_v6_loopback_full]()
    suite.test[test_net__test_ip_addr_v6_compressed]()
    suite.test[test_net__test_ip_addr_v6_all_zeros_long]()
    suite.test[test_net__test_ip_addr_v6_link_local]()
    suite.test[test_net__test_ip_addr_equality_v4]()
    suite.test[test_net__test_ip_addr_inequality_v4]()
    suite.test[test_net__test_ip_addr_v4_not_equal_v6]()
    suite.test[test_net__test_ip_addr_parse_too_many_octets_raises]()
    suite.test[test_net__test_ip_addr_parse_octet_overflow_raises]()
    suite.test[test_net__test_ip_addr_parse_negative_octet_raises]()
    suite.test[test_net__test_ip_addr_parse_empty_raises]()
    suite.test[test_net__test_ip_addr_parse_alpha_raises]()
    suite.test[test_net__test_ip_addr_parse_hex_no_prefix_raises]()
    suite.test[test_net__test_ip_addr_parse_newline_injection_raises]()
    suite.test[test_net__test_ip_addr_parse_null_byte_raises]()
    suite.test[test_net__test_socket_addr_str]()
    suite.test[test_net__test_socket_addr_localhost]()
    suite.test[test_net__test_socket_addr_unspecified]()
    suite.test[test_net__test_socket_addr_max_port]()
    suite.test[test_net__test_socket_addr_port_zero]()
    suite.test[test_net__test_socket_addr_port_well_known_http]()
    suite.test[test_net__test_socket_addr_port_well_known_https]()
    suite.test[test_net__test_socket_addr_parse_v4]()
    suite.test[test_net__test_socket_addr_parse_ipv6]()
    suite.test[test_net__test_socket_addr_equality]()
    suite.test[test_net__test_socket_addr_inequality_port]()
    suite.test[test_net__test_socket_addr_inequality_ip]()
    suite.test[test_net__test_socket_addr_parse_missing_port_raises]()
    suite.test[test_net__test_socket_addr_parse_bad_ip_raises]()
    suite.test[test_net__test_socket_addr_parse_empty_raises]()
    suite.test[test_net__test_socket_addr_parse_newline_injection_raises]()
    suite.test[test_net__test_network_error_str_no_code]()
    suite.test[test_net__test_network_error_str_with_code]()
    suite.test[test_net__test_network_error_message_preserved]()
    suite.test[test_net__test_connection_refused_str]()
    suite.test[test_net__test_connection_timeout_str]()
    suite.test[test_net__test_address_in_use_str]()
    suite.test[test_net__test_address_parse_error_str]()
    suite.test[test_net__test_address_parse_error_preserves_injection_attempt]()
    suite.test[test_net__test_broken_pipe_no_addr]()
    suite.test[test_net__test_broken_pipe_with_addr]()
    suite.test[test_net__test_dns_error_str]()
    suite.test[test_net__test_dns_error_zero_code]()
    suite^.run()
