"""GENERATED by tests/tools/gen_test_aggregates.py -- do not edit.

Aggregates the 9 test files of ``tests/ws/`` into one compiled
binary so the 9 separate compiler invocations become one. Run it with
``mojo -I . -I tests/ws`` (see tests/tools/run_test_aggregates.sh).

Regenerate with ``python3 tests/tools/gen_test_aggregates.py``; CI fails if this
file is out of date with the tree.
"""

from std.testing import TestSuite
from test_ws import test_text_frame_opcode as test_ws__test_text_frame_opcode
from test_ws import (
    test_binary_frame_opcode as test_ws__test_binary_frame_opcode,
)
from test_ws import test_ping_frame_opcode as test_ws__test_ping_frame_opcode
from test_ws import test_pong_frame_opcode as test_ws__test_pong_frame_opcode
from test_ws import test_close_frame_opcode as test_ws__test_close_frame_opcode
from test_ws import (
    test_close_frame_payload as test_ws__test_close_frame_payload,
)
from test_ws import (
    test_close_frame_with_reason as test_ws__test_close_frame_with_reason,
)
from test_ws import (
    test_is_control_data_frames as test_ws__test_is_control_data_frames,
)
from test_ws import test_opcode_values as test_ws__test_opcode_values
from test_ws import test_close_code_values as test_ws__test_close_code_values
from test_ws import (
    test_encode_small_frame_header as test_ws__test_encode_small_frame_header,
)
from test_ws import (
    test_encode_empty_payload as test_ws__test_encode_empty_payload,
)
from test_ws import (
    test_encode_126_byte_payload as test_ws__test_encode_126_byte_payload,
)
from test_ws import (
    test_encode_with_zero_mask as test_ws__test_encode_with_zero_mask,
)
from test_ws import test_encode_rsv1_raises as test_ws__test_encode_rsv1_raises
from test_ws import (
    test_encode_control_oversized_raises as test_ws__test_encode_control_oversized_raises,
)
from test_ws import (
    test_decode_small_text_frame as test_ws__test_decode_small_text_frame,
)
from test_ws import test_decode_empty_ping as test_ws__test_decode_empty_ping
from test_ws import (
    test_decode_16bit_length as test_ws__test_decode_16bit_length,
)
from test_ws import (
    test_decode_masked_frame as test_ws__test_decode_masked_frame,
)
from test_ws import (
    test_decode_truncated_raises as test_ws__test_decode_truncated_raises,
)
from test_ws import (
    test_decode_fragmented_control_raises as test_ws__test_decode_fragmented_control_raises,
)
from test_ws import (
    test_encode_decode_roundtrip_text as test_ws__test_encode_decode_roundtrip_text,
)
from test_ws import (
    test_encode_decode_roundtrip_text_utf8 as test_ws__test_encode_decode_roundtrip_text_utf8,
)
from test_ws import (
    test_encode_decode_roundtrip_binary as test_ws__test_encode_decode_roundtrip_binary,
)
from test_ws import (
    test_encode_decode_roundtrip_masked as test_ws__test_encode_decode_roundtrip_masked,
)
from test_ws import (
    test_encode_decode_126_bytes as test_ws__test_encode_decode_126_bytes,
)
from test_ws import (
    test_consumed_with_trailing_data as test_ws__test_consumed_with_trailing_data,
)
from test_ws import (
    test_ws_protocol_error_str as test_ws__test_ws_protocol_error_str,
)
from test_ws import test_ws_connect_plain as test_ws__test_ws_connect_plain
from test_ws import test_ws_echo_roundtrip as test_ws__test_ws_echo_roundtrip
from test_ws import (
    test_ws_server_text_echo_loopback as test_ws__test_ws_server_text_echo_loopback,
)
from test_ws import (
    test_ws_server_binary_echo_loopback as test_ws__test_ws_server_binary_echo_loopback,
)
from test_ws import (
    test_ws_server_unmasked_frame_rejected as test_ws__test_ws_server_unmasked_frame_rejected,
)
from test_ws import (
    test_upgrade_parse_captures_origin as test_ws__test_upgrade_parse_captures_origin,
)
from test_ws import (
    test_upgrade_parse_origin_absent_is_empty as test_ws__test_upgrade_parse_origin_absent_is_empty,
)
from test_ws import (
    test_upgrade_parse_origin_header_name_case_insensitive as test_ws__test_upgrade_parse_origin_header_name_case_insensitive,
)
from test_ws import (
    test_ws_connection_carries_handshake_origin as test_ws__test_ws_connection_carries_handshake_origin,
)
from test_ws_autoclient import (
    test_wire_choice_codepoints as test_ws_autoclient__test_wire_choice_codepoints,
)
from test_ws_autoclient import (
    test_config_defaults as test_ws_autoclient__test_config_defaults,
)
from test_ws_autoclient import (
    test_decide_wire_cleartext_ws_skips_h2 as test_ws_autoclient__test_decide_wire_cleartext_ws_skips_h2,
)
from test_ws_autoclient import (
    test_decide_wire_wss_prefer_h2_false_forces_h1 as test_ws_autoclient__test_decide_wire_wss_prefer_h2_false_forces_h1,
)
from test_ws_autoclient import (
    test_decide_wire_wss_h2_alpn_with_connect_protocol as test_ws_autoclient__test_decide_wire_wss_h2_alpn_with_connect_protocol,
)
from test_ws_autoclient import (
    test_decide_wire_wss_h2_alpn_without_connect_protocol as test_ws_autoclient__test_decide_wire_wss_h2_alpn_without_connect_protocol,
)
from test_ws_autoclient import (
    test_decide_wire_wss_http11_alpn as test_ws_autoclient__test_decide_wire_wss_http11_alpn,
)
from test_ws_autoclient import (
    test_decide_wire_wss_no_alpn as test_ws_autoclient__test_decide_wire_wss_no_alpn,
)
from test_ws_autoclient import (
    test_decide_wire_unknown_alpn_fails as test_ws_autoclient__test_decide_wire_unknown_alpn_fails,
)
from test_ws_autoclient import (
    test_decide_wire_invalid_scheme_fails as test_ws_autoclient__test_decide_wire_invalid_scheme_fails,
)
from test_ws_autoclient import (
    test_url_scheme_parses_wss as test_ws_autoclient__test_url_scheme_parses_wss,
)
from test_ws_autoclient import (
    test_url_scheme_parses_ws as test_ws_autoclient__test_url_scheme_parses_ws,
)
from test_ws_autoclient import (
    test_connect_unreachable_host_surfaces_failure as test_ws_autoclient__test_connect_unreachable_host_surfaces_failure,
)
from test_ws_autoclient import (
    test_take_methods_guard_state as test_ws_autoclient__test_take_methods_guard_state,
)
from test_ws_autoclient_loopback import (
    test_ws_autoclient_loopback_default_prefer_h2 as test_ws_autoclient_loopback__test_ws_autoclient_loopback_default_prefer_h2,
)
from test_ws_autoclient_loopback import (
    test_ws_autoclient_loopback_prefer_h2_false as test_ws_autoclient_loopback__test_ws_autoclient_loopback_prefer_h2_false,
)
from test_ws_autoclient_loopback import (
    test_ws_autoclient_loopback_binary_round_trip as test_ws_autoclient_loopback__test_ws_autoclient_loopback_binary_round_trip,
)
from test_ws_autoclient_loopback import (
    test_ws_autoclient_wss_unreachable_local_port as test_ws_autoclient_loopback__test_ws_autoclient_wss_unreachable_local_port,
)
from test_ws_h2 import (
    test_bootstrap_raises_when_peer_did_not_advertise_8441 as test_ws_h2__test_bootstrap_raises_when_peer_did_not_advertise_8441,
)
from test_ws_h2 import (
    test_peer_settings_mid_handshake_unblocks_bootstrap as test_ws_h2__test_peer_settings_mid_handshake_unblocks_bootstrap,
)
from test_ws_h2 import (
    test_bootstrap_emits_extended_connect_headers_no_end_stream as test_ws_h2__test_bootstrap_emits_extended_connect_headers_no_end_stream,
)
from test_ws_h2 import (
    test_send_frame_emits_data_frame_carrying_ws_wire as test_ws_h2__test_send_frame_emits_data_frame_carrying_ws_wire,
)
from test_ws_h2 import (
    test_pull_frames_split_across_data_arrivals as test_ws_h2__test_pull_frames_split_across_data_arrivals,
)
from test_ws_h2 import (
    test_close_emits_close_frame_with_end_stream_and_locks_send as test_ws_h2__test_close_emits_close_frame_with_end_stream_and_locks_send,
)
from test_ws_h2_reactor import (
    test_ws_h2_reactor as test_ws_h2_reactor__test_ws_h2_reactor,
)
from test_ws_h2_roundtrip import (
    test_ws_h2_roundtrip as test_ws_h2_roundtrip__test_ws_h2_roundtrip,
)
from test_ws_multicore import (
    test_ws_multicore_serve_4_workers_echo_round_trip as test_ws_multicore__test_ws_multicore_serve_4_workers_echo_round_trip,
)
from test_ws_permessage_deflate import (
    test_parse_simple_offer_round_trips as test_ws_permessage_deflate__test_parse_simple_offer_round_trips,
)
from test_ws_permessage_deflate import (
    test_parse_handles_flags_kv_quoted_values_multi_offer as test_ws_permessage_deflate__test_parse_handles_flags_kv_quoted_values_multi_offer,
)
from test_ws_permessage_deflate import (
    test_negotiate_picks_first_pmd_offer_and_locks_no_context_takeover as test_ws_permessage_deflate__test_negotiate_picks_first_pmd_offer_and_locks_no_context_takeover,
)
from test_ws_permessage_deflate import (
    test_negotiate_returns_none_when_no_offer_matches as test_ws_permessage_deflate__test_negotiate_returns_none_when_no_offer_matches,
)
from test_ws_permessage_deflate import (
    test_compress_decompress_round_trip_utf8_payload as test_ws_permessage_deflate__test_compress_decompress_round_trip_utf8_payload,
)
from test_ws_permessage_deflate import (
    test_compress_empty_payload_emits_single_byte_and_decompress_rejects as test_ws_permessage_deflate__test_compress_empty_payload_emits_single_byte_and_decompress_rejects,
)
from test_ws_permessage_deflate import (
    test_decompress_respects_max_decompressed_bytes_cap as test_ws_permessage_deflate__test_decompress_respects_max_decompressed_bytes_cap,
)
from test_ws_permessage_deflate import (
    test_offer_emit_reflects_config_flags as test_ws_permessage_deflate__test_offer_emit_reflects_config_flags,
)
from test_ws_permessage_deflate import (
    test_context_takeover_round_trips_three_messages as test_ws_permessage_deflate__test_context_takeover_round_trips_three_messages,
)
from test_ws_permessage_deflate import (
    test_context_takeover_compresses_repeated_payload_better_than_no_context as test_ws_permessage_deflate__test_context_takeover_compresses_repeated_payload_better_than_no_context,
)
from test_ws_permessage_deflate import (
    test_context_takeover_empty_payload_round_trips as test_ws_permessage_deflate__test_context_takeover_empty_payload_round_trips,
)
from test_ws_permessage_deflate import (
    test_context_takeover_respects_max_decompressed_bytes as test_ws_permessage_deflate__test_context_takeover_respects_max_decompressed_bytes,
)
from test_ws_stateful_handler import (
    test_ws_stateful_handler as test_ws_stateful_handler__test_ws_stateful_handler,
)


def main() raises:
    var suite = TestSuite()
    # tests/ws/test_ws.mojo
    suite.test[test_ws__test_text_frame_opcode]()
    suite.test[test_ws__test_binary_frame_opcode]()
    suite.test[test_ws__test_ping_frame_opcode]()
    suite.test[test_ws__test_pong_frame_opcode]()
    suite.test[test_ws__test_close_frame_opcode]()
    suite.test[test_ws__test_close_frame_payload]()
    suite.test[test_ws__test_close_frame_with_reason]()
    suite.test[test_ws__test_is_control_data_frames]()
    suite.test[test_ws__test_opcode_values]()
    suite.test[test_ws__test_close_code_values]()
    suite.test[test_ws__test_encode_small_frame_header]()
    suite.test[test_ws__test_encode_empty_payload]()
    suite.test[test_ws__test_encode_126_byte_payload]()
    suite.test[test_ws__test_encode_with_zero_mask]()
    suite.test[test_ws__test_encode_rsv1_raises]()
    suite.test[test_ws__test_encode_control_oversized_raises]()
    suite.test[test_ws__test_decode_small_text_frame]()
    suite.test[test_ws__test_decode_empty_ping]()
    suite.test[test_ws__test_decode_16bit_length]()
    suite.test[test_ws__test_decode_masked_frame]()
    suite.test[test_ws__test_decode_truncated_raises]()
    suite.test[test_ws__test_decode_fragmented_control_raises]()
    suite.test[test_ws__test_encode_decode_roundtrip_text]()
    suite.test[test_ws__test_encode_decode_roundtrip_text_utf8]()
    suite.test[test_ws__test_encode_decode_roundtrip_binary]()
    suite.test[test_ws__test_encode_decode_roundtrip_masked]()
    suite.test[test_ws__test_encode_decode_126_bytes]()
    suite.test[test_ws__test_consumed_with_trailing_data]()
    suite.test[test_ws__test_ws_protocol_error_str]()
    suite.test[test_ws__test_ws_connect_plain]()
    suite.test[test_ws__test_ws_echo_roundtrip]()
    suite.test[test_ws__test_ws_server_text_echo_loopback]()
    suite.test[test_ws__test_ws_server_binary_echo_loopback]()
    suite.test[test_ws__test_ws_server_unmasked_frame_rejected]()
    suite.test[test_ws__test_upgrade_parse_captures_origin]()
    suite.test[test_ws__test_upgrade_parse_origin_absent_is_empty]()
    suite.test[
        test_ws__test_upgrade_parse_origin_header_name_case_insensitive
    ]()
    suite.test[test_ws__test_ws_connection_carries_handshake_origin]()
    # tests/ws/test_ws_autoclient.mojo
    suite.test[test_ws_autoclient__test_wire_choice_codepoints]()
    suite.test[test_ws_autoclient__test_config_defaults]()
    suite.test[test_ws_autoclient__test_decide_wire_cleartext_ws_skips_h2]()
    suite.test[
        test_ws_autoclient__test_decide_wire_wss_prefer_h2_false_forces_h1
    ]()
    suite.test[
        test_ws_autoclient__test_decide_wire_wss_h2_alpn_with_connect_protocol
    ]()
    suite.test[
        test_ws_autoclient__test_decide_wire_wss_h2_alpn_without_connect_protocol
    ]()
    suite.test[test_ws_autoclient__test_decide_wire_wss_http11_alpn]()
    suite.test[test_ws_autoclient__test_decide_wire_wss_no_alpn]()
    suite.test[test_ws_autoclient__test_decide_wire_unknown_alpn_fails]()
    suite.test[test_ws_autoclient__test_decide_wire_invalid_scheme_fails]()
    suite.test[test_ws_autoclient__test_url_scheme_parses_wss]()
    suite.test[test_ws_autoclient__test_url_scheme_parses_ws]()
    suite.test[
        test_ws_autoclient__test_connect_unreachable_host_surfaces_failure
    ]()
    suite.test[test_ws_autoclient__test_take_methods_guard_state]()
    # tests/ws/test_ws_autoclient_loopback.mojo
    suite.test[
        test_ws_autoclient_loopback__test_ws_autoclient_loopback_default_prefer_h2
    ]()
    suite.test[
        test_ws_autoclient_loopback__test_ws_autoclient_loopback_prefer_h2_false
    ]()
    suite.test[
        test_ws_autoclient_loopback__test_ws_autoclient_loopback_binary_round_trip
    ]()
    suite.test[
        test_ws_autoclient_loopback__test_ws_autoclient_wss_unreachable_local_port
    ]()
    # tests/ws/test_ws_h2.mojo
    suite.test[
        test_ws_h2__test_bootstrap_raises_when_peer_did_not_advertise_8441
    ]()
    suite.test[
        test_ws_h2__test_peer_settings_mid_handshake_unblocks_bootstrap
    ]()
    suite.test[
        test_ws_h2__test_bootstrap_emits_extended_connect_headers_no_end_stream
    ]()
    suite.test[test_ws_h2__test_send_frame_emits_data_frame_carrying_ws_wire]()
    suite.test[test_ws_h2__test_pull_frames_split_across_data_arrivals]()
    suite.test[
        test_ws_h2__test_close_emits_close_frame_with_end_stream_and_locks_send
    ]()
    # tests/ws/test_ws_h2_reactor.mojo
    suite.test[test_ws_h2_reactor__test_ws_h2_reactor]()
    # tests/ws/test_ws_h2_roundtrip.mojo
    suite.test[test_ws_h2_roundtrip__test_ws_h2_roundtrip]()
    # tests/ws/test_ws_multicore.mojo
    suite.test[
        test_ws_multicore__test_ws_multicore_serve_4_workers_echo_round_trip
    ]()
    # tests/ws/test_ws_permessage_deflate.mojo
    suite.test[
        test_ws_permessage_deflate__test_parse_simple_offer_round_trips
    ]()
    suite.test[
        test_ws_permessage_deflate__test_parse_handles_flags_kv_quoted_values_multi_offer
    ]()
    suite.test[
        test_ws_permessage_deflate__test_negotiate_picks_first_pmd_offer_and_locks_no_context_takeover
    ]()
    suite.test[
        test_ws_permessage_deflate__test_negotiate_returns_none_when_no_offer_matches
    ]()
    suite.test[
        test_ws_permessage_deflate__test_compress_decompress_round_trip_utf8_payload
    ]()
    suite.test[
        test_ws_permessage_deflate__test_compress_empty_payload_emits_single_byte_and_decompress_rejects
    ]()
    suite.test[
        test_ws_permessage_deflate__test_decompress_respects_max_decompressed_bytes_cap
    ]()
    suite.test[
        test_ws_permessage_deflate__test_offer_emit_reflects_config_flags
    ]()
    suite.test[
        test_ws_permessage_deflate__test_context_takeover_round_trips_three_messages
    ]()
    suite.test[
        test_ws_permessage_deflate__test_context_takeover_compresses_repeated_payload_better_than_no_context
    ]()
    suite.test[
        test_ws_permessage_deflate__test_context_takeover_empty_payload_round_trips
    ]()
    suite.test[
        test_ws_permessage_deflate__test_context_takeover_respects_max_decompressed_bytes
    ]()
    # tests/ws/test_ws_stateful_handler.mojo
    suite.test[test_ws_stateful_handler__test_ws_stateful_handler]()
    suite^.run()
