"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 3 test files of ``tests/conformance/`` into one compiled
binary so the 3 separate compiler invocations become one. Run it with
``mojo -I . -I tests/conformance`` (see tools/run_test_aggregates.sh).

Regenerate with ``python3 tools/gen_test_aggregates.py``; CI fails if this
file is out of date with the tree.
"""

from std.testing import TestSuite
from test_conformance_h1 import (
    test_directory_exists as test_conformance_h1__test_directory_exists,
)
from test_conformance_h1 import (
    test_all_h1_fixtures_validate as test_conformance_h1__test_all_h1_fixtures_validate,
)
from test_conformance_h1 import (
    test_leniency_overlay_flips_strict_default as test_conformance_h1__test_leniency_overlay_flips_strict_default,
)
from test_conformance_h1 import (
    test_strict_overlay_keeps_strict as test_conformance_h1__test_strict_overlay_keeps_strict,
)
from test_conformance_h3_server import (
    test_rfc9114_get_minimal_round_trip as test_conformance_h3_server__test_rfc9114_get_minimal_round_trip,
)
from test_conformance_h3_server import (
    test_aioquic_post_body_round_trip as test_conformance_h3_server__test_aioquic_post_body_round_trip,
)
from test_conformance_h3_server import (
    test_quiche_multi_data_chunks_assemble as test_conformance_h3_server__test_quiche_multi_data_chunks_assemble,
)
from test_conformance_h3_server import (
    test_split_feed_reassembles_request as test_conformance_h3_server__test_split_feed_reassembles_request,
)
from test_conformance_h3_server import (
    test_response_round_trips_through_writer as test_conformance_h3_server__test_response_round_trips_through_writer,
)
from test_conformance_h3_server import (
    test_idempotent_take_request_after_round_trip as test_conformance_h3_server__test_idempotent_take_request_after_round_trip,
)
from test_conformance_h3_server import (
    test_truncated_headers_does_not_complete as test_conformance_h3_server__test_truncated_headers_does_not_complete,
)
from test_conformance_ws import (
    test_directory_exists as test_conformance_ws__test_directory_exists,
)
from test_conformance_ws import (
    test_all_ws_fixtures_validate as test_conformance_ws__test_all_ws_fixtures_validate,
)
from test_conformance_ws import (
    test_accept_and_reject_fixtures_both_present as test_conformance_ws__test_accept_and_reject_fixtures_both_present,
)


def main() raises:
    var suite = TestSuite()
    # tests/conformance/test_conformance_h1.mojo
    suite.test[test_conformance_h1__test_directory_exists]()
    suite.test[test_conformance_h1__test_all_h1_fixtures_validate]()
    suite.test[
        test_conformance_h1__test_leniency_overlay_flips_strict_default
    ]()
    suite.test[test_conformance_h1__test_strict_overlay_keeps_strict]()
    # tests/conformance/test_conformance_h3_server.mojo
    suite.test[
        test_conformance_h3_server__test_rfc9114_get_minimal_round_trip
    ]()
    suite.test[test_conformance_h3_server__test_aioquic_post_body_round_trip]()
    suite.test[
        test_conformance_h3_server__test_quiche_multi_data_chunks_assemble
    ]()
    suite.test[
        test_conformance_h3_server__test_split_feed_reassembles_request
    ]()
    suite.test[
        test_conformance_h3_server__test_response_round_trips_through_writer
    ]()
    suite.test[
        test_conformance_h3_server__test_idempotent_take_request_after_round_trip
    ]()
    suite.test[
        test_conformance_h3_server__test_truncated_headers_does_not_complete
    ]()
    # tests/conformance/test_conformance_ws.mojo
    suite.test[test_conformance_ws__test_directory_exists]()
    suite.test[test_conformance_ws__test_all_ws_fixtures_validate]()
    suite.test[
        test_conformance_ws__test_accept_and_reject_fixtures_both_present
    ]()
    suite^.run()
