"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 14 test files of ``tests/h3/`` into one compiled
binary so the 14 separate compiler invocations become one. Run it with
``mojo -I . -I tests/h3`` (see tools/run_test_aggregates.sh).

Regenerate with ``python3 tools/gen_test_aggregates.py``; CI fails if this
file is out of date with the tree.
"""

from std.testing import TestSuite
from test_frame import (
    test_data_frame_round_trip as test_frame__test_data_frame_round_trip,
)
from test_frame import (
    test_headers_frame_round_trip as test_frame__test_headers_frame_round_trip,
)
from test_frame import (
    test_settings_frame_payload_round_trip as test_frame__test_settings_frame_payload_round_trip,
)
from test_frame import (
    test_settings_frame_complete_wrap as test_frame__test_settings_frame_complete_wrap,
)
from test_frame import (
    test_empty_payload_round_trip as test_frame__test_empty_payload_round_trip,
)
from test_frame import (
    test_unknown_frame_type_accepted as test_frame__test_unknown_frame_type_accepted,
)
from test_frame import (
    test_grease_frame_type_detection as test_frame__test_grease_frame_type_detection,
)
from test_frame import (
    test_decoder_rejects_truncated_payload as test_frame__test_decoder_rejects_truncated_payload,
)
from test_frame import (
    test_decoder_rejects_empty_buffer as test_frame__test_decoder_rejects_empty_buffer,
)
from test_frame import (
    test_settings_decoder_rejects_dangling_identifier as test_frame__test_settings_decoder_rejects_dangling_identifier,
)
from test_h3_0rtt_gate import (
    test_idempotent_methods_eligible as test_h3_0rtt_gate__test_idempotent_methods_eligible,
)
from test_h3_0rtt_gate import (
    test_non_idempotent_methods_excluded as test_h3_0rtt_gate__test_non_idempotent_methods_excluded,
)
from test_h3_0rtt_gate import (
    test_method_classification_case_insensitive as test_h3_0rtt_gate__test_method_classification_case_insensitive,
)
from test_h3_0rtt_gate import (
    test_outcome_carrier_fields as test_h3_0rtt_gate__test_outcome_carrier_fields,
)
from test_h3_client_e2e import test_h3_get as test_h3_client_e2e__test_h3_get
from test_h3_client_e2e import (
    test_h3_post_echo as test_h3_client_e2e__test_h3_post_echo,
)
from test_h3_client_e2e import (
    test_h3_stream_body as test_h3_client_e2e__test_h3_stream_body,
)
from test_h3_client_frag import (
    test_large_body_fragments as test_h3_client_frag__test_large_body_fragments,
)
from test_h3_client_frag import (
    test_idle_then_reuse as test_h3_client_frag__test_idle_then_reuse,
)
from test_h3_client_mux import (
    test_two_concurrent_requests as test_h3_client_mux__test_two_concurrent_requests,
)
from test_h3_client_reasm import (
    test_out_of_order_with_dup_and_gap as test_h3_client_reasm__test_out_of_order_with_dup_and_gap,
)
from test_h3_client_reasm import (
    test_overlapping_chunk_trimmed as test_h3_client_reasm__test_overlapping_chunk_trimmed,
)
from test_h3_client_reasm import (
    test_in_order_fast_path as test_h3_client_reasm__test_in_order_fast_path,
)
from test_h3_client_streams import (
    test_request_roundtrip_into_server_reader as test_h3_client_streams__test_request_roundtrip_into_server_reader,
)
from test_h3_client_streams import (
    test_get_request_no_body as test_h3_client_streams__test_get_request_no_body,
)
from test_h3_client_streams import (
    test_response_roundtrip_into_client_reader as test_h3_client_streams__test_response_roundtrip_into_client_reader,
)
from test_h3_client_streams import (
    test_response_reader_rejects_control_frame as test_h3_client_streams__test_response_reader_rejects_control_frame,
)
from test_h3_client_streams import (
    test_control_stream_preamble_is_settings_first as test_h3_client_streams__test_control_stream_preamble_is_settings_first,
)
from test_h3_client_streams import (
    test_qpack_stream_preambles as test_h3_client_streams__test_qpack_stream_preambles,
)
from test_h3_dispatch import (
    test_feed_stream_chunk_implicit_open as test_h3_dispatch__test_feed_stream_chunk_implicit_open,
)
from test_h3_dispatch import (
    test_get_request_surfaces_after_fin as test_h3_dispatch__test_get_request_surfaces_after_fin,
)
from test_h3_dispatch import (
    test_take_request_assembles_method_and_path as test_h3_dispatch__test_take_request_assembles_method_and_path,
)
from test_h3_dispatch import (
    test_take_request_body_round_trip as test_h3_dispatch__test_take_request_body_round_trip,
)
from test_h3_dispatch import (
    test_take_request_is_idempotent_guarded as test_h3_dispatch__test_take_request_is_idempotent_guarded,
)
from test_h3_dispatch import (
    test_emit_response_buffers_headers_and_data as test_h3_dispatch__test_emit_response_buffers_headers_and_data,
)
from test_h3_dispatch import (
    test_take_response_frames_drains_once as test_h3_dispatch__test_take_response_frames_drains_once,
)
from test_h3_dispatch import (
    test_emit_response_is_idempotent_guarded as test_h3_dispatch__test_emit_response_is_idempotent_guarded,
)
from test_h3_dispatch import (
    test_garbled_chunk_sets_protocol_error as test_h3_dispatch__test_garbled_chunk_sets_protocol_error,
)
from test_h3_dispatch import (
    test_partial_chunk_needs_more_then_completes as test_h3_dispatch__test_partial_chunk_needs_more_then_completes,
)
from test_h3_end_to_end import (
    test_get_request_dispatches_through_handler as test_h3_end_to_end__test_get_request_dispatches_through_handler,
)
from test_h3_end_to_end import (
    test_post_request_body_echo as test_h3_end_to_end__test_post_request_body_echo,
)
from test_h3_end_to_end import (
    test_concurrent_streams_on_one_connection as test_h3_end_to_end__test_concurrent_streams_on_one_connection,
)
from test_h3_end_to_end import (
    test_multiple_connections_dispatch_independently as test_h3_end_to_end__test_multiple_connections_dispatch_independently,
)
from test_h3_end_to_end import (
    test_pump_http3_handler_once_drives_handler as test_h3_end_to_end__test_pump_http3_handler_once_drives_handler,
)
from test_h3_end_to_end import (
    test_pump_http3_handler_once_zero_when_no_streams_ready as test_h3_end_to_end__test_pump_http3_handler_once_zero_when_no_streams_ready,
)
from test_h3_end_to_end import (
    test_streaming_response_incremental_data as test_h3_end_to_end__test_streaming_response_incremental_data,
)
from test_h3_end_to_end import (
    test_buffered_response_not_registered_as_stream as test_h3_end_to_end__test_buffered_response_not_registered_as_stream,
)
from test_h3_qpack_dynamic import (
    test_encoder_stream_inserts_owe_increment as test_h3_qpack_dynamic__test_encoder_stream_inserts_owe_increment,
)
from test_h3_qpack_dynamic import (
    test_request_resolves_dynamic_reference as test_h3_qpack_dynamic__test_request_resolves_dynamic_reference,
)
from test_h3_qpack_dynamic import (
    test_split_encoder_chunk_buffers_then_applies as test_h3_qpack_dynamic__test_split_encoder_chunk_buffers_then_applies,
)
from test_h3_uni_streams import (
    test_peer_control_stream_settings_round_trip as test_h3_uni_streams__test_peer_control_stream_settings_round_trip,
)
from test_h3_uni_streams import (
    test_uni_stream_type_varint_split_across_chunks as test_h3_uni_streams__test_uni_stream_type_varint_split_across_chunks,
)
from test_h3_uni_streams import (
    test_qpack_uni_stream_kinds_are_recorded as test_h3_uni_streams__test_qpack_uni_stream_kinds_are_recorded,
)
from test_h3_uni_streams import (
    test_push_uni_stream_tolerated as test_h3_uni_streams__test_push_uni_stream_tolerated,
)
from test_h3_uni_streams import (
    test_grease_uni_stream_codepoint_tolerated as test_h3_uni_streams__test_grease_uni_stream_codepoint_tolerated,
)
from test_h3_uni_streams import (
    test_settings_twice_is_frame_unexpected as test_h3_uni_streams__test_settings_twice_is_frame_unexpected,
)
from test_h3_uni_streams import (
    test_non_settings_before_settings_is_missing_settings as test_h3_uni_streams__test_non_settings_before_settings_is_missing_settings,
)
from test_h3_uni_streams import (
    test_goaway_records_peer_max_stream_id as test_h3_uni_streams__test_goaway_records_peer_max_stream_id,
)
from test_h3_uni_streams import (
    test_second_peer_control_stream_raises as test_h3_uni_streams__test_second_peer_control_stream_raises,
)
from test_h3_uni_streams import (
    test_emit_initial_settings_round_trips as test_h3_uni_streams__test_emit_initial_settings_round_trips,
)
from test_h3_uni_streams import (
    test_emit_goaway_flips_flag_and_double_emit_raises as test_h3_uni_streams__test_emit_goaway_flips_flag_and_double_emit_raises,
)
from test_request_reader import (
    test_initial_state as test_request_reader__test_initial_state,
)
from test_request_reader import (
    test_headers_only as test_request_reader__test_headers_only,
)
from test_request_reader import (
    test_headers_then_data as test_request_reader__test_headers_then_data,
)
from test_request_reader import (
    test_headers_then_data_then_trailers as test_request_reader__test_headers_then_data_then_trailers,
)
from test_request_reader import (
    test_data_before_headers_is_protocol_error as test_request_reader__test_data_before_headers_is_protocol_error,
)
from test_request_reader import (
    test_control_frame_on_request_stream_is_protocol_error as test_request_reader__test_control_frame_on_request_stream_is_protocol_error,
)
from test_request_reader import (
    test_truncated_frame_yields_needs_more as test_request_reader__test_truncated_frame_yields_needs_more,
)
from test_request_reader import (
    test_unknown_frame_type_is_skipped as test_request_reader__test_unknown_frame_type_is_skipped,
)
from test_request_reader import (
    test_oversized_headers_is_protocol_error as test_request_reader__test_oversized_headers_is_protocol_error,
)
from test_request_reader import (
    test_repeat_headers_after_trailers_is_protocol_error as test_request_reader__test_repeat_headers_after_trailers_is_protocol_error,
)
from test_response_writer import (
    test_status_only as test_response_writer__test_status_only,
)
from test_response_writer import (
    test_status_with_application_headers as test_response_writer__test_status_with_application_headers,
)
from test_response_writer import (
    test_invalid_status_raises as test_response_writer__test_invalid_status_raises,
)
from test_response_writer import (
    test_pseudo_header_in_application_headers_raises as test_response_writer__test_pseudo_header_in_application_headers_raises,
)
from test_response_writer import (
    test_data_frame_round_trip as test_response_writer__test_data_frame_round_trip,
)
from test_response_writer import (
    test_trailers_round_trip as test_response_writer__test_trailers_round_trip,
)
from test_response_writer import (
    test_pseudo_header_in_trailers_raises as test_response_writer__test_pseudo_header_in_trailers_raises,
)
from test_server_scaffold import (
    test_stream_type_codepoints as test_server_scaffold__test_stream_type_codepoints,
)
from test_server_scaffold import (
    test_config_defaults as test_server_scaffold__test_config_defaults,
)
from test_server_scaffold import (
    test_h3_connection_defaults as test_server_scaffold__test_h3_connection_defaults,
)
from test_server_scaffold import (
    test_with_config_overrides as test_server_scaffold__test_with_config_overrides,
)
from test_server_scaffold import (
    test_open_request_stream_tracks_state as test_server_scaffold__test_open_request_stream_tracks_state,
)
from test_server_scaffold import (
    test_open_request_stream_is_idempotent as test_server_scaffold__test_open_request_stream_is_idempotent,
)
from test_server_scaffold import (
    test_close_request_stream_releases as test_server_scaffold__test_close_request_stream_releases,
)
from test_server_scaffold import (
    test_close_request_stream_unknown_id_is_noop as test_server_scaffold__test_close_request_stream_unknown_id_is_noop,
)
from test_server_scaffold import (
    test_goaway_rejects_new_streams as test_server_scaffold__test_goaway_rejects_new_streams,
)
from test_server_scaffold import (
    test_feed_stream_chunk_allocates_stream_implicitly as test_server_scaffold__test_feed_stream_chunk_allocates_stream_implicitly,
)
from test_server_scaffold import (
    test_take_response_frames_empty_when_no_emit as test_server_scaffold__test_take_response_frames_empty_when_no_emit,
)


def main() raises:
    var suite = TestSuite()
    # tests/h3/test_frame.mojo
    suite.test[test_frame__test_data_frame_round_trip]()
    suite.test[test_frame__test_headers_frame_round_trip]()
    suite.test[test_frame__test_settings_frame_payload_round_trip]()
    suite.test[test_frame__test_settings_frame_complete_wrap]()
    suite.test[test_frame__test_empty_payload_round_trip]()
    suite.test[test_frame__test_unknown_frame_type_accepted]()
    suite.test[test_frame__test_grease_frame_type_detection]()
    suite.test[test_frame__test_decoder_rejects_truncated_payload]()
    suite.test[test_frame__test_decoder_rejects_empty_buffer]()
    suite.test[test_frame__test_settings_decoder_rejects_dangling_identifier]()
    # tests/h3/test_h3_0rtt_gate.mojo
    suite.test[test_h3_0rtt_gate__test_idempotent_methods_eligible]()
    suite.test[test_h3_0rtt_gate__test_non_idempotent_methods_excluded]()
    suite.test[test_h3_0rtt_gate__test_method_classification_case_insensitive]()
    suite.test[test_h3_0rtt_gate__test_outcome_carrier_fields]()
    # tests/h3/test_h3_client_e2e.mojo
    suite.test[test_h3_client_e2e__test_h3_get]()
    suite.test[test_h3_client_e2e__test_h3_post_echo]()
    suite.test[test_h3_client_e2e__test_h3_stream_body]()
    # tests/h3/test_h3_client_frag.mojo
    suite.test[test_h3_client_frag__test_large_body_fragments]()
    suite.test[test_h3_client_frag__test_idle_then_reuse]()
    # tests/h3/test_h3_client_mux.mojo
    suite.test[test_h3_client_mux__test_two_concurrent_requests]()
    # tests/h3/test_h3_client_reasm.mojo
    suite.test[test_h3_client_reasm__test_out_of_order_with_dup_and_gap]()
    suite.test[test_h3_client_reasm__test_overlapping_chunk_trimmed]()
    suite.test[test_h3_client_reasm__test_in_order_fast_path]()
    # tests/h3/test_h3_client_streams.mojo
    suite.test[
        test_h3_client_streams__test_request_roundtrip_into_server_reader
    ]()
    suite.test[test_h3_client_streams__test_get_request_no_body]()
    suite.test[
        test_h3_client_streams__test_response_roundtrip_into_client_reader
    ]()
    suite.test[
        test_h3_client_streams__test_response_reader_rejects_control_frame
    ]()
    suite.test[
        test_h3_client_streams__test_control_stream_preamble_is_settings_first
    ]()
    suite.test[test_h3_client_streams__test_qpack_stream_preambles]()
    # tests/h3/test_h3_dispatch.mojo
    suite.test[test_h3_dispatch__test_feed_stream_chunk_implicit_open]()
    suite.test[test_h3_dispatch__test_get_request_surfaces_after_fin]()
    suite.test[test_h3_dispatch__test_take_request_assembles_method_and_path]()
    suite.test[test_h3_dispatch__test_take_request_body_round_trip]()
    suite.test[test_h3_dispatch__test_take_request_is_idempotent_guarded]()
    suite.test[test_h3_dispatch__test_emit_response_buffers_headers_and_data]()
    suite.test[test_h3_dispatch__test_take_response_frames_drains_once]()
    suite.test[test_h3_dispatch__test_emit_response_is_idempotent_guarded]()
    suite.test[test_h3_dispatch__test_garbled_chunk_sets_protocol_error]()
    suite.test[test_h3_dispatch__test_partial_chunk_needs_more_then_completes]()
    # tests/h3/test_h3_end_to_end.mojo
    suite.test[
        test_h3_end_to_end__test_get_request_dispatches_through_handler
    ]()
    suite.test[test_h3_end_to_end__test_post_request_body_echo]()
    suite.test[test_h3_end_to_end__test_concurrent_streams_on_one_connection]()
    suite.test[
        test_h3_end_to_end__test_multiple_connections_dispatch_independently
    ]()
    suite.test[
        test_h3_end_to_end__test_pump_http3_handler_once_drives_handler
    ]()
    suite.test[
        test_h3_end_to_end__test_pump_http3_handler_once_zero_when_no_streams_ready
    ]()
    suite.test[test_h3_end_to_end__test_streaming_response_incremental_data]()
    suite.test[
        test_h3_end_to_end__test_buffered_response_not_registered_as_stream
    ]()
    # tests/h3/test_h3_qpack_dynamic.mojo
    suite.test[
        test_h3_qpack_dynamic__test_encoder_stream_inserts_owe_increment
    ]()
    suite.test[test_h3_qpack_dynamic__test_request_resolves_dynamic_reference]()
    suite.test[
        test_h3_qpack_dynamic__test_split_encoder_chunk_buffers_then_applies
    ]()
    # tests/h3/test_h3_uni_streams.mojo
    suite.test[
        test_h3_uni_streams__test_peer_control_stream_settings_round_trip
    ]()
    suite.test[
        test_h3_uni_streams__test_uni_stream_type_varint_split_across_chunks
    ]()
    suite.test[test_h3_uni_streams__test_qpack_uni_stream_kinds_are_recorded]()
    suite.test[test_h3_uni_streams__test_push_uni_stream_tolerated]()
    suite.test[
        test_h3_uni_streams__test_grease_uni_stream_codepoint_tolerated
    ]()
    suite.test[test_h3_uni_streams__test_settings_twice_is_frame_unexpected]()
    suite.test[
        test_h3_uni_streams__test_non_settings_before_settings_is_missing_settings
    ]()
    suite.test[test_h3_uni_streams__test_goaway_records_peer_max_stream_id]()
    suite.test[test_h3_uni_streams__test_second_peer_control_stream_raises]()
    suite.test[test_h3_uni_streams__test_emit_initial_settings_round_trips]()
    suite.test[
        test_h3_uni_streams__test_emit_goaway_flips_flag_and_double_emit_raises
    ]()
    # tests/h3/test_request_reader.mojo
    suite.test[test_request_reader__test_initial_state]()
    suite.test[test_request_reader__test_headers_only]()
    suite.test[test_request_reader__test_headers_then_data]()
    suite.test[test_request_reader__test_headers_then_data_then_trailers]()
    suite.test[
        test_request_reader__test_data_before_headers_is_protocol_error
    ]()
    suite.test[
        test_request_reader__test_control_frame_on_request_stream_is_protocol_error
    ]()
    suite.test[test_request_reader__test_truncated_frame_yields_needs_more]()
    suite.test[test_request_reader__test_unknown_frame_type_is_skipped]()
    suite.test[test_request_reader__test_oversized_headers_is_protocol_error]()
    suite.test[
        test_request_reader__test_repeat_headers_after_trailers_is_protocol_error
    ]()
    # tests/h3/test_response_writer.mojo
    suite.test[test_response_writer__test_status_only]()
    suite.test[test_response_writer__test_status_with_application_headers]()
    suite.test[test_response_writer__test_invalid_status_raises]()
    suite.test[
        test_response_writer__test_pseudo_header_in_application_headers_raises
    ]()
    suite.test[test_response_writer__test_data_frame_round_trip]()
    suite.test[test_response_writer__test_trailers_round_trip]()
    suite.test[test_response_writer__test_pseudo_header_in_trailers_raises]()
    # tests/h3/test_server_scaffold.mojo
    suite.test[test_server_scaffold__test_stream_type_codepoints]()
    suite.test[test_server_scaffold__test_config_defaults]()
    suite.test[test_server_scaffold__test_h3_connection_defaults]()
    suite.test[test_server_scaffold__test_with_config_overrides]()
    suite.test[test_server_scaffold__test_open_request_stream_tracks_state]()
    suite.test[test_server_scaffold__test_open_request_stream_is_idempotent]()
    suite.test[test_server_scaffold__test_close_request_stream_releases]()
    suite.test[
        test_server_scaffold__test_close_request_stream_unknown_id_is_noop
    ]()
    suite.test[test_server_scaffold__test_goaway_rejects_new_streams]()
    suite.test[
        test_server_scaffold__test_feed_stream_chunk_allocates_stream_implicitly
    ]()
    suite.test[
        test_server_scaffold__test_take_response_frames_empty_when_no_emit
    ]()
    suite^.run()
