"""GENERATED by tests/tools/gen_test_aggregates.py -- do not edit.

Aggregates the 1 test files of ``tests/io/`` into one compiled
binary so the 1 separate compiler invocations become one. Run it with
``mojo -I . -I tests/io`` (see tests/tools/run_test_aggregates.sh).

Regenerate with ``python3 tests/tools/gen_test_aggregates.py``; CI fails if this
file is out of date with the tree.
"""

from std.testing import TestSuite
from test_byte_cursor import (
    test_read_unsigned_be as test_byte_cursor__test_read_unsigned_be,
)
from test_byte_cursor import (
    test_read_unsigned_le as test_byte_cursor__test_read_unsigned_le,
)
from test_byte_cursor import (
    test_read_u64_round_trip_both_endians as test_byte_cursor__test_read_u64_round_trip_both_endians,
)
from test_byte_cursor import (
    test_read_bytes_borrowed as test_byte_cursor__test_read_bytes_borrowed,
)
from test_byte_cursor import (
    test_read_utf8_valid_ascii_and_multibyte as test_byte_cursor__test_read_utf8_valid_ascii_and_multibyte,
)
from test_byte_cursor import (
    test_read_utf8_rejects_invalid as test_byte_cursor__test_read_utf8_rejects_invalid,
)
from test_byte_cursor import (
    test_read_utf8_rejects_truncated_multibyte as test_byte_cursor__test_read_utf8_rejects_truncated_multibyte,
)
from test_byte_cursor import (
    test_read_past_end_raises as test_byte_cursor__test_read_past_end_raises,
)
from test_byte_cursor import (
    test_read_bytes_past_end_raises as test_byte_cursor__test_read_bytes_past_end_raises,
)
from test_byte_cursor import test_skip as test_byte_cursor__test_skip
from test_byte_cursor import (
    test_writer_round_trip_all_widths as test_byte_cursor__test_writer_round_trip_all_widths,
)
from test_byte_cursor import (
    test_writer_bytes_copies as test_byte_cursor__test_writer_bytes_copies,
)


def main() raises:
    var suite = TestSuite()
    # tests/io/test_byte_cursor.mojo
    suite.test[test_byte_cursor__test_read_unsigned_be]()
    suite.test[test_byte_cursor__test_read_unsigned_le]()
    suite.test[test_byte_cursor__test_read_u64_round_trip_both_endians]()
    suite.test[test_byte_cursor__test_read_bytes_borrowed]()
    suite.test[test_byte_cursor__test_read_utf8_valid_ascii_and_multibyte]()
    suite.test[test_byte_cursor__test_read_utf8_rejects_invalid]()
    suite.test[test_byte_cursor__test_read_utf8_rejects_truncated_multibyte]()
    suite.test[test_byte_cursor__test_read_past_end_raises]()
    suite.test[test_byte_cursor__test_read_bytes_past_end_raises]()
    suite.test[test_byte_cursor__test_skip]()
    suite.test[test_byte_cursor__test_writer_round_trip_all_widths]()
    suite.test[test_byte_cursor__test_writer_bytes_copies]()
    suite^.run()
