"""GENERATED by tools/gen_test_aggregates.py -- do not edit.

Aggregates the 1 test files of ``tests/openapi/`` into one compiled
binary so the 1 separate compiler invocations become one. Run it with
``mojo -I . -I tests/openapi`` (see tools/run_test_aggregates.sh).

Regenerate with ``python3 tools/gen_test_aggregates.py``; CI fails if this
file is out of date with the tree.
"""

from std.testing import TestSuite
from test_openapi import (
    test_minimal_spec_round_trips_through_json_parser as test_openapi__test_minimal_spec_round_trips_through_json_parser,
)
from test_openapi import (
    test_path_with_get_operation as test_openapi__test_path_with_get_operation,
)
from test_openapi import (
    test_json_escaping_preserves_special_chars as test_openapi__test_json_escaping_preserves_special_chars,
)
from test_openapi import (
    test_emitter_is_deterministic as test_openapi__test_emitter_is_deterministic,
)
from test_openapi import (
    test_spec_from_router_paths_and_params as test_openapi__test_spec_from_router_paths_and_params,
)
from test_openapi import (
    test_spec_from_router_is_deterministic as test_openapi__test_spec_from_router_is_deterministic,
)


def main() raises:
    var suite = TestSuite()
    # tests/openapi/test_openapi.mojo
    suite.test[
        test_openapi__test_minimal_spec_round_trips_through_json_parser
    ]()
    suite.test[test_openapi__test_path_with_get_operation]()
    suite.test[test_openapi__test_json_escaping_preserves_special_chars]()
    suite.test[test_openapi__test_emitter_is_deterministic]()
    suite.test[test_openapi__test_spec_from_router_paths_and_params]()
    suite.test[test_openapi__test_spec_from_router_is_deterministic]()
    suite^.run()
